// finance_messages.go — hand-written proto message types for the
// OnPaymentReceived RPC added in S3-E-03.
//
// NOTE: These types would normally be generated by protoc from finance.proto.
// They are written by hand because protoc is not available in the sandbox.
// Run `make genpb` to regenerate cleanly from finance.proto once protoc is
// available in the build environment.
//
// OnPaymentReceived is called by booking-svc after a booking transitions to
// paid_in_full, triggering a double-entry journal posting in finance-svc.

package pb

// OnPaymentReceivedRequest carries the payment details needed to create a
// journal entry (Dr Bank / Cr Pilgrim Liability).
// Amount is int64 (integer IDR) per §S3-J-03 contract — no fractional IDR.
type OnPaymentReceivedRequest struct {
	BookingId   string
	InvoiceId   string
	Amount      int64  // integer IDR — no fractional amounts (§S3-J-03)
	ReceivedAt  string // RFC3339 timestamp; empty = use server time
}

func (x *OnPaymentReceivedRequest) GetBookingId() string {
	if x == nil {
		return ""
	}
	return x.BookingId
}

func (x *OnPaymentReceivedRequest) GetInvoiceId() string {
	if x == nil {
		return ""
	}
	return x.InvoiceId
}

func (x *OnPaymentReceivedRequest) GetAmount() int64 {
	if x == nil {
		return 0
	}
	return x.Amount
}

func (x *OnPaymentReceivedRequest) GetReceivedAt() string {
	if x == nil {
		return ""
	}
	return x.ReceivedAt
}

// OnPaymentReceivedResponse returns the journal entry that was created (or the
// existing entry if already posted for this invoice).
type OnPaymentReceivedResponse struct {
	EntryId  string
	Balanced bool
}

func (x *OnPaymentReceivedResponse) GetEntryId() string {
	if x == nil {
		return ""
	}
	return x.EntryId
}

func (x *OnPaymentReceivedResponse) GetBalanced() bool {
	if x == nil {
		return false
	}
	return x.Balanced
}
