// pl_messages.go — hand-written proto message types for revenue recognition,
// P&L report, and balance sheet RPCs (finance depth / Wave 1B).
//
// NOTE: These types would normally be generated by protoc from finance.proto.
// They are written by hand because protoc is not available in the sandbox.
// Run `make genpb` to regenerate cleanly from finance.proto once protoc is
// available in the build environment.

package pb

// ---------------------------------------------------------------------------
// RecognizeRevenue
// ---------------------------------------------------------------------------

// RecognizeRevenueRequest is the request for the RecognizeRevenue RPC.
// Posts Dr 2001 (Pilgrim Liability) / Cr 4001 (Revenue).
// Idempotent on departure_id.
type RecognizeRevenueRequest struct {
	DepartureId    string
	TotalAmountIdr int64 // integer IDR — no fractional amounts
}

func (x *RecognizeRevenueRequest) GetDepartureId() string {
	if x == nil {
		return ""
	}
	return x.DepartureId
}

func (x *RecognizeRevenueRequest) GetTotalAmountIdr() int64 {
	if x == nil {
		return 0
	}
	return x.TotalAmountIdr
}

// RecognizeRevenueResponse is the response for the RecognizeRevenue RPC.
type RecognizeRevenueResponse struct {
	EntryId      string // UUID of the journal entry
	RecognizedAt string // RFC3339 timestamp of when the entry was posted
	Replayed     bool   // true if an existing entry was returned (idempotent replay)
}

func (x *RecognizeRevenueResponse) GetEntryId() string {
	if x == nil {
		return ""
	}
	return x.EntryId
}

func (x *RecognizeRevenueResponse) GetRecognizedAt() string {
	if x == nil {
		return ""
	}
	return x.RecognizedAt
}

func (x *RecognizeRevenueResponse) GetReplayed() bool {
	if x == nil {
		return false
	}
	return x.Replayed
}

// ---------------------------------------------------------------------------
// GetPLReport
// ---------------------------------------------------------------------------

// GetPLReportRequest is the request for the GetPLReport RPC.
// From and To are optional RFC3339 date/time strings (empty = unbounded).
type GetPLReportRequest struct {
	From string // optional RFC3339 lower bound (inclusive)
	To   string // optional RFC3339 upper bound (inclusive)
}

func (x *GetPLReportRequest) GetFrom() string {
	if x == nil {
		return ""
	}
	return x.From
}

func (x *GetPLReportRequest) GetTo() string {
	if x == nil {
		return ""
	}
	return x.To
}

// PLLineItemProto is the wire representation of one P&L line item.
type PLLineItemProto struct {
	AccountCode string
	AccountName string
	Amount      int64  // integer IDR
	Direction   string // "revenue" or "expense"
}

func (x *PLLineItemProto) GetAccountCode() string {
	if x == nil {
		return ""
	}
	return x.AccountCode
}

func (x *PLLineItemProto) GetAccountName() string {
	if x == nil {
		return ""
	}
	return x.AccountName
}

func (x *PLLineItemProto) GetAmount() int64 {
	if x == nil {
		return 0
	}
	return x.Amount
}

func (x *PLLineItemProto) GetDirection() string {
	if x == nil {
		return ""
	}
	return x.Direction
}

// PLReportProto is the wire representation of a P&L report.
type PLReportProto struct {
	PeriodFrom   string           // RFC3339
	PeriodTo     string           // RFC3339
	GeneratedAt  string           // RFC3339
	TotalRevenue int64            // sum of Cr 4001
	TotalCogs    int64            // sum of Dr 5001
	GrossProfit  int64            // TotalRevenue - TotalCOGS
	OtherIncome  int64            // Cr account 4xxx (non-4001)
	OtherExpense int64            // Dr account 5xxx (non-5001)
	NetProfit    int64            // GrossProfit + OtherIncome - OtherExpense
	Entries      []*PLLineItemProto
}

func (x *PLReportProto) GetPeriodFrom() string {
	if x == nil {
		return ""
	}
	return x.PeriodFrom
}

func (x *PLReportProto) GetPeriodTo() string {
	if x == nil {
		return ""
	}
	return x.PeriodTo
}

func (x *PLReportProto) GetGeneratedAt() string {
	if x == nil {
		return ""
	}
	return x.GeneratedAt
}

func (x *PLReportProto) GetTotalRevenue() int64 {
	if x == nil {
		return 0
	}
	return x.TotalRevenue
}

func (x *PLReportProto) GetTotalCogs() int64 {
	if x == nil {
		return 0
	}
	return x.TotalCogs
}

func (x *PLReportProto) GetGrossProfit() int64 {
	if x == nil {
		return 0
	}
	return x.GrossProfit
}

func (x *PLReportProto) GetOtherIncome() int64 {
	if x == nil {
		return 0
	}
	return x.OtherIncome
}

func (x *PLReportProto) GetOtherExpense() int64 {
	if x == nil {
		return 0
	}
	return x.OtherExpense
}

func (x *PLReportProto) GetNetProfit() int64 {
	if x == nil {
		return 0
	}
	return x.NetProfit
}

func (x *PLReportProto) GetEntries() []*PLLineItemProto {
	if x == nil {
		return nil
	}
	return x.Entries
}

// ---------------------------------------------------------------------------
// GetBalanceSheet
// ---------------------------------------------------------------------------

// GetBalanceSheetRequest is the request for the GetBalanceSheet RPC.
// AsOf is an optional RFC3339 date/time string (empty = all history).
type GetBalanceSheetRequest struct {
	AsOf string // optional RFC3339 upper bound (inclusive)
}

func (x *GetBalanceSheetRequest) GetAsOf() string {
	if x == nil {
		return ""
	}
	return x.AsOf
}

// BalanceSheetLineProto is the wire representation of one balance-sheet line.
type BalanceSheetLineProto struct {
	AccountCode string
	AccountName string
	Balance     int64 // net balance in integer IDR
}

func (x *BalanceSheetLineProto) GetAccountCode() string {
	if x == nil {
		return ""
	}
	return x.AccountCode
}

func (x *BalanceSheetLineProto) GetAccountName() string {
	if x == nil {
		return ""
	}
	return x.AccountName
}

func (x *BalanceSheetLineProto) GetBalance() int64 {
	if x == nil {
		return 0
	}
	return x.Balance
}

// BalanceSheetProto is the wire representation of a balance sheet.
type BalanceSheetProto struct {
	AsOfDate         string                   // RFC3339
	GeneratedAt      string                   // RFC3339
	Assets           []*BalanceSheetLineProto // account_code 1xxx
	Liabilities      []*BalanceSheetLineProto // account_code 2xxx
	Equity           []*BalanceSheetLineProto // account_code 3xxx
	TotalAssets      int64
	TotalLiabilities int64
	TotalEquity      int64
}

func (x *BalanceSheetProto) GetAsOfDate() string {
	if x == nil {
		return ""
	}
	return x.AsOfDate
}

func (x *BalanceSheetProto) GetGeneratedAt() string {
	if x == nil {
		return ""
	}
	return x.GeneratedAt
}

func (x *BalanceSheetProto) GetAssets() []*BalanceSheetLineProto {
	if x == nil {
		return nil
	}
	return x.Assets
}

func (x *BalanceSheetProto) GetLiabilities() []*BalanceSheetLineProto {
	if x == nil {
		return nil
	}
	return x.Liabilities
}

func (x *BalanceSheetProto) GetEquity() []*BalanceSheetLineProto {
	if x == nil {
		return nil
	}
	return x.Equity
}

func (x *BalanceSheetProto) GetTotalAssets() int64 {
	if x == nil {
		return 0
	}
	return x.TotalAssets
}

func (x *BalanceSheetProto) GetTotalLiabilities() int64 {
	if x == nil {
		return 0
	}
	return x.TotalLiabilities
}

func (x *BalanceSheetProto) GetTotalEquity() int64 {
	if x == nil {
		return 0
	}
	return x.TotalEquity
}
