// reports_messages.go — hand-written proto message types for the
// GetFinanceSummary and ListJournalEntries RPCs added in S5-E-01.
//
// NOTE: These types would normally be generated by protoc from finance.proto.
// They are written by hand because protoc is not available in the sandbox.
// Run `make genpb` to regenerate cleanly from finance.proto once protoc is
// available in the build environment.

package pb

// ---------------------------------------------------------------------------
// GetFinanceSummary
// ---------------------------------------------------------------------------

// GetFinanceSummaryRequest is the request message for GetFinanceSummary RPC.
// No filter fields — returns all account balances.
type GetFinanceSummaryRequest struct{}

// AccountBalance holds the aggregated debit/credit and net balance for one
// account code. All amounts are int64 IDR (integer rupiah, no fractions).
type AccountBalance struct {
	AccountCode string
	DebitTotal  int64 // integer IDR
	CreditTotal int64 // integer IDR
	Net         int64 // DebitTotal - CreditTotal
}

func (x *AccountBalance) GetAccountCode() string {
	if x == nil {
		return ""
	}
	return x.AccountCode
}
func (x *AccountBalance) GetDebitTotal() int64 {
	if x == nil {
		return 0
	}
	return x.DebitTotal
}
func (x *AccountBalance) GetCreditTotal() int64 {
	if x == nil {
		return 0
	}
	return x.CreditTotal
}
func (x *AccountBalance) GetNet() int64 {
	if x == nil {
		return 0
	}
	return x.Net
}

// GetFinanceSummaryResponse holds the list of account balances.
type GetFinanceSummaryResponse struct {
	Accounts []*AccountBalance
}

func (x *GetFinanceSummaryResponse) GetAccounts() []*AccountBalance {
	if x == nil {
		return nil
	}
	return x.Accounts
}

// ---------------------------------------------------------------------------
// ListJournalEntries
// ---------------------------------------------------------------------------

// ListJournalEntriesRequest is the request message for ListJournalEntries RPC.
// From, To, and Cursor are optional RFC3339 strings (empty = not set).
// Limit defaults to 50 if zero.
type ListJournalEntriesRequest struct {
	From   string // optional RFC3339 date/time lower bound
	To     string // optional RFC3339 date/time upper bound
	Limit  int32  // max entries to return (default 50)
	Cursor string // optional RFC3339 timestamp cursor (posted_at of last seen entry)
}

func (x *ListJournalEntriesRequest) GetFrom() string {
	if x == nil {
		return ""
	}
	return x.From
}
func (x *ListJournalEntriesRequest) GetTo() string {
	if x == nil {
		return ""
	}
	return x.To
}
func (x *ListJournalEntriesRequest) GetLimit() int32 {
	if x == nil {
		return 0
	}
	return x.Limit
}
func (x *ListJournalEntriesRequest) GetCursor() string {
	if x == nil {
		return ""
	}
	return x.Cursor
}

// JournalLineProto is the wire representation of one journal line.
// All amounts are int64 IDR.
type JournalLineProto struct {
	Id          string
	EntryId     string
	AccountCode string
	Debit       int64 // integer IDR
	Credit      int64 // integer IDR
}

func (x *JournalLineProto) GetId() string {
	if x == nil {
		return ""
	}
	return x.Id
}
func (x *JournalLineProto) GetEntryId() string {
	if x == nil {
		return ""
	}
	return x.EntryId
}
func (x *JournalLineProto) GetAccountCode() string {
	if x == nil {
		return ""
	}
	return x.AccountCode
}
func (x *JournalLineProto) GetDebit() int64 {
	if x == nil {
		return 0
	}
	return x.Debit
}
func (x *JournalLineProto) GetCredit() int64 {
	if x == nil {
		return 0
	}
	return x.Credit
}

// JournalEntryProto is the wire representation of one journal entry with its lines.
type JournalEntryProto struct {
	Id             string
	IdempotencyKey string
	SourceType     string
	SourceId       string
	PostedAt       string // RFC3339
	Description    string
	Lines          []*JournalLineProto
}

func (x *JournalEntryProto) GetId() string {
	if x == nil {
		return ""
	}
	return x.Id
}
func (x *JournalEntryProto) GetIdempotencyKey() string {
	if x == nil {
		return ""
	}
	return x.IdempotencyKey
}
func (x *JournalEntryProto) GetSourceType() string {
	if x == nil {
		return ""
	}
	return x.SourceType
}
func (x *JournalEntryProto) GetSourceId() string {
	if x == nil {
		return ""
	}
	return x.SourceId
}
func (x *JournalEntryProto) GetPostedAt() string {
	if x == nil {
		return ""
	}
	return x.PostedAt
}
func (x *JournalEntryProto) GetDescription() string {
	if x == nil {
		return ""
	}
	return x.Description
}
func (x *JournalEntryProto) GetLines() []*JournalLineProto {
	if x == nil {
		return nil
	}
	return x.Lines
}

// ListJournalEntriesResponse holds the page of entries plus the next cursor.
// NextCursor is the posted_at of the last entry in this page (RFC3339).
// Empty NextCursor means no more pages.
type ListJournalEntriesResponse struct {
	Entries    []*JournalEntryProto
	NextCursor string
}

func (x *ListJournalEntriesResponse) GetEntries() []*JournalEntryProto {
	if x == nil {
		return nil
	}
	return x.Entries
}
func (x *ListJournalEntriesResponse) GetNextCursor() string {
	if x == nil {
		return ""
	}
	return x.NextCursor
}
