// Package rest_oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package rest_oapi

import (
	"context"
	"fmt"
	"net/url"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AddonRefSettlementCurrency.
const (
	AddonRefSettlementCurrencyIDR AddonRefSettlementCurrency = "IDR"
)

// Defines values for DepartureStatus.
const (
	Closed DepartureStatus = "closed"
	Open   DepartureStatus = "open"
)

// Defines values for MoneySettlementCurrency.
const (
	MoneySettlementCurrencyIDR MoneySettlementCurrency = "IDR"
)

// Defines values for OperatorKind.
const (
	Airline OperatorKind = "airline"
	Bus     OperatorKind = "bus"
	Rail    OperatorKind = "rail"
)

// Defines values for PackageKind.
const (
	Badal        PackageKind = "badal"
	Financial    PackageKind = "financial"
	HajjFuroda   PackageKind = "hajj_furoda"
	HajjKhusus   PackageKind = "hajj_khusus"
	Retail       PackageKind = "retail"
	UmrahPlus    PackageKind = "umrah_plus"
	UmrahReguler PackageKind = "umrah_reguler"
)

// Defines values for PackagePricingSettlementCurrency.
const (
	IDR PackagePricingSettlementCurrency = "IDR"
)

// Defines values for RoomType.
const (
	Double RoomType = "double"
	Quad   RoomType = "quad"
	Triple RoomType = "triple"
)

// Defines values for UserProfileStatus.
const (
	Active    UserProfileStatus = "active"
	Pending   UserProfileStatus = "pending"
	Suspended UserProfileStatus = "suspended"
)

// Defines values for VendorReadinessState.
const (
	Blocked    VendorReadinessState = "blocked"
	InProgress VendorReadinessState = "in_progress"
	NotStarted VendorReadinessState = "not_started"
	Ready      VendorReadinessState = "ready"
)

// AddonRef defines model for AddonRef.
type AddonRef struct {
	Id                 string                     `json:"id"`
	ListAmount         int64                      `json:"list_amount"`
	ListCurrency       string                     `json:"list_currency"`
	Name               string                     `json:"name"`
	SettlementCurrency AddonRefSettlementCurrency `json:"settlement_currency"`
}

// AddonRefSettlementCurrency defines model for AddonRef.SettlementCurrency.
type AddonRefSettlementCurrency string

// AirlineRef defines model for AirlineRef.
type AirlineRef struct {
	Code         string       `json:"code"`
	Id           string       `json:"id"`
	Name         string       `json:"name"`
	OperatorKind OperatorKind `json:"operator_kind"`
}

// CatalogErrorResponse defines model for CatalogErrorResponse.
type CatalogErrorResponse struct {
	Error struct {
		// Code snake_case catalog error code (e.g. `package_not_found`,
		// `departure_not_found`, `invalid_query_param`,
		// `invalid_cursor`, `internal_error`, `service_unavailable`).
		Code string `json:"code"`

		// Message Human-readable message in Bahasa Indonesia (Q003).
		Message string `json:"message"`

		// TraceId OTel span ID (hex) for correlation with Tempo.
		TraceId *string `json:"trace_id,omitempty"`
	} `json:"error"`
}

// DepartureDetail defines model for DepartureDetail.
type DepartureDetail struct {
	DepartureDate   openapi_types.Date `json:"departure_date"`
	Id              string             `json:"id"`
	PackageId       string             `json:"package_id"`
	Pricing         []PackagePricing   `json:"pricing"`
	RemainingSeats  int                `json:"remaining_seats"`
	ReturnDate      openapi_types.Date `json:"return_date"`
	Status          DepartureStatus    `json:"status"`
	TotalSeats      int                `json:"total_seats"`
	VendorReadiness VendorReadiness    `json:"vendor_readiness"`
}

// DepartureStatus defines model for DepartureStatus.
type DepartureStatus string

// DepartureSummary defines model for DepartureSummary.
type DepartureSummary struct {
	DepartureDate  openapi_types.Date `json:"departure_date"`
	Id             string             `json:"id"`
	RemainingSeats int                `json:"remaining_seats"`
	ReturnDate     openapi_types.Date `json:"return_date"`
	Status         DepartureStatus    `json:"status"`
}

// EnrollTotpResponse defines model for EnrollTotpResponse.
type EnrollTotpResponse struct {
	Data struct {
		// OtpauthUrl otpauth:// URL — render as QR code in the UI.
		OtpauthUrl string `json:"otpauth_url"`

		// Secret Plaintext base32 secret. Shown exactly once; discard after display.
		Secret string `json:"secret"`
	} `json:"data"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code UPPER_SNAKE error code emitted by the central error middleware.
		// Matches iam-svc's legacy REST envelope so existing clients /
		// e2e bodies are unaffected. Common values: `VALIDATION_ERROR`,
		// `UNAUTHORIZED`, `FORBIDDEN`, `NOT_FOUND`, `CONFLICT`,
		// `SERVICE_UNAVAILABLE`, `INTERNAL_ERROR`.
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// GetDepartureResponse defines model for GetDepartureResponse.
type GetDepartureResponse struct {
	Departure DepartureDetail `json:"departure"`
}

// GetMeResponse defines model for GetMeResponse.
type GetMeResponse struct {
	Data struct {
		// TotpEnrolled True once the user has called POST /v1/me/2fa/enroll at least once.
		TotpEnrolled bool `json:"totp_enrolled"`

		// TotpVerified True once the user has successfully verified an enrolled secret.
		TotpVerified bool        `json:"totp_verified"`
		User         UserProfile `json:"user"`
	} `json:"data"`
}

// GetPackageResponse defines model for GetPackageResponse.
type GetPackageResponse struct {
	Package PackageDetail `json:"package"`
}

// HotelRef defines model for HotelRef.
type HotelRef struct {
	City             string `json:"city"`
	Id               string `json:"id"`
	Name             string `json:"name"`
	StarRating       int    `json:"star_rating"`
	WalkingDistanceM int    `json:"walking_distance_m"`
}

// Itinerary defines model for Itinerary.
type Itinerary struct {
	Days      []ItineraryDay `json:"days"`
	Id        string         `json:"id"`
	PublicUrl string         `json:"public_url"`
}

// ItineraryDay defines model for ItineraryDay.
type ItineraryDay struct {
	Day         int     `json:"day"`
	Description string  `json:"description"`
	PhotoUrl    *string `json:"photo_url,omitempty"`
	Title       string  `json:"title"`
}

// ListPackagesResponse defines model for ListPackagesResponse.
type ListPackagesResponse struct {
	Packages []PackageListItem `json:"packages"`
	Page     PageMeta          `json:"page"`
}

// LiveResponse defines model for LiveResponse.
type LiveResponse struct {
	Data struct {
		Ok bool `json:"ok"`
	} `json:"data"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email openapi_types.Email `json:"email"`

	// Password Plaintext password; bcrypt-compared server-side. Never logged.
	Password string `json:"password"`

	// TotpCode Six-digit TOTP code. Accepted but unused in BL-IAM-001 (login-time
	// TOTP enforcement lands in S1-E-06). Clients should still send the
	// code after enrollment so they don't need to adapt when enforcement
	// flips on.
	TotpCode *string `json:"totp_code,omitempty"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Data struct {
		AccessExpiresAt time.Time `json:"access_expires_at"`

		// AccessToken PASETO-signed access token. Short-lived.
		AccessToken      string    `json:"access_token"`
		RefreshExpiresAt time.Time `json:"refresh_expires_at"`

		// RefreshToken Opaque refresh token (hex-encoded). Store client-side; only its SHA-256 digest persists server-side.
		RefreshToken string      `json:"refresh_token"`
		User         UserProfile `json:"user"`
	} `json:"data"`
}

// Money defines model for Money.
type Money struct {
	ListAmount         int64                   `json:"list_amount"`
	ListCurrency       string                  `json:"list_currency"`
	SettlementCurrency MoneySettlementCurrency `json:"settlement_currency"`
}

// MoneySettlementCurrency defines model for Money.SettlementCurrency.
type MoneySettlementCurrency string

// MuthawwifRef defines model for MuthawwifRef.
type MuthawwifRef struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	PortraitUrl string `json:"portrait_url"`
}

// NextDeparture defines model for NextDeparture.
type NextDeparture struct {
	DepartureDate  openapi_types.Date `json:"departure_date"`
	Id             string             `json:"id"`
	RemainingSeats int                `json:"remaining_seats"`
	ReturnDate     openapi_types.Date `json:"return_date"`
}

// OperatorKind defines model for OperatorKind.
type OperatorKind string

// PackageDetail defines model for PackageDetail.
type PackageDetail struct {
	AddOns        []AddonRef         `json:"add_ons"`
	Airline       *AirlineRef        `json:"airline"`
	CoverPhotoUrl string             `json:"cover_photo_url"`
	Departures    []DepartureSummary `json:"departures"`
	Description   string             `json:"description"`
	Highlights    []string           `json:"highlights"`
	Hotels        []HotelRef         `json:"hotels"`
	Id            string             `json:"id"`
	Itinerary     *Itinerary         `json:"itinerary"`
	Kind          PackageKind        `json:"kind"`
	Muthawwif     *MuthawwifRef      `json:"muthawwif"`
	Name          string             `json:"name"`
}

// PackageKind defines model for PackageKind.
type PackageKind string

// PackageListItem defines model for PackageListItem.
type PackageListItem struct {
	CoverPhotoUrl string         `json:"cover_photo_url"`
	Description   string         `json:"description"`
	Id            string         `json:"id"`
	Kind          PackageKind    `json:"kind"`
	Name          string         `json:"name"`
	NextDeparture *NextDeparture `json:"next_departure"`
	StartingPrice Money          `json:"starting_price"`
}

// PackagePricing defines model for PackagePricing.
type PackagePricing struct {
	ListAmount         int64                            `json:"list_amount"`
	ListCurrency       string                           `json:"list_currency"`
	RoomType           RoomType                         `json:"room_type"`
	SettlementCurrency PackagePricingSettlementCurrency `json:"settlement_currency"`
}

// PackagePricingSettlementCurrency defines model for PackagePricing.SettlementCurrency.
type PackagePricingSettlementCurrency string

// PageMeta defines model for PageMeta.
type PageMeta struct {
	HasMore    bool    `json:"has_more"`
	NextCursor *string `json:"next_cursor"`
}

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	Data struct {
		Ok bool `json:"ok"`
	} `json:"data"`
}

// RefreshSessionRequest defines model for RefreshSessionRequest.
type RefreshSessionRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RefreshSessionResponse defines model for RefreshSessionResponse.
type RefreshSessionResponse struct {
	Data struct {
		AccessExpiresAt  time.Time `json:"access_expires_at"`
		AccessToken      string    `json:"access_token"`
		RefreshExpiresAt time.Time `json:"refresh_expires_at"`
		RefreshToken     string    `json:"refresh_token"`
	} `json:"data"`
}

// RoomType defines model for RoomType.
type RoomType string

// SuspendUserResponse defines model for SuspendUserResponse.
type SuspendUserResponse struct {
	Data struct {
		User UserProfile `json:"user"`
	} `json:"data"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	// BranchId Home-branch UUID. Empty for branch-less staff (super_admin seed).
	BranchId *openapi_types.UUID `json:"branch_id,omitempty"`
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`

	// Status Matches iam.users.status enum.
	Status UserProfileStatus `json:"status"`

	// UserId User UUID.
	UserId openapi_types.UUID `json:"user_id"`
}

// UserProfileStatus Matches iam.users.status enum.
type UserProfileStatus string

// VendorReadiness defines model for VendorReadiness.
type VendorReadiness struct {
	Hotel  VendorReadinessState `json:"hotel"`
	Ticket VendorReadinessState `json:"ticket"`
	Visa   VendorReadinessState `json:"visa"`
}

// VendorReadinessState defines model for VendorReadinessState.
type VendorReadinessState string

// VerifyTotpRequest defines model for VerifyTotpRequest.
type VerifyTotpRequest struct {
	// Code Six-digit TOTP code from the user's authenticator.
	Code string `json:"code"`
}

// VerifyTotpResponse defines model for VerifyTotpResponse.
type VerifyTotpResponse struct {
	Data struct {
		VerifiedAt time.Time `json:"verified_at"`
	} `json:"data"`
}

// ListPackagesParams defines parameters for ListPackages.
type ListPackagesParams struct {
	Kind          *PackageKind        `form:"kind,omitempty" json:"kind,omitempty"`
	AirlineCode   *string             `form:"airline_code,omitempty" json:"airline_code,omitempty"`
	HotelId       *string             `form:"hotel_id,omitempty" json:"hotel_id,omitempty"`
	DepartureFrom *openapi_types.Date `form:"departure_from,omitempty" json:"departure_from,omitempty"`
	DepartureTo   *openapi_types.Date `form:"departure_to,omitempty" json:"departure_to,omitempty"`
	Cursor        *string             `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit         *int                `form:"limit,omitempty" json:"limit,omitempty"`
}

// VerifyTotpJSONRequestBody defines body for VerifyTotp for application/json ContentType.
type VerifyTotpJSONRequestBody = VerifyTotpRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshSessionJSONRequestBody defines body for RefreshSession for application/json ContentType.
type RefreshSessionJSONRequestBody = RefreshSessionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /system/live)
	Liveness(c *fiber.Ctx) error
	// Readiness probe
	// (GET /system/ready)
	Readiness(c *fiber.Ctx) error
	// Proxy finance-svc liveness
	// (GET /v1/finance/system/live)
	GetFinanceSystemLive(c *fiber.Ctx) error
	// Current user profile
	// (GET /v1/me)
	GetMe(c *fiber.Ctx) error
	// Begin TOTP enrollment — generate a secret + otpauth URL
	// (POST /v1/me/2fa/enroll)
	EnrollTotp(c *fiber.Ctx) error
	// Verify TOTP code and mark enrollment complete
	// (POST /v1/me/2fa/verify)
	VerifyTotp(c *fiber.Ctx) error
	// Active package-departure detail
	// (GET /v1/package-departures/{id})
	GetPackageDepartureById(c *fiber.Ctx, id string) error
	// List active packages
	// (GET /v1/packages)
	ListPackages(c *fiber.Ctx, params ListPackagesParams) error
	// Active package detail
	// (GET /v1/packages/{id})
	GetPackageById(c *fiber.Ctx, id string) error
	// Logout — revoke the current session row
	// (DELETE /v1/sessions)
	Logout(c *fiber.Ctx) error
	// Login — exchange credentials for an access + refresh pair
	// (POST /v1/sessions)
	Login(c *fiber.Ctx) error
	// Rotate refresh token — issue a new access + refresh pair
	// (POST /v1/sessions/refresh)
	RefreshSession(c *fiber.Ctx) error
	// Suspend a user and revoke every active session
	// (POST /v1/users/{id}/suspend)
	SuspendUser(c *fiber.Ctx, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// Liveness operation middleware
func (siw *ServerInterfaceWrapper) Liveness(c *fiber.Ctx) error {

	return siw.Handler.Liveness(c)
}

// Readiness operation middleware
func (siw *ServerInterfaceWrapper) Readiness(c *fiber.Ctx) error {

	return siw.Handler.Readiness(c)
}

// GetFinanceSystemLive operation middleware
func (siw *ServerInterfaceWrapper) GetFinanceSystemLive(c *fiber.Ctx) error {

	return siw.Handler.GetFinanceSystemLive(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetMe(c)
}

// EnrollTotp operation middleware
func (siw *ServerInterfaceWrapper) EnrollTotp(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.EnrollTotp(c)
}

// VerifyTotp operation middleware
func (siw *ServerInterfaceWrapper) VerifyTotp(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.VerifyTotp(c)
}

// GetPackageDepartureById operation middleware
func (siw *ServerInterfaceWrapper) GetPackageDepartureById(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetPackageDepartureById(c, id)
}

// ListPackages operation middleware
func (siw *ServerInterfaceWrapper) ListPackages(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPackagesParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameter("form", true, false, "kind", query, &params.Kind)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter kind: %w", err).Error())
	}

	// ------------- Optional query parameter "airline_code" -------------

	err = runtime.BindQueryParameter("form", true, false, "airline_code", query, &params.AirlineCode)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter airline_code: %w", err).Error())
	}

	// ------------- Optional query parameter "hotel_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "hotel_id", query, &params.HotelId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter hotel_id: %w", err).Error())
	}

	// ------------- Optional query parameter "departure_from" -------------

	err = runtime.BindQueryParameter("form", true, false, "departure_from", query, &params.DepartureFrom)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter departure_from: %w", err).Error())
	}

	// ------------- Optional query parameter "departure_to" -------------

	err = runtime.BindQueryParameter("form", true, false, "departure_to", query, &params.DepartureTo)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter departure_to: %w", err).Error())
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", query, &params.Cursor)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cursor: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.ListPackages(c, params)
}

// GetPackageById operation middleware
func (siw *ServerInterfaceWrapper) GetPackageById(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetPackageById(c, id)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.Logout(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *fiber.Ctx) error {

	return siw.Handler.Login(c)
}

// RefreshSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshSession(c *fiber.Ctx) error {

	return siw.Handler.RefreshSession(c)
}

// SuspendUser operation middleware
func (siw *ServerInterfaceWrapper) SuspendUser(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.SuspendUser(c, id)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/system/live", wrapper.Liveness)

	router.Get(options.BaseURL+"/system/ready", wrapper.Readiness)

	router.Get(options.BaseURL+"/v1/finance/system/live", wrapper.GetFinanceSystemLive)

	router.Get(options.BaseURL+"/v1/me", wrapper.GetMe)

	router.Post(options.BaseURL+"/v1/me/2fa/enroll", wrapper.EnrollTotp)

	router.Post(options.BaseURL+"/v1/me/2fa/verify", wrapper.VerifyTotp)

	router.Get(options.BaseURL+"/v1/package-departures/:id", wrapper.GetPackageDepartureById)

	router.Get(options.BaseURL+"/v1/packages", wrapper.ListPackages)

	router.Get(options.BaseURL+"/v1/packages/:id", wrapper.GetPackageById)

	router.Delete(options.BaseURL+"/v1/sessions", wrapper.Logout)

	router.Post(options.BaseURL+"/v1/sessions", wrapper.Login)

	router.Post(options.BaseURL+"/v1/sessions/refresh", wrapper.RefreshSession)

	router.Post(options.BaseURL+"/v1/users/:id/suspend", wrapper.SuspendUser)

}

type LivenessRequestObject struct {
}

type LivenessResponseObject interface {
	VisitLivenessResponse(ctx *fiber.Ctx) error
}

type Liveness200JSONResponse LiveResponse

func (response Liveness200JSONResponse) VisitLivenessResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ReadinessRequestObject struct {
}

type ReadinessResponseObject interface {
	VisitReadinessResponse(ctx *fiber.Ctx) error
}

type Readiness200JSONResponse ReadyResponse

func (response Readiness200JSONResponse) VisitReadinessResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetFinanceSystemLiveRequestObject struct {
}

type GetFinanceSystemLiveResponseObject interface {
	VisitGetFinanceSystemLiveResponse(ctx *fiber.Ctx) error
}

type GetFinanceSystemLive200JSONResponse LiveResponse

func (response GetFinanceSystemLive200JSONResponse) VisitGetFinanceSystemLiveResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetFinanceSystemLive502JSONResponse ErrorResponse

func (response GetFinanceSystemLive502JSONResponse) VisitGetFinanceSystemLiveResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(502)

	return ctx.JSON(&response)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(ctx *fiber.Ctx) error
}

type GetMe200JSONResponse GetMeResponse

func (response GetMe200JSONResponse) VisitGetMeResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetMe401JSONResponse ErrorResponse

func (response GetMe401JSONResponse) VisitGetMeResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetMe404JSONResponse ErrorResponse

func (response GetMe404JSONResponse) VisitGetMeResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetMe502JSONResponse ErrorResponse

func (response GetMe502JSONResponse) VisitGetMeResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(502)

	return ctx.JSON(&response)
}

type EnrollTotpRequestObject struct {
}

type EnrollTotpResponseObject interface {
	VisitEnrollTotpResponse(ctx *fiber.Ctx) error
}

type EnrollTotp200JSONResponse EnrollTotpResponse

func (response EnrollTotp200JSONResponse) VisitEnrollTotpResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type EnrollTotp401JSONResponse ErrorResponse

func (response EnrollTotp401JSONResponse) VisitEnrollTotpResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type EnrollTotp409JSONResponse ErrorResponse

func (response EnrollTotp409JSONResponse) VisitEnrollTotpResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type EnrollTotp502JSONResponse ErrorResponse

func (response EnrollTotp502JSONResponse) VisitEnrollTotpResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(502)

	return ctx.JSON(&response)
}

type VerifyTotpRequestObject struct {
	Body *VerifyTotpJSONRequestBody
}

type VerifyTotpResponseObject interface {
	VisitVerifyTotpResponse(ctx *fiber.Ctx) error
}

type VerifyTotp200JSONResponse VerifyTotpResponse

func (response VerifyTotp200JSONResponse) VisitVerifyTotpResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type VerifyTotp400JSONResponse ErrorResponse

func (response VerifyTotp400JSONResponse) VisitVerifyTotpResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type VerifyTotp401JSONResponse ErrorResponse

func (response VerifyTotp401JSONResponse) VisitVerifyTotpResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type VerifyTotp422JSONResponse ErrorResponse

func (response VerifyTotp422JSONResponse) VisitVerifyTotpResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type VerifyTotp502JSONResponse ErrorResponse

func (response VerifyTotp502JSONResponse) VisitVerifyTotpResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(502)

	return ctx.JSON(&response)
}

type GetPackageDepartureByIdRequestObject struct {
	Id string `json:"id"`
}

type GetPackageDepartureByIdResponseObject interface {
	VisitGetPackageDepartureByIdResponse(ctx *fiber.Ctx) error
}

type GetPackageDepartureById200JSONResponse GetDepartureResponse

func (response GetPackageDepartureById200JSONResponse) VisitGetPackageDepartureByIdResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetPackageDepartureById404JSONResponse CatalogErrorResponse

func (response GetPackageDepartureById404JSONResponse) VisitGetPackageDepartureByIdResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetPackageDepartureById500JSONResponse CatalogErrorResponse

func (response GetPackageDepartureById500JSONResponse) VisitGetPackageDepartureByIdResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetPackageDepartureById502JSONResponse CatalogErrorResponse

func (response GetPackageDepartureById502JSONResponse) VisitGetPackageDepartureByIdResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(502)

	return ctx.JSON(&response)
}

type ListPackagesRequestObject struct {
	Params ListPackagesParams
}

type ListPackagesResponseObject interface {
	VisitListPackagesResponse(ctx *fiber.Ctx) error
}

type ListPackages200JSONResponse ListPackagesResponse

func (response ListPackages200JSONResponse) VisitListPackagesResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListPackages400JSONResponse CatalogErrorResponse

func (response ListPackages400JSONResponse) VisitListPackagesResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type ListPackages500JSONResponse CatalogErrorResponse

func (response ListPackages500JSONResponse) VisitListPackagesResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type ListPackages502JSONResponse CatalogErrorResponse

func (response ListPackages502JSONResponse) VisitListPackagesResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(502)

	return ctx.JSON(&response)
}

type GetPackageByIdRequestObject struct {
	Id string `json:"id"`
}

type GetPackageByIdResponseObject interface {
	VisitGetPackageByIdResponse(ctx *fiber.Ctx) error
}

type GetPackageById200JSONResponse GetPackageResponse

func (response GetPackageById200JSONResponse) VisitGetPackageByIdResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetPackageById404JSONResponse CatalogErrorResponse

func (response GetPackageById404JSONResponse) VisitGetPackageByIdResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type GetPackageById500JSONResponse CatalogErrorResponse

func (response GetPackageById500JSONResponse) VisitGetPackageByIdResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

type GetPackageById502JSONResponse CatalogErrorResponse

func (response GetPackageById502JSONResponse) VisitGetPackageByIdResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(502)

	return ctx.JSON(&response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(ctx *fiber.Ctx) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(ctx *fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type Logout401JSONResponse ErrorResponse

func (response Logout401JSONResponse) VisitLogoutResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type Logout502JSONResponse ErrorResponse

func (response Logout502JSONResponse) VisitLogoutResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(502)

	return ctx.JSON(&response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(ctx *fiber.Ctx) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type Login400JSONResponse ErrorResponse

func (response Login400JSONResponse) VisitLoginResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type Login401JSONResponse ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type Login403JSONResponse ErrorResponse

func (response Login403JSONResponse) VisitLoginResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type Login502JSONResponse ErrorResponse

func (response Login502JSONResponse) VisitLoginResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(502)

	return ctx.JSON(&response)
}

type RefreshSessionRequestObject struct {
	Body *RefreshSessionJSONRequestBody
}

type RefreshSessionResponseObject interface {
	VisitRefreshSessionResponse(ctx *fiber.Ctx) error
}

type RefreshSession200JSONResponse RefreshSessionResponse

func (response RefreshSession200JSONResponse) VisitRefreshSessionResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type RefreshSession400JSONResponse ErrorResponse

func (response RefreshSession400JSONResponse) VisitRefreshSessionResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type RefreshSession401JSONResponse ErrorResponse

func (response RefreshSession401JSONResponse) VisitRefreshSessionResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type RefreshSession403JSONResponse ErrorResponse

func (response RefreshSession403JSONResponse) VisitRefreshSessionResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type RefreshSession502JSONResponse ErrorResponse

func (response RefreshSession502JSONResponse) VisitRefreshSessionResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(502)

	return ctx.JSON(&response)
}

type SuspendUserRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type SuspendUserResponseObject interface {
	VisitSuspendUserResponse(ctx *fiber.Ctx) error
}

type SuspendUser200JSONResponse SuspendUserResponse

func (response SuspendUser200JSONResponse) VisitSuspendUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type SuspendUser400JSONResponse ErrorResponse

func (response SuspendUser400JSONResponse) VisitSuspendUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type SuspendUser401JSONResponse ErrorResponse

func (response SuspendUser401JSONResponse) VisitSuspendUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type SuspendUser403JSONResponse ErrorResponse

func (response SuspendUser403JSONResponse) VisitSuspendUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type SuspendUser404JSONResponse ErrorResponse

func (response SuspendUser404JSONResponse) VisitSuspendUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type SuspendUser502JSONResponse ErrorResponse

func (response SuspendUser502JSONResponse) VisitSuspendUserResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(502)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe
	// (GET /system/live)
	Liveness(ctx context.Context, request LivenessRequestObject) (LivenessResponseObject, error)
	// Readiness probe
	// (GET /system/ready)
	Readiness(ctx context.Context, request ReadinessRequestObject) (ReadinessResponseObject, error)
	// Proxy finance-svc liveness
	// (GET /v1/finance/system/live)
	GetFinanceSystemLive(ctx context.Context, request GetFinanceSystemLiveRequestObject) (GetFinanceSystemLiveResponseObject, error)
	// Current user profile
	// (GET /v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Begin TOTP enrollment — generate a secret + otpauth URL
	// (POST /v1/me/2fa/enroll)
	EnrollTotp(ctx context.Context, request EnrollTotpRequestObject) (EnrollTotpResponseObject, error)
	// Verify TOTP code and mark enrollment complete
	// (POST /v1/me/2fa/verify)
	VerifyTotp(ctx context.Context, request VerifyTotpRequestObject) (VerifyTotpResponseObject, error)
	// Active package-departure detail
	// (GET /v1/package-departures/{id})
	GetPackageDepartureById(ctx context.Context, request GetPackageDepartureByIdRequestObject) (GetPackageDepartureByIdResponseObject, error)
	// List active packages
	// (GET /v1/packages)
	ListPackages(ctx context.Context, request ListPackagesRequestObject) (ListPackagesResponseObject, error)
	// Active package detail
	// (GET /v1/packages/{id})
	GetPackageById(ctx context.Context, request GetPackageByIdRequestObject) (GetPackageByIdResponseObject, error)
	// Logout — revoke the current session row
	// (DELETE /v1/sessions)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Login — exchange credentials for an access + refresh pair
	// (POST /v1/sessions)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Rotate refresh token — issue a new access + refresh pair
	// (POST /v1/sessions/refresh)
	RefreshSession(ctx context.Context, request RefreshSessionRequestObject) (RefreshSessionResponseObject, error)
	// Suspend a user and revoke every active session
	// (POST /v1/users/{id}/suspend)
	SuspendUser(ctx context.Context, request SuspendUserRequestObject) (SuspendUserResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Liveness operation middleware
func (sh *strictHandler) Liveness(ctx *fiber.Ctx) error {
	var request LivenessRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Liveness(ctx.UserContext(), request.(LivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Liveness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LivenessResponseObject); ok {
		if err := validResponse.VisitLivenessResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Readiness operation middleware
func (sh *strictHandler) Readiness(ctx *fiber.Ctx) error {
	var request ReadinessRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Readiness(ctx.UserContext(), request.(ReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Readiness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ReadinessResponseObject); ok {
		if err := validResponse.VisitReadinessResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetFinanceSystemLive operation middleware
func (sh *strictHandler) GetFinanceSystemLive(ctx *fiber.Ctx) error {
	var request GetFinanceSystemLiveRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetFinanceSystemLive(ctx.UserContext(), request.(GetFinanceSystemLiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFinanceSystemLive")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetFinanceSystemLiveResponseObject); ok {
		if err := validResponse.VisitGetFinanceSystemLiveResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx *fiber.Ctx) error {
	var request GetMeRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx.UserContext(), request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// EnrollTotp operation middleware
func (sh *strictHandler) EnrollTotp(ctx *fiber.Ctx) error {
	var request EnrollTotpRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.EnrollTotp(ctx.UserContext(), request.(EnrollTotpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EnrollTotp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(EnrollTotpResponseObject); ok {
		if err := validResponse.VisitEnrollTotpResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// VerifyTotp operation middleware
func (sh *strictHandler) VerifyTotp(ctx *fiber.Ctx) error {
	var request VerifyTotpRequestObject

	var body VerifyTotpJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyTotp(ctx.UserContext(), request.(VerifyTotpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyTotp")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(VerifyTotpResponseObject); ok {
		if err := validResponse.VisitVerifyTotpResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetPackageDepartureById operation middleware
func (sh *strictHandler) GetPackageDepartureById(ctx *fiber.Ctx, id string) error {
	var request GetPackageDepartureByIdRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetPackageDepartureById(ctx.UserContext(), request.(GetPackageDepartureByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPackageDepartureById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetPackageDepartureByIdResponseObject); ok {
		if err := validResponse.VisitGetPackageDepartureByIdResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListPackages operation middleware
func (sh *strictHandler) ListPackages(ctx *fiber.Ctx, params ListPackagesParams) error {
	var request ListPackagesRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListPackages(ctx.UserContext(), request.(ListPackagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPackages")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ListPackagesResponseObject); ok {
		if err := validResponse.VisitListPackagesResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetPackageById operation middleware
func (sh *strictHandler) GetPackageById(ctx *fiber.Ctx, id string) error {
	var request GetPackageByIdRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetPackageById(ctx.UserContext(), request.(GetPackageByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPackageById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetPackageByIdResponseObject); ok {
		if err := validResponse.VisitGetPackageByIdResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *fiber.Ctx) error {
	var request LogoutRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.UserContext(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *fiber.Ctx) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.UserContext(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RefreshSession operation middleware
func (sh *strictHandler) RefreshSession(ctx *fiber.Ctx) error {
	var request RefreshSessionRequestObject

	var body RefreshSessionJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshSession(ctx.UserContext(), request.(RefreshSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(RefreshSessionResponseObject); ok {
		if err := validResponse.VisitRefreshSessionResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SuspendUser operation middleware
func (sh *strictHandler) SuspendUser(ctx *fiber.Ctx, id openapi_types.UUID) error {
	var request SuspendUserRequestObject

	request.Id = id

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.SuspendUser(ctx.UserContext(), request.(SuspendUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SuspendUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(SuspendUserResponseObject); ok {
		if err := validResponse.VisitSuspendUserResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
