// jamaah_ocr_messages.go — hand-written proto message types for OCR RPCs.
//
// NOTE: These types would normally be generated by protoc from jamaah.proto.
// They are written by hand because protoc is not available in the sandbox.
// Run `make genpb` to regenerate cleanly from jamaah.proto once protoc is
// available in the build environment.
//
// TriggerOCR — initiates OCR processing on a passport document.
// GetOCRStatus — retrieves OCR results and confidence score for a document.

package pb

// TriggerOCRRequest carries the document ID to run OCR on.
type TriggerOCRRequest struct {
	DocumentId string // UUID of the document in jamaah.pilgrim_documents
}

func (x *TriggerOCRRequest) GetDocumentId() string {
	if x == nil {
		return ""
	}
	return x.DocumentId
}

// TriggerOCRResponse returns the OCR result and updated document status.
type TriggerOCRResponse struct {
	DocumentId string
	Status     string            // "ocr_complete" or "pending" (manual review if confidence < 0.8)
	Confidence float64
	OcrResult  map[string]string // extracted fields: name, passport_no, dob, nationality, etc.
}

func (x *TriggerOCRResponse) GetDocumentId() string {
	if x == nil {
		return ""
	}
	return x.DocumentId
}
func (x *TriggerOCRResponse) GetStatus() string {
	if x == nil {
		return ""
	}
	return x.Status
}
func (x *TriggerOCRResponse) GetConfidence() float64 {
	if x == nil {
		return 0
	}
	return x.Confidence
}
func (x *TriggerOCRResponse) GetOcrResult() map[string]string {
	if x == nil {
		return nil
	}
	return x.OcrResult
}

// GetOCRStatusRequest carries the document ID to retrieve OCR status for.
type GetOCRStatusRequest struct {
	DocumentId string
}

func (x *GetOCRStatusRequest) GetDocumentId() string {
	if x == nil {
		return ""
	}
	return x.DocumentId
}

// GetOCRStatusResponse returns the current OCR state of a document.
type GetOCRStatusResponse struct {
	DocumentId string
	Status     string
	Confidence float64
	OcrResult  map[string]string
}

func (x *GetOCRStatusResponse) GetDocumentId() string {
	if x == nil {
		return ""
	}
	return x.DocumentId
}
func (x *GetOCRStatusResponse) GetStatus() string {
	if x == nil {
		return ""
	}
	return x.Status
}
func (x *GetOCRStatusResponse) GetConfidence() float64 {
	if x == nil {
		return 0
	}
	return x.Confidence
}
func (x *GetOCRStatusResponse) GetOcrResult() map[string]string {
	if x == nil {
		return nil
	}
	return x.OcrResult
}
