// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	GetDbTxDiagnostic(ctx context.Context, id int64) (Diagnostic, error)
	InsertDbTxDiagnostic(ctx context.Context, arg InsertDbTxDiagnosticParams) (Diagnostic, error)
	ReadyCheck(ctx context.Context) (int32, error)

	// Journal entry queries (S3-E-03 / BL-FIN-001..003)
	GetJournalEntryByIdempotencyKey(ctx context.Context, idempotencyKey string) (JournalEntryRow, error)
	GetJournalEntryByID(ctx context.Context, id string) (JournalEntryRow, error)
	InsertJournalEntry(ctx context.Context, arg InsertJournalEntryParams) (JournalEntryRow, error)
	InsertJournalLine(ctx context.Context, arg InsertJournalLineParams) (JournalLineRow, error)

	// Finance report queries (S5-E-01 / BL-FIN-004..005)
	GetFinanceSummary(ctx context.Context) ([]AccountSummaryRow, error)
	ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]JournalEntryRow, error)
	GetJournalLines(ctx context.Context, entryIDs []string) ([]JournalLineRow, error)

	// Finance depth queries — P&L and Balance Sheet (Wave 1B)
	GetPLReportLines(ctx context.Context, arg GetPLReportLinesParams) ([]PLReportLineRow, error)
	GetBalanceSheetLines(ctx context.Context, arg GetBalanceSheetLinesParams) ([]BalanceSheetLineRow, error)

	// Disbursement batch queries (BL-FIN-010/011)
	InsertDisbursementBatch(ctx context.Context, arg InsertDisbursementBatchParams) (DisbursementBatchRow, error)
	InsertDisbursementItem(ctx context.Context, arg InsertDisbursementItemParams) (DisbursementItemRow, error)
	GetDisbursementBatchByID(ctx context.Context, id string) (DisbursementBatchRow, error)
	GetDisbursementItemsByBatchID(ctx context.Context, batchID string) ([]DisbursementItemRow, error)
	UpdateDisbursementBatchDecision(ctx context.Context, arg UpdateDisbursementBatchDecisionParams) error
	UpdateDisbursementItemJournal(ctx context.Context, journalEntryID string, itemID int64) error
	GetDisbursementAgingBuckets(ctx context.Context, asOfDate time.Time) (AgingBuckets, error)
	GetARAgingBuckets(ctx context.Context, asOfDate time.Time) (AgingBuckets, error)
}

var _ Querier = (*Queries)(nil)
