// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetDbTxDiagnostic(ctx context.Context, id int64) (Diagnostic, error)
	InsertDbTxDiagnostic(ctx context.Context, arg InsertDbTxDiagnosticParams) (Diagnostic, error)
	ReadyCheck(ctx context.Context) (int32, error)

	// Journal entry queries (S3-E-03 / BL-FIN-001..003)
	GetJournalEntryByIdempotencyKey(ctx context.Context, idempotencyKey string) (JournalEntryRow, error)
	InsertJournalEntry(ctx context.Context, arg InsertJournalEntryParams) (JournalEntryRow, error)
	InsertJournalLine(ctx context.Context, arg InsertJournalLineParams) (JournalLineRow, error)

	// Finance report queries (S5-E-01 / BL-FIN-004..005)
	GetFinanceSummary(ctx context.Context) ([]AccountSummaryRow, error)
	ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]JournalEntryRow, error)
	GetJournalLines(ctx context.Context, entryIDs []string) ([]JournalLineRow, error)
}

var _ Querier = (*Queries)(nil)
