// booking_messages.go — hand-written proto message types for the
// S1-E-03 / BL-BOOK-001..006 CreateDraftBooking RPC.
//
// NOTE: needs make genpb — these types would normally be generated by protoc
// into booking.pb.go. They are written by hand here because protoc is not
// available in the current environment. Run `make genpb` to regenerate
// booking.pb.go from booking.proto, then delete this file.
//
// Types follow the same getter-method pattern as protoc-gen-go output so that
// handler code in bookings.go compiles unchanged once regenerated.
package pb

// ---------------------------------------------------------------------------
// PilgrimInput — one jamaah in the booking.
// ---------------------------------------------------------------------------

// PilgrimInput is one jamaah in the CreateDraftBooking request.
type PilgrimInput struct {
	FullName    string
	Email       string
	Whatsapp    string
	Domicile    string
	IsLead      bool
	HasKtp      bool
	HasPassport bool
}

func (x *PilgrimInput) GetFullName() string {
	if x == nil {
		return ""
	}
	return x.FullName
}
func (x *PilgrimInput) GetEmail() string {
	if x == nil {
		return ""
	}
	return x.Email
}
func (x *PilgrimInput) GetWhatsapp() string {
	if x == nil {
		return ""
	}
	return x.Whatsapp
}
func (x *PilgrimInput) GetDomicile() string {
	if x == nil {
		return ""
	}
	return x.Domicile
}
func (x *PilgrimInput) GetIsLead() bool {
	if x == nil {
		return false
	}
	return x.IsLead
}
func (x *PilgrimInput) GetHasKtp() bool {
	if x == nil {
		return false
	}
	return x.HasKtp
}
func (x *PilgrimInput) GetHasPassport() bool {
	if x == nil {
		return false
	}
	return x.HasPassport
}

// ---------------------------------------------------------------------------
// AddonInput — one selected add-on.
// ---------------------------------------------------------------------------

// AddonInput is a selected add-on in the CreateDraftBooking request.
type AddonInput struct {
	AddonId            string
	AddonName          string
	ListAmount         int64
	ListCurrency       string
	SettlementCurrency string
}

func (x *AddonInput) GetAddonId() string {
	if x == nil {
		return ""
	}
	return x.AddonId
}
func (x *AddonInput) GetAddonName() string {
	if x == nil {
		return ""
	}
	return x.AddonName
}
func (x *AddonInput) GetListAmount() int64 {
	if x == nil {
		return 0
	}
	return x.ListAmount
}
func (x *AddonInput) GetListCurrency() string {
	if x == nil {
		return ""
	}
	return x.ListCurrency
}
func (x *AddonInput) GetSettlementCurrency() string {
	if x == nil {
		return ""
	}
	return x.SettlementCurrency
}

// ---------------------------------------------------------------------------
// CreateDraftBookingRequest
// ---------------------------------------------------------------------------

// CreateDraftBookingRequest mirrors the proto message.
type CreateDraftBookingRequest struct {
	Channel       string
	AgentId       string
	StaffUserId   string
	PackageId     string
	DepartureId   string
	RoomType      string
	LeadFullName  string
	LeadEmail     string
	LeadWhatsapp  string
	LeadDomicile  string
	Pilgrims      []*PilgrimInput
	Addons        []*AddonInput
	ListAmount    int64
	ListCurrency  string
	SettlementCurrency string
	Notes         string
	IdempotencyKey string
	MahramWarning string
}

func (x *CreateDraftBookingRequest) GetChannel() string {
	if x == nil {
		return ""
	}
	return x.Channel
}
func (x *CreateDraftBookingRequest) GetAgentId() string {
	if x == nil {
		return ""
	}
	return x.AgentId
}
func (x *CreateDraftBookingRequest) GetStaffUserId() string {
	if x == nil {
		return ""
	}
	return x.StaffUserId
}
func (x *CreateDraftBookingRequest) GetPackageId() string {
	if x == nil {
		return ""
	}
	return x.PackageId
}
func (x *CreateDraftBookingRequest) GetDepartureId() string {
	if x == nil {
		return ""
	}
	return x.DepartureId
}
func (x *CreateDraftBookingRequest) GetRoomType() string {
	if x == nil {
		return ""
	}
	return x.RoomType
}
func (x *CreateDraftBookingRequest) GetLeadFullName() string {
	if x == nil {
		return ""
	}
	return x.LeadFullName
}
func (x *CreateDraftBookingRequest) GetLeadEmail() string {
	if x == nil {
		return ""
	}
	return x.LeadEmail
}
func (x *CreateDraftBookingRequest) GetLeadWhatsapp() string {
	if x == nil {
		return ""
	}
	return x.LeadWhatsapp
}
func (x *CreateDraftBookingRequest) GetLeadDomicile() string {
	if x == nil {
		return ""
	}
	return x.LeadDomicile
}
func (x *CreateDraftBookingRequest) GetPilgrims() []*PilgrimInput {
	if x == nil {
		return nil
	}
	return x.Pilgrims
}
func (x *CreateDraftBookingRequest) GetAddons() []*AddonInput {
	if x == nil {
		return nil
	}
	return x.Addons
}
func (x *CreateDraftBookingRequest) GetListAmount() int64 {
	if x == nil {
		return 0
	}
	return x.ListAmount
}
func (x *CreateDraftBookingRequest) GetListCurrency() string {
	if x == nil {
		return ""
	}
	return x.ListCurrency
}
func (x *CreateDraftBookingRequest) GetSettlementCurrency() string {
	if x == nil {
		return ""
	}
	return x.SettlementCurrency
}
func (x *CreateDraftBookingRequest) GetNotes() string {
	if x == nil {
		return ""
	}
	return x.Notes
}
func (x *CreateDraftBookingRequest) GetIdempotencyKey() string {
	if x == nil {
		return ""
	}
	return x.IdempotencyKey
}
func (x *CreateDraftBookingRequest) GetMahramWarning() string {
	if x == nil {
		return ""
	}
	return x.MahramWarning
}

// ---------------------------------------------------------------------------
// BookingItemResult — one pilgrim in the response.
// ---------------------------------------------------------------------------

// BookingItemResult is one pilgrim in the CreateDraftBookingResponse.
type BookingItemResult struct {
	Id              string
	FullName        string
	IsLead          bool
	DocumentWarning string
}

func (x *BookingItemResult) GetId() string {
	if x == nil {
		return ""
	}
	return x.Id
}
func (x *BookingItemResult) GetFullName() string {
	if x == nil {
		return ""
	}
	return x.FullName
}
func (x *BookingItemResult) GetIsLead() bool {
	if x == nil {
		return false
	}
	return x.IsLead
}
func (x *BookingItemResult) GetDocumentWarning() string {
	if x == nil {
		return ""
	}
	return x.DocumentWarning
}

// ---------------------------------------------------------------------------
// CreateDraftBookingResponse
// ---------------------------------------------------------------------------

// CreateDraftBookingResponse mirrors the proto message.
type CreateDraftBookingResponse struct {
	Id                 string
	Status             string
	Channel            string
	PackageId          string
	DepartureId        string
	RoomType           string
	AgentId            string
	StaffUserId        string
	LeadFullName       string
	LeadEmail          string
	LeadWhatsapp       string
	LeadDomicile       string
	ListAmount         int64
	ListCurrency       string
	SettlementCurrency string
	Notes              string
	IdempotencyKey     string
	CreatedAt          string
	ExpiresAt          string
	Items              []*BookingItemResult
	MahramWarning      string
	Replayed           bool
}

func (x *CreateDraftBookingResponse) GetId() string {
	if x == nil {
		return ""
	}
	return x.Id
}
func (x *CreateDraftBookingResponse) GetStatus() string {
	if x == nil {
		return ""
	}
	return x.Status
}
func (x *CreateDraftBookingResponse) GetChannel() string {
	if x == nil {
		return ""
	}
	return x.Channel
}
func (x *CreateDraftBookingResponse) GetPackageId() string {
	if x == nil {
		return ""
	}
	return x.PackageId
}
func (x *CreateDraftBookingResponse) GetDepartureId() string {
	if x == nil {
		return ""
	}
	return x.DepartureId
}
func (x *CreateDraftBookingResponse) GetRoomType() string {
	if x == nil {
		return ""
	}
	return x.RoomType
}
func (x *CreateDraftBookingResponse) GetAgentId() string {
	if x == nil {
		return ""
	}
	return x.AgentId
}
func (x *CreateDraftBookingResponse) GetStaffUserId() string {
	if x == nil {
		return ""
	}
	return x.StaffUserId
}
func (x *CreateDraftBookingResponse) GetLeadFullName() string {
	if x == nil {
		return ""
	}
	return x.LeadFullName
}
func (x *CreateDraftBookingResponse) GetLeadEmail() string {
	if x == nil {
		return ""
	}
	return x.LeadEmail
}
func (x *CreateDraftBookingResponse) GetLeadWhatsapp() string {
	if x == nil {
		return ""
	}
	return x.LeadWhatsapp
}
func (x *CreateDraftBookingResponse) GetLeadDomicile() string {
	if x == nil {
		return ""
	}
	return x.LeadDomicile
}
func (x *CreateDraftBookingResponse) GetListAmount() int64 {
	if x == nil {
		return 0
	}
	return x.ListAmount
}
func (x *CreateDraftBookingResponse) GetListCurrency() string {
	if x == nil {
		return ""
	}
	return x.ListCurrency
}
func (x *CreateDraftBookingResponse) GetSettlementCurrency() string {
	if x == nil {
		return ""
	}
	return x.SettlementCurrency
}
func (x *CreateDraftBookingResponse) GetNotes() string {
	if x == nil {
		return ""
	}
	return x.Notes
}
func (x *CreateDraftBookingResponse) GetIdempotencyKey() string {
	if x == nil {
		return ""
	}
	return x.IdempotencyKey
}
func (x *CreateDraftBookingResponse) GetCreatedAt() string {
	if x == nil {
		return ""
	}
	return x.CreatedAt
}
func (x *CreateDraftBookingResponse) GetExpiresAt() string {
	if x == nil {
		return ""
	}
	return x.ExpiresAt
}
func (x *CreateDraftBookingResponse) GetItems() []*BookingItemResult {
	if x == nil {
		return nil
	}
	return x.Items
}
func (x *CreateDraftBookingResponse) GetMahramWarning() string {
	if x == nil {
		return ""
	}
	return x.MahramWarning
}
func (x *CreateDraftBookingResponse) GetReplayed() bool {
	if x == nil {
		return false
	}
	return x.Replayed
}
