// mark_booking_paid_messages.go — hand-written proto message types for the
// MarkBookingPaid RPC added in S2-E-02.
//
// NOTE: These types would normally be generated by protoc from booking.proto.
// They are written by hand because protoc is not available in the sandbox.
// Run `make genpb` to regenerate, then delete this file.
//
// MarkBookingPaid is called by payment-svc after a payment event is processed.

package pb

// MarkBookingPaidRequest carries the payment event details from payment-svc.
type MarkBookingPaidRequest struct {
	BookingId     string
	AmountPaidIdr float64
	InvoiceStatus string
	InvoiceId     string
}

func (x *MarkBookingPaidRequest) GetBookingId() string {
	if x == nil {
		return ""
	}
	return x.BookingId
}
func (x *MarkBookingPaidRequest) GetAmountPaidIdr() float64 {
	if x == nil {
		return 0
	}
	return x.AmountPaidIdr
}
func (x *MarkBookingPaidRequest) GetInvoiceStatus() string {
	if x == nil {
		return ""
	}
	return x.InvoiceStatus
}
func (x *MarkBookingPaidRequest) GetInvoiceId() string {
	if x == nil {
		return ""
	}
	return x.InvoiceId
}

// MarkBookingPaidResponse is the booking-svc acknowledgement.
type MarkBookingPaidResponse struct {
	BookingId string
	NewStatus string
}

func (x *MarkBookingPaidResponse) GetBookingId() string {
	if x == nil {
		return ""
	}
	return x.BookingId
}
func (x *MarkBookingPaidResponse) GetNewStatus() string {
	if x == nil {
		return ""
	}
	return x.NewStatus
}
