// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: ops.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpsService_Ping_FullMethodName = "/pb.OpsService/Ping"
)

// OpsServiceClient is the client API for OpsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OpsService — internal gRPC surface for the ops domain.
//
// Current scope is the scaffold Ping (proves the gateway's
// RequireBearerToken + RequirePermission middleware chain reaches this
// backend over gRPC). Container-level liveness is served by the standard
// grpc.health.v1.Health protocol (BL-MON-001). Real RPCs land with the
// ops feature slice.
type OpsServiceClient interface {
	// Ping — scaffold RPC used by the gateway's permission-gate smoke tests.
	// Identity-agnostic per ADR 0009: the gateway validates the bearer and the
	// permission tuple upstream; this handler returns a trivial
	// {message: "ok"} proving the gateway→backend hop works.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type opsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpsServiceClient(cc grpc.ClientConnInterface) OpsServiceClient {
	return &opsServiceClient{cc}
}

func (c *opsServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, OpsService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpsServiceServer is the server API for OpsService service.
// All implementations must embed UnimplementedOpsServiceServer
// for forward compatibility.
//
// OpsService — internal gRPC surface for the ops domain.
//
// Current scope is the scaffold Ping (proves the gateway's
// RequireBearerToken + RequirePermission middleware chain reaches this
// backend over gRPC). Container-level liveness is served by the standard
// grpc.health.v1.Health protocol (BL-MON-001). Real RPCs land with the
// ops feature slice.
type OpsServiceServer interface {
	// Ping — scaffold RPC used by the gateway's permission-gate smoke tests.
	// Identity-agnostic per ADR 0009: the gateway validates the bearer and the
	// permission tuple upstream; this handler returns a trivial
	// {message: "ok"} proving the gateway→backend hop works.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedOpsServiceServer()
}

// UnimplementedOpsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpsServiceServer struct{}

func (UnimplementedOpsServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOpsServiceServer) mustEmbedUnimplementedOpsServiceServer() {}
func (UnimplementedOpsServiceServer) testEmbeddedByValue()                    {}

// UnsafeOpsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpsServiceServer will
// result in compilation errors.
type UnsafeOpsServiceServer interface {
	mustEmbedUnimplementedOpsServiceServer()
}

func RegisterOpsServiceServer(s grpc.ServiceRegistrar, srv OpsServiceServer) {
	// If the following call pancis, it indicates UnimplementedOpsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpsService_ServiceDesc, srv)
}

func _OpsService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpsServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpsService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpsServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpsService_ServiceDesc is the grpc.ServiceDesc for OpsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OpsService",
	HandlerType: (*OpsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _OpsService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ops.proto",
}
