import { redirect } from '@sveltejs/kit';
import type { Cookies, RequestEvent } from '@sveltejs/kit';
import type { CSUser, Lead, LeadList, PackageOption } from '$lib/features/s4-crm/types';

// $types is generated by svelte-kit sync; fall back to RequestEvent when not yet generated
type LoadEvent = { cookies: Cookies; fetch: RequestEvent['fetch'] };

// Server-side: VITE_* vars are NOT available in +page.server.ts (only in client code).
// Use MOCK_CRM and GATEWAY_URL as server-side env vars; fall back to VITE_ variants
// for local dev parity when running via `vite dev` (which injects VITE_ into Node).
const MOCK = process.env.MOCK_CRM === 'true' || process.env.VITE_MOCK_CRM === 'true';
const baseUrl =
  process.env.GATEWAY_URL ?? process.env.VITE_GATEWAY_URL ?? 'http://localhost:4000';

async function loadMockData(): Promise<{
  leads: Lead[];
  total: number;
  csUsers: CSUser[];
  packages: PackageOption[];
}> {
  const { listLeadsMock, listCsUsersMock, listPackagesMock } = await import(
    '$lib/features/s4-crm/mock'
  );
  const [leadsResult, csUsers, packages] = await Promise.all([
    listLeadsMock({}),
    listCsUsersMock(),
    listPackagesMock()
  ]);
  return { leads: leadsResult.leads, total: leadsResult.total, csUsers, packages };
}

export const load = async ({ cookies, fetch }: LoadEvent) => {
  const accessToken = cookies.get('umrohos_access_token');
  if (!accessToken) {
    throw redirect(303, '/console/login');
  }

  if (MOCK) {
    const data = await loadMockData();
    return { ...data, error: null };
  }

  try {
    const [leadsRes, csRes, packagesRes] = await Promise.all([
      fetch(`${baseUrl}/v1/leads`, {
        headers: { Authorization: `Bearer ${accessToken}` }
      }),
      fetch(`${baseUrl}/v1/cs-users`, {
        headers: { Authorization: `Bearer ${accessToken}` }
      }),
      fetch(`${baseUrl}/v1/packages`, {
        headers: { Authorization: `Bearer ${accessToken}` }
      })
    ]);

    const leadsBody = leadsRes.ok
      ? ((await leadsRes.json()) as LeadList)
      : { leads: [], total: 0 };

    const csBody = csRes.ok ? ((await csRes.json()) as CSUser[]) : [];

    const packagesBody = packagesRes.ok
      ? ((await packagesRes.json()) as { packages: PackageOption[] })
      : { packages: [] };

    return {
      leads: leadsBody.leads ?? [],
      total: leadsBody.total ?? 0,
      csUsers: Array.isArray(csBody) ? csBody : [],
      packages: packagesBody.packages ?? [],
      error: leadsRes.ok ? null : `Gagal memuat data leads (${leadsRes.status})`
    };
  } catch {
    return {
      leads: [],
      total: 0,
      csUsers: [],
      packages: [],
      error: 'Tidak dapat terhubung ke gateway.'
    };
  }
};
