// payment_messages.go — hand-written proto message types for payment-svc S2-E-02.
//
// NOTE: These types would normally be generated by protoc from payment.proto.
// They are written by hand here because protoc is not available in the sandbox.
// Run `make genpb` to regenerate from payment.proto, then delete this file.
//
// Types follow the same getter-method pattern as protoc-gen-go output so that
// handler code compiles unchanged once the real generated file exists.
//
// RPCs added:
//   IssueVirtualAccount  — booking-svc calls this during submit saga
//   ProcessWebhook       — internal gRPC path for webhook ingestion
//   StartRefund          — booking-svc calls this during cancel saga

package pb

// ---------------------------------------------------------------------------
// IssueVirtualAccount
// ---------------------------------------------------------------------------

// IssueVirtualAccountRequest is sent by booking-svc (or CS console) to create
// an invoice + VA for a booking.
type IssueVirtualAccountRequest struct {
	BookingId             string
	AmountTotal           float64
	RoundingAdjustmentIdr float64
	// FxSnapshotJson is the JSON-encoded FX rates map at issuance time.
	FxSnapshotJson string
	// GatewayPref selects the gateway ("midtrans"|"xendit"|"mock"); empty = primary.
	GatewayPref string
	// BankCode is the preferred VA bank; empty = gateway default.
	BankCode    string
	ActorUserId string
}

func (x *IssueVirtualAccountRequest) GetBookingId() string {
	if x == nil {
		return ""
	}
	return x.BookingId
}
func (x *IssueVirtualAccountRequest) GetAmountTotal() float64 {
	if x == nil {
		return 0
	}
	return x.AmountTotal
}
func (x *IssueVirtualAccountRequest) GetRoundingAdjustmentIdr() float64 {
	if x == nil {
		return 0
	}
	return x.RoundingAdjustmentIdr
}
func (x *IssueVirtualAccountRequest) GetFxSnapshotJson() string {
	if x == nil {
		return ""
	}
	return x.FxSnapshotJson
}
func (x *IssueVirtualAccountRequest) GetGatewayPref() string {
	if x == nil {
		return ""
	}
	return x.GatewayPref
}
func (x *IssueVirtualAccountRequest) GetBankCode() string {
	if x == nil {
		return ""
	}
	return x.BankCode
}
func (x *IssueVirtualAccountRequest) GetActorUserId() string {
	if x == nil {
		return ""
	}
	return x.ActorUserId
}

// IssueVirtualAccountResponse carries the issued VA details.
type IssueVirtualAccountResponse struct {
	InvoiceId     string
	BookingId     string
	AccountNumber string
	BankCode      string
	AmountTotal   float64
	ExpiresAt     string // RFC3339
	Gateway       string
	Replayed      bool
}

func (x *IssueVirtualAccountResponse) GetInvoiceId() string {
	if x == nil {
		return ""
	}
	return x.InvoiceId
}
func (x *IssueVirtualAccountResponse) GetBookingId() string {
	if x == nil {
		return ""
	}
	return x.BookingId
}
func (x *IssueVirtualAccountResponse) GetAccountNumber() string {
	if x == nil {
		return ""
	}
	return x.AccountNumber
}
func (x *IssueVirtualAccountResponse) GetBankCode() string {
	if x == nil {
		return ""
	}
	return x.BankCode
}
func (x *IssueVirtualAccountResponse) GetAmountTotal() float64 {
	if x == nil {
		return 0
	}
	return x.AmountTotal
}
func (x *IssueVirtualAccountResponse) GetExpiresAt() string {
	if x == nil {
		return ""
	}
	return x.ExpiresAt
}
func (x *IssueVirtualAccountResponse) GetGateway() string {
	if x == nil {
		return ""
	}
	return x.Gateway
}
func (x *IssueVirtualAccountResponse) GetReplayed() bool {
	if x == nil {
		return false
	}
	return x.Replayed
}

// ---------------------------------------------------------------------------
// ProcessWebhook
// ---------------------------------------------------------------------------

// ProcessWebhookRequest carries a raw webhook payload from a gateway.
type ProcessWebhookRequest struct {
	// Gateway identifies the source ("midtrans"|"xendit"|"mock").
	Gateway string
	// Payload is the raw HTTP request body bytes.
	Payload []byte
	// Signature is the gateway HMAC header value (e.g. X-Signature-512 for Midtrans).
	Signature string
}

func (x *ProcessWebhookRequest) GetGateway() string {
	if x == nil {
		return ""
	}
	return x.Gateway
}
func (x *ProcessWebhookRequest) GetPayload() []byte {
	if x == nil {
		return nil
	}
	return x.Payload
}
func (x *ProcessWebhookRequest) GetSignature() string {
	if x == nil {
		return ""
	}
	return x.Signature
}

// ProcessWebhookResponse is returned after webhook processing.
type ProcessWebhookResponse struct {
	Replayed  bool
	InvoiceId string
	NewStatus string
}

func (x *ProcessWebhookResponse) GetReplayed() bool {
	if x == nil {
		return false
	}
	return x.Replayed
}
func (x *ProcessWebhookResponse) GetInvoiceId() string {
	if x == nil {
		return ""
	}
	return x.InvoiceId
}
func (x *ProcessWebhookResponse) GetNewStatus() string {
	if x == nil {
		return ""
	}
	return x.NewStatus
}

// ---------------------------------------------------------------------------
// StartRefund
// ---------------------------------------------------------------------------

// StartRefundRequest initiates a refund for a booking.
type StartRefundRequest struct {
	BookingId   string
	ReasonCode  string
	ActorUserId string
}

func (x *StartRefundRequest) GetBookingId() string {
	if x == nil {
		return ""
	}
	return x.BookingId
}
func (x *StartRefundRequest) GetReasonCode() string {
	if x == nil {
		return ""
	}
	return x.ReasonCode
}
func (x *StartRefundRequest) GetActorUserId() string {
	if x == nil {
		return ""
	}
	return x.ActorUserId
}

// StartRefundResponse is returned after the refund record is created.
type StartRefundResponse struct {
	RefundId  string
	InvoiceId string
	AmountIdr float64
	Status    string
}

func (x *StartRefundResponse) GetRefundId() string {
	if x == nil {
		return ""
	}
	return x.RefundId
}
func (x *StartRefundResponse) GetInvoiceId() string {
	if x == nil {
		return ""
	}
	return x.InvoiceId
}
func (x *StartRefundResponse) GetAmountIdr() float64 {
	if x == nil {
		return 0
	}
	return x.AmountIdr
}
func (x *StartRefundResponse) GetStatus() string {
	if x == nil {
		return ""
	}
	return x.Status
}
