-- S1-E-03 / BL-BOOK-001..006 — booking-svc draft creation queries.
--
-- All booking data lives in the `booking` schema (created in migration 000011).
-- IDs use ULID+prefix (bkg_, bkgitem_) generated by the service layer.
-- The service layer ensures only status='draft' is ever persisted in S1.

-- name: InsertBooking :one
-- Create a new draft booking row. status is always 'draft' in S1.
INSERT INTO booking.bookings (
    id,
    status,
    channel,
    package_id,
    departure_id,
    room_type,
    agent_id,
    staff_user_id,
    lead_full_name,
    lead_email,
    lead_whatsapp,
    lead_domicile,
    list_amount,
    list_currency,
    settlement_currency,
    notes,
    idempotency_key,
    idempotency_body_hash,
    expires_at
) VALUES (
    $1,
    'draft'::booking.status,
    $2::booking.channel,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18
)
RETURNING
    id, status, channel,
    package_id, departure_id, room_type,
    agent_id, staff_user_id,
    lead_full_name, lead_email, lead_whatsapp, lead_domicile,
    list_amount, list_currency, settlement_currency,
    notes, idempotency_key, idempotency_body_hash,
    created_at, updated_at, expires_at;

-- name: InsertBookingItem :one
-- Create a booking item (jamaah entry) for a booking.
INSERT INTO booking.booking_items (
    id,
    booking_id,
    full_name,
    email,
    whatsapp,
    domicile,
    is_lead,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    'active'::booking.item_status
)
RETURNING
    id, booking_id, full_name, email, whatsapp, domicile, is_lead, status, created_at, updated_at;

-- name: InsertBookingAddon :exec
-- Link an add-on (snapshotted) to a booking.
INSERT INTO booking.booking_addons (
    booking_id,
    addon_id,
    addon_name,
    list_amount,
    list_currency,
    settlement_currency
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (booking_id, addon_id) DO NOTHING;

-- name: GetBookingByID :one
-- Fetch a booking by ID. Returns only 'draft' status rows in S1 (see
-- S1 § Booking States: non-draft rows return 404 to S1 read paths).
SELECT
    id, status, channel,
    package_id, departure_id, room_type,
    agent_id, staff_user_id,
    lead_full_name, lead_email, lead_whatsapp, lead_domicile,
    list_amount, list_currency, settlement_currency,
    notes, idempotency_key,
    created_at, updated_at, expires_at
FROM booking.bookings
WHERE id = $1
  AND status = 'draft';

-- name: ListBookingItems :many
SELECT
    id, booking_id, full_name, email, whatsapp, domicile, is_lead, status, created_at, updated_at
FROM booking.booking_items
WHERE booking_id = $1
ORDER BY is_lead DESC, created_at ASC;

-- name: ListBookingAddons :many
SELECT
    booking_id, addon_id, addon_name, list_amount, list_currency, settlement_currency
FROM booking.booking_addons
WHERE booking_id = $1;

-- name: GetBookingByIdempotencyKey :one
-- Used for idempotency dedup: find an existing booking by (channel, key).
SELECT
    id, status, channel,
    package_id, departure_id, room_type,
    agent_id, staff_user_id,
    lead_full_name, lead_email, lead_whatsapp, lead_domicile,
    list_amount, list_currency, settlement_currency,
    notes, idempotency_key, idempotency_body_hash,
    created_at, updated_at, expires_at
FROM booking.bookings
WHERE channel = $1::booking.channel
  AND idempotency_key = $2;
