// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//
// NOTE: bookings-related methods (InsertBooking, InsertBookingItem,
// InsertBookingAddon, GetBookingByID, ListBookingItems, ListBookingAddons,
// GetBookingByIdempotencyKey) are hand-authored in bookings.sql.go until
// `make generate` can be run against the booking schema.

package sqlc

import (
	"context"
)

type Querier interface {
	GetDbTxDiagnostic(ctx context.Context, id int64) (Diagnostic, error)
	InsertDbTxDiagnostic(ctx context.Context, arg InsertDbTxDiagnosticParams) (Diagnostic, error)
	ReadyCheck(ctx context.Context) (int32, error)

	// Booking draft queries (S1-E-03 / BL-BOOK-001..006)
	InsertBooking(ctx context.Context, arg InsertBookingParams) (BookingRow, error)
	InsertBookingItem(ctx context.Context, arg InsertBookingItemParams) (BookingItemRow, error)
	InsertBookingAddon(ctx context.Context, arg InsertBookingAddonParams) error
	GetBookingByID(ctx context.Context, id string) (BookingRow, error)
	ListBookingItems(ctx context.Context, bookingID string) ([]BookingItemRow, error)
	ListBookingAddons(ctx context.Context, bookingID string) ([]BookingAddonRow, error)
	GetBookingByIdempotencyKey(ctx context.Context, arg GetBookingByIdempotencyKeyParams) (BookingRow, error)
}

var _ Querier = (*Queries)(nil)
