[SERVICE]
    Flush         1
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
    Name          forward
    Listen        0.0.0.0
    Port          24224

[FILTER]
    Name          parser
    Match         *
    Key_Name      log
    Parser        json
    Reserve_Data  Off

[OUTPUT]
    Name          loki
    Match         demo-svc
    Host          loki
    Port          3100
    Labels        job=demo-svc, container=demo-svc
    Line_Format   json

[OUTPUT]
    Name          loki
    Match         demo-grpc-svc
    Host          loki
    Port          3100
    Labels        job=demo-grpc-svc, container=demo-grpc-svc
    Line_Format   json

[OUTPUT]
    Name          loki
    Match         broker-svc
    Host          loki
    Port          3100
    Labels        job=broker-svc, container=broker-svc
    Line_Format   json
