// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: packages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActivePackageByID = `-- name: GetActivePackageByID :one
SELECT
    id,
    kind,
    name,
    description,
    highlights,
    cover_photo_url,
    itinerary_id,
    airline_id,
    muthawwif_id,
    status,
    created_at,
    updated_at
FROM catalog.packages
WHERE id = $1
  AND status = 'active'
  AND deleted_at IS NULL
`

type GetActivePackageByIDRow struct {
	ID            string               `json:"id"`
	Kind          CatalogPackageKind   `json:"kind"`
	Name          string               `json:"name"`
	Description   string               `json:"description"`
	Highlights    []string             `json:"highlights"`
	CoverPhotoUrl string               `json:"cover_photo_url"`
	ItineraryID   pgtype.Text          `json:"itinerary_id"`
	AirlineID     pgtype.Text          `json:"airline_id"`
	MuthawwifID   pgtype.Text          `json:"muthawwif_id"`
	Status        CatalogPackageStatus `json:"status"`
	CreatedAt     pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz   `json:"updated_at"`
}

func (q *Queries) GetActivePackageByID(ctx context.Context, id string) (GetActivePackageByIDRow, error) {
	row := q.db.QueryRow(ctx, getActivePackageByID, id)
	var i GetActivePackageByIDRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Description,
		&i.Highlights,
		&i.CoverPhotoUrl,
		&i.ItineraryID,
		&i.AirlineID,
		&i.MuthawwifID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAirlineByID = `-- name: GetAirlineByID :one
SELECT id, code, name, operator_kind, created_at, updated_at
FROM catalog.airlines
WHERE id = $1
`

func (q *Queries) GetAirlineByID(ctx context.Context, id string) (CatalogAirline, error) {
	row := q.db.QueryRow(ctx, getAirlineByID, id)
	var i CatalogAirline
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.OperatorKind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItineraryByID = `-- name: GetItineraryByID :one
SELECT id, name, days, public_url, created_at, updated_at
FROM catalog.itinerary_templates
WHERE id = $1
`

func (q *Queries) GetItineraryByID(ctx context.Context, id string) (CatalogItineraryTemplate, error) {
	row := q.db.QueryRow(ctx, getItineraryByID, id)
	var i CatalogItineraryTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Days,
		&i.PublicUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMuthawwifByID = `-- name: GetMuthawwifByID :one
SELECT id, name, portrait_url, created_at, updated_at
FROM catalog.muthawwif
WHERE id = $1
`

func (q *Queries) GetMuthawwifByID(ctx context.Context, id string) (CatalogMuthawwif, error) {
	row := q.db.QueryRow(ctx, getMuthawwifByID, id)
	var i CatalogMuthawwif
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PortraitUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextDepartureForPackage = `-- name: GetNextDepartureForPackage :one
SELECT
    id,
    departure_date,
    return_date,
    total_seats,
    reserved_seats,
    (total_seats - reserved_seats)::integer AS remaining_seats
FROM catalog.package_departures
WHERE package_id = $1
  AND status IN ('open', 'closed')
  AND departure_date >= CURRENT_DATE
ORDER BY departure_date ASC
LIMIT 1
`

type GetNextDepartureForPackageRow struct {
	ID             string      `json:"id"`
	DepartureDate  pgtype.Date `json:"departure_date"`
	ReturnDate     pgtype.Date `json:"return_date"`
	TotalSeats     int32       `json:"total_seats"`
	ReservedSeats  int32       `json:"reserved_seats"`
	RemainingSeats int32       `json:"remaining_seats"`
}

// Returns pgx.ErrNoRows when the package has no upcoming open/closed
// departure. Service layer treats that as "no next_departure" and
// emits `null` on the wire.
func (q *Queries) GetNextDepartureForPackage(ctx context.Context, packageID string) (GetNextDepartureForPackageRow, error) {
	row := q.db.QueryRow(ctx, getNextDepartureForPackage, packageID)
	var i GetNextDepartureForPackageRow
	err := row.Scan(
		&i.ID,
		&i.DepartureDate,
		&i.ReturnDate,
		&i.TotalSeats,
		&i.ReservedSeats,
		&i.RemainingSeats,
	)
	return i, err
}

const getStartingPriceForPackage = `-- name: GetStartingPriceForPackage :one
SELECT
    pr.list_amount::bigint AS list_amount,
    pr.list_currency,
    pr.settlement_currency
FROM catalog.package_pricing pr
JOIN catalog.package_departures d ON d.id = pr.package_departure_id
WHERE d.package_id = $1
  AND d.status IN ('open', 'closed')
  AND d.departure_date >= CURRENT_DATE
ORDER BY pr.list_amount ASC
LIMIT 1
`

type GetStartingPriceForPackageRow struct {
	ListAmount         int64  `json:"list_amount"`
	ListCurrency       string `json:"list_currency"`
	SettlementCurrency string `json:"settlement_currency"`
}

// Returns the lowest priced room type across the package's upcoming
// open/closed departures. Returns pgx.ErrNoRows if the package has
// no priced upcoming departure (unusual for an active package).
//
// `list_amount` is cast to BIGINT for wire conformance (whole currency
// units per § Catalog). MVP single-currency (Q001) means no sub-unit
// loss; multi-currency handling revisits this when it lands.
func (q *Queries) GetStartingPriceForPackage(ctx context.Context, packageID string) (GetStartingPriceForPackageRow, error) {
	row := q.db.QueryRow(ctx, getStartingPriceForPackage, packageID)
	var i GetStartingPriceForPackageRow
	err := row.Scan(&i.ListAmount, &i.ListCurrency, &i.SettlementCurrency)
	return i, err
}

const listActivePackages = `-- name: ListActivePackages :many

SELECT
    p.id,
    p.kind,
    p.name,
    p.description,
    p.cover_photo_url
FROM catalog.packages p
WHERE p.status = 'active'
  AND p.deleted_at IS NULL
  AND ($1::catalog.package_kind IS NULL OR p.kind = $1::catalog.package_kind)
  AND ($2::text IS NULL OR EXISTS (
        SELECT 1 FROM catalog.airlines a
        WHERE a.id = p.airline_id AND a.code = $2::text
  ))
  AND ($3::text IS NULL OR EXISTS (
        SELECT 1 FROM catalog.package_hotels ph
        WHERE ph.package_id = p.id AND ph.hotel_id = $3::text
  ))
  AND (
        $4::date IS NULL
        AND $5::date IS NULL
        OR EXISTS (
            SELECT 1 FROM catalog.package_departures d
            WHERE d.package_id = p.id
              AND d.status IN ('open', 'closed')
              AND ($4::date IS NULL OR d.departure_date >= $4::date)
              AND ($5::date IS NULL OR d.departure_date <= $5::date)
        )
  )
  AND ($6::text IS NULL OR p.id > $6::text)
ORDER BY p.id ASC
LIMIT $7::integer
`

type ListActivePackagesParams struct {
	Kind          NullCatalogPackageKind `json:"kind"`
	AirlineCode   pgtype.Text            `json:"airline_code"`
	HotelID       pgtype.Text            `json:"hotel_id"`
	DepartureFrom pgtype.Date            `json:"departure_from"`
	DepartureTo   pgtype.Date            `json:"departure_to"`
	CursorID      pgtype.Text            `json:"cursor_id"`
	RowLimit      int32                  `json:"row_limit"`
}

type ListActivePackagesRow struct {
	ID            string             `json:"id"`
	Kind          CatalogPackageKind `json:"kind"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	CoverPhotoUrl string             `json:"cover_photo_url"`
}

// S1-E-02 / BL-CAT-001 — package read queries.
//
// All queries are read-only. Only `status = 'active'` rows are returned
// by every query; draft/archived packages must never leak through these
// endpoints per `slice-S1.md § Catalog`.
//
// The list page is built by three queries: `ListActivePackages` returns
// the base package rows (filtered + cursor-paginated), and for each row
// the service layer fetches `GetStartingPriceForPackage` and
// `GetNextDepartureForPackage` to hydrate `starting_price` and
// `next_departure`. A package with no upcoming open/closed departure
// returns `pgx.ErrNoRows` from the latter two — the handler emits
// `next_departure: null` and `starting_price: {0, IDR, IDR}` (an
// intentional "no priced departure" signal for the UI).
//
// Cursor pagination keys off `packages.id` ULID (time-sortable), so
// `WHERE id > $cursor ORDER BY id` yields a stable chronological page
// across the active set.
// Filters are all optional; pass NULL / empty string to skip a filter.
// Caller fetches `row_limit+1` rows; the extra row signals
// `has_more=true` and is dropped before shaping the response.
func (q *Queries) ListActivePackages(ctx context.Context, arg ListActivePackagesParams) ([]ListActivePackagesRow, error) {
	rows, err := q.db.Query(ctx, listActivePackages,
		arg.Kind,
		arg.AirlineCode,
		arg.HotelID,
		arg.DepartureFrom,
		arg.DepartureTo,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePackagesRow{}
	for rows.Next() {
		var i ListActivePackagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Description,
			&i.CoverPhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAddonsForPackage = `-- name: ListAddonsForPackage :many
SELECT
    a.id,
    a.name,
    a.list_amount::bigint AS list_amount,
    a.list_currency,
    a.settlement_currency
FROM catalog.addons a
JOIN catalog.package_addons pa ON pa.addon_id = a.id
WHERE pa.package_id = $1
ORDER BY a.name ASC
`

type ListAddonsForPackageRow struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	ListAmount         int64  `json:"list_amount"`
	ListCurrency       string `json:"list_currency"`
	SettlementCurrency string `json:"settlement_currency"`
}

func (q *Queries) ListAddonsForPackage(ctx context.Context, packageID string) ([]ListAddonsForPackageRow, error) {
	rows, err := q.db.Query(ctx, listAddonsForPackage, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAddonsForPackageRow{}
	for rows.Next() {
		var i ListAddonsForPackageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ListAmount,
			&i.ListCurrency,
			&i.SettlementCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotelsForPackage = `-- name: ListHotelsForPackage :many
SELECT h.id, h.name, h.city, h.star_rating, h.walking_distance_m
FROM catalog.hotels h
JOIN catalog.package_hotels ph ON ph.hotel_id = h.id
WHERE ph.package_id = $1
ORDER BY ph.sort_order ASC, h.name ASC
`

type ListHotelsForPackageRow struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	City             string `json:"city"`
	StarRating       int16  `json:"star_rating"`
	WalkingDistanceM int32  `json:"walking_distance_m"`
}

func (q *Queries) ListHotelsForPackage(ctx context.Context, packageID string) ([]ListHotelsForPackageRow, error) {
	rows, err := q.db.Query(ctx, listHotelsForPackage, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHotelsForPackageRow{}
	for rows.Next() {
		var i ListHotelsForPackageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.StarRating,
			&i.WalkingDistanceM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenDeparturesForPackage = `-- name: ListOpenDeparturesForPackage :many
SELECT
    id,
    package_id,
    departure_date,
    return_date,
    total_seats,
    reserved_seats,
    (total_seats - reserved_seats)::integer AS remaining_seats,
    status
FROM catalog.package_departures
WHERE package_id = $1
  AND status IN ('open', 'closed')
  AND departure_date >= CURRENT_DATE
ORDER BY departure_date ASC
`

type ListOpenDeparturesForPackageRow struct {
	ID             string                 `json:"id"`
	PackageID      string                 `json:"package_id"`
	DepartureDate  pgtype.Date            `json:"departure_date"`
	ReturnDate     pgtype.Date            `json:"return_date"`
	TotalSeats     int32                  `json:"total_seats"`
	ReservedSeats  int32                  `json:"reserved_seats"`
	RemainingSeats int32                  `json:"remaining_seats"`
	Status         CatalogDepartureStatus `json:"status"`
}

// Public-readable departures: open/closed only, upcoming only.
func (q *Queries) ListOpenDeparturesForPackage(ctx context.Context, packageID string) ([]ListOpenDeparturesForPackageRow, error) {
	rows, err := q.db.Query(ctx, listOpenDeparturesForPackage, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenDeparturesForPackageRow{}
	for rows.Next() {
		var i ListOpenDeparturesForPackageRow
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.DepartureDate,
			&i.ReturnDate,
			&i.TotalSeats,
			&i.ReservedSeats,
			&i.RemainingSeats,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
