// Package pb — hand-written proto message types and gRPC client for
// BookingService (S1-E-03 / BL-BOOK-001..006).
//
// NOTE: needs make genpb — these types would normally be generated by protoc
// into booking.pb.go and booking_grpc.pb.go. They are written by hand here
// because protoc is not available in the current environment. Run `make genpb`
// to regenerate from booking.proto, then delete this file.
//
// Types follow the same getter-method pattern as protoc-gen-go output.
package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ---------------------------------------------------------------------------
// gRPC method paths
// ---------------------------------------------------------------------------

const (
	BookingService_Healthz_FullMethodName            = "/pb.BookingService/Healthz"
	BookingService_CreateDraftBooking_FullMethodName = "/pb.BookingService/CreateDraftBooking"
	BookingService_SubmitBooking_FullMethodName      = "/pb.BookingService/SubmitBooking"
)

// ---------------------------------------------------------------------------
// BookingServiceClient interface + implementation
// ---------------------------------------------------------------------------

// BookingServiceClient is the client API for BookingService.
type BookingServiceClient interface {
	Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzResponse, error)
	CreateDraftBooking(ctx context.Context, in *CreateDraftBookingRequest, opts ...grpc.CallOption) (*CreateDraftBookingResponse, error)
	SubmitBooking(ctx context.Context, in *SubmitBookingRequest, opts ...grpc.CallOption) (*SubmitBookingResponse, error)
}

type bookingServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewBookingServiceClient returns a BookingServiceClient backed by the given conn.
func NewBookingServiceClient(cc grpc.ClientConnInterface) BookingServiceClient {
	return &bookingServiceClient{cc}
}

func (c *bookingServiceClient) Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, BookingService_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) CreateDraftBooking(ctx context.Context, in *CreateDraftBookingRequest, opts ...grpc.CallOption) (*CreateDraftBookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDraftBookingResponse)
	err := c.cc.Invoke(ctx, BookingService_CreateDraftBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) SubmitBooking(ctx context.Context, in *SubmitBookingRequest, opts ...grpc.CallOption) (*SubmitBookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitBookingResponse)
	err := c.cc.Invoke(ctx, BookingService_SubmitBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ---------------------------------------------------------------------------
// Healthz messages (minimal stub)
// ---------------------------------------------------------------------------

// HealthzRequest is the Healthz request message.
type HealthzRequest struct{}

func (x *HealthzRequest) Reset()         {}
func (x *HealthzRequest) String() string { return "" }
func (x *HealthzRequest) ProtoMessage()  {}

// HealthzResponse is the Healthz response message.
type HealthzResponse struct {
	Ok bool
}

func (x *HealthzResponse) Reset()         {}
func (x *HealthzResponse) String() string { return "" }
func (x *HealthzResponse) ProtoMessage()  {}
func (x *HealthzResponse) GetOk() bool {
	if x == nil {
		return false
	}
	return x.Ok
}

// ---------------------------------------------------------------------------
// PilgrimInput
// ---------------------------------------------------------------------------

// PilgrimInput is one jamaah in the CreateDraftBooking request.
type PilgrimInput struct {
	FullName    string
	Email       string
	Whatsapp    string
	Domicile    string
	IsLead      bool
	HasKtp      bool
	HasPassport bool
}

func (x *PilgrimInput) Reset()         {}
func (x *PilgrimInput) String() string { return "" }
func (x *PilgrimInput) ProtoMessage()  {}

func (x *PilgrimInput) GetFullName() string {
	if x == nil {
		return ""
	}
	return x.FullName
}
func (x *PilgrimInput) GetEmail() string {
	if x == nil {
		return ""
	}
	return x.Email
}
func (x *PilgrimInput) GetWhatsapp() string {
	if x == nil {
		return ""
	}
	return x.Whatsapp
}
func (x *PilgrimInput) GetDomicile() string {
	if x == nil {
		return ""
	}
	return x.Domicile
}
func (x *PilgrimInput) GetIsLead() bool {
	if x == nil {
		return false
	}
	return x.IsLead
}
func (x *PilgrimInput) GetHasKtp() bool {
	if x == nil {
		return false
	}
	return x.HasKtp
}
func (x *PilgrimInput) GetHasPassport() bool {
	if x == nil {
		return false
	}
	return x.HasPassport
}

// ---------------------------------------------------------------------------
// AddonInput
// ---------------------------------------------------------------------------

// AddonInput is a selected add-on in the CreateDraftBooking request.
type AddonInput struct {
	AddonId            string
	AddonName          string
	ListAmount         int64
	ListCurrency       string
	SettlementCurrency string
}

func (x *AddonInput) Reset()         {}
func (x *AddonInput) String() string { return "" }
func (x *AddonInput) ProtoMessage()  {}

func (x *AddonInput) GetAddonId() string {
	if x == nil {
		return ""
	}
	return x.AddonId
}
func (x *AddonInput) GetAddonName() string {
	if x == nil {
		return ""
	}
	return x.AddonName
}
func (x *AddonInput) GetListAmount() int64 {
	if x == nil {
		return 0
	}
	return x.ListAmount
}
func (x *AddonInput) GetListCurrency() string {
	if x == nil {
		return ""
	}
	return x.ListCurrency
}
func (x *AddonInput) GetSettlementCurrency() string {
	if x == nil {
		return ""
	}
	return x.SettlementCurrency
}

// ---------------------------------------------------------------------------
// CreateDraftBookingRequest
// ---------------------------------------------------------------------------

// CreateDraftBookingRequest mirrors the booking.proto message.
type CreateDraftBookingRequest struct {
	Channel            string
	AgentId            string
	StaffUserId        string
	PackageId          string
	DepartureId        string
	RoomType           string
	LeadFullName       string
	LeadEmail          string
	LeadWhatsapp       string
	LeadDomicile       string
	Pilgrims           []*PilgrimInput
	Addons             []*AddonInput
	ListAmount         int64
	ListCurrency       string
	SettlementCurrency string
	Notes              string
	IdempotencyKey     string
	MahramWarning      string
}

func (x *CreateDraftBookingRequest) Reset()         {}
func (x *CreateDraftBookingRequest) String() string { return "" }
func (x *CreateDraftBookingRequest) ProtoMessage()  {}

func (x *CreateDraftBookingRequest) GetChannel() string {
	if x == nil {
		return ""
	}
	return x.Channel
}
func (x *CreateDraftBookingRequest) GetAgentId() string {
	if x == nil {
		return ""
	}
	return x.AgentId
}
func (x *CreateDraftBookingRequest) GetStaffUserId() string {
	if x == nil {
		return ""
	}
	return x.StaffUserId
}
func (x *CreateDraftBookingRequest) GetPackageId() string {
	if x == nil {
		return ""
	}
	return x.PackageId
}
func (x *CreateDraftBookingRequest) GetDepartureId() string {
	if x == nil {
		return ""
	}
	return x.DepartureId
}
func (x *CreateDraftBookingRequest) GetRoomType() string {
	if x == nil {
		return ""
	}
	return x.RoomType
}
func (x *CreateDraftBookingRequest) GetLeadFullName() string {
	if x == nil {
		return ""
	}
	return x.LeadFullName
}
func (x *CreateDraftBookingRequest) GetLeadEmail() string {
	if x == nil {
		return ""
	}
	return x.LeadEmail
}
func (x *CreateDraftBookingRequest) GetLeadWhatsapp() string {
	if x == nil {
		return ""
	}
	return x.LeadWhatsapp
}
func (x *CreateDraftBookingRequest) GetLeadDomicile() string {
	if x == nil {
		return ""
	}
	return x.LeadDomicile
}
func (x *CreateDraftBookingRequest) GetPilgrims() []*PilgrimInput {
	if x == nil {
		return nil
	}
	return x.Pilgrims
}
func (x *CreateDraftBookingRequest) GetAddons() []*AddonInput {
	if x == nil {
		return nil
	}
	return x.Addons
}
func (x *CreateDraftBookingRequest) GetListAmount() int64 {
	if x == nil {
		return 0
	}
	return x.ListAmount
}
func (x *CreateDraftBookingRequest) GetListCurrency() string {
	if x == nil {
		return ""
	}
	return x.ListCurrency
}
func (x *CreateDraftBookingRequest) GetSettlementCurrency() string {
	if x == nil {
		return ""
	}
	return x.SettlementCurrency
}
func (x *CreateDraftBookingRequest) GetNotes() string {
	if x == nil {
		return ""
	}
	return x.Notes
}
func (x *CreateDraftBookingRequest) GetIdempotencyKey() string {
	if x == nil {
		return ""
	}
	return x.IdempotencyKey
}
func (x *CreateDraftBookingRequest) GetMahramWarning() string {
	if x == nil {
		return ""
	}
	return x.MahramWarning
}

// ---------------------------------------------------------------------------
// BookingItemResult
// ---------------------------------------------------------------------------

// BookingItemResult is one pilgrim in the CreateDraftBookingResponse.
type BookingItemResult struct {
	Id              string
	FullName        string
	IsLead          bool
	DocumentWarning string
}

func (x *BookingItemResult) Reset()         {}
func (x *BookingItemResult) String() string { return "" }
func (x *BookingItemResult) ProtoMessage()  {}

func (x *BookingItemResult) GetId() string {
	if x == nil {
		return ""
	}
	return x.Id
}
func (x *BookingItemResult) GetFullName() string {
	if x == nil {
		return ""
	}
	return x.FullName
}
func (x *BookingItemResult) GetIsLead() bool {
	if x == nil {
		return false
	}
	return x.IsLead
}
func (x *BookingItemResult) GetDocumentWarning() string {
	if x == nil {
		return ""
	}
	return x.DocumentWarning
}

// ---------------------------------------------------------------------------
// CreateDraftBookingResponse
// ---------------------------------------------------------------------------

// CreateDraftBookingResponse mirrors the booking.proto message.
type CreateDraftBookingResponse struct {
	Id                 string
	Status             string
	Channel            string
	PackageId          string
	DepartureId        string
	RoomType           string
	AgentId            string
	StaffUserId        string
	LeadFullName       string
	LeadEmail          string
	LeadWhatsapp       string
	LeadDomicile       string
	ListAmount         int64
	ListCurrency       string
	SettlementCurrency string
	Notes              string
	IdempotencyKey     string
	CreatedAt          string
	ExpiresAt          string
	Items              []*BookingItemResult
	MahramWarning      string
	Replayed           bool
}

func (x *CreateDraftBookingResponse) Reset()         {}
func (x *CreateDraftBookingResponse) String() string { return "" }
func (x *CreateDraftBookingResponse) ProtoMessage()  {}

func (x *CreateDraftBookingResponse) GetId() string {
	if x == nil {
		return ""
	}
	return x.Id
}
func (x *CreateDraftBookingResponse) GetStatus() string {
	if x == nil {
		return ""
	}
	return x.Status
}
func (x *CreateDraftBookingResponse) GetChannel() string {
	if x == nil {
		return ""
	}
	return x.Channel
}
func (x *CreateDraftBookingResponse) GetPackageId() string {
	if x == nil {
		return ""
	}
	return x.PackageId
}
func (x *CreateDraftBookingResponse) GetDepartureId() string {
	if x == nil {
		return ""
	}
	return x.DepartureId
}
func (x *CreateDraftBookingResponse) GetRoomType() string {
	if x == nil {
		return ""
	}
	return x.RoomType
}
func (x *CreateDraftBookingResponse) GetAgentId() string {
	if x == nil {
		return ""
	}
	return x.AgentId
}
func (x *CreateDraftBookingResponse) GetStaffUserId() string {
	if x == nil {
		return ""
	}
	return x.StaffUserId
}
func (x *CreateDraftBookingResponse) GetLeadFullName() string {
	if x == nil {
		return ""
	}
	return x.LeadFullName
}
func (x *CreateDraftBookingResponse) GetLeadEmail() string {
	if x == nil {
		return ""
	}
	return x.LeadEmail
}
func (x *CreateDraftBookingResponse) GetLeadWhatsapp() string {
	if x == nil {
		return ""
	}
	return x.LeadWhatsapp
}
func (x *CreateDraftBookingResponse) GetLeadDomicile() string {
	if x == nil {
		return ""
	}
	return x.LeadDomicile
}
func (x *CreateDraftBookingResponse) GetListAmount() int64 {
	if x == nil {
		return 0
	}
	return x.ListAmount
}
func (x *CreateDraftBookingResponse) GetListCurrency() string {
	if x == nil {
		return ""
	}
	return x.ListCurrency
}
func (x *CreateDraftBookingResponse) GetSettlementCurrency() string {
	if x == nil {
		return ""
	}
	return x.SettlementCurrency
}
func (x *CreateDraftBookingResponse) GetNotes() string {
	if x == nil {
		return ""
	}
	return x.Notes
}
func (x *CreateDraftBookingResponse) GetIdempotencyKey() string {
	if x == nil {
		return ""
	}
	return x.IdempotencyKey
}
func (x *CreateDraftBookingResponse) GetCreatedAt() string {
	if x == nil {
		return ""
	}
	return x.CreatedAt
}
func (x *CreateDraftBookingResponse) GetExpiresAt() string {
	if x == nil {
		return ""
	}
	return x.ExpiresAt
}
func (x *CreateDraftBookingResponse) GetItems() []*BookingItemResult {
	if x == nil {
		return nil
	}
	return x.Items
}
func (x *CreateDraftBookingResponse) GetMahramWarning() string {
	if x == nil {
		return ""
	}
	return x.MahramWarning
}
func (x *CreateDraftBookingResponse) GetReplayed() bool {
	if x == nil {
		return false
	}
	return x.Replayed
}

// ---------------------------------------------------------------------------
// SubmitBookingRequest / SubmitBookingResponse / BookingSummary
// ---------------------------------------------------------------------------

// SubmitBookingRequest is sent by gateway-svc to transition a booking
// from 'draft' to 'pending_payment'.
type SubmitBookingRequest struct {
	BookingId string
}

func (x *SubmitBookingRequest) Reset()         {}
func (x *SubmitBookingRequest) String() string { return "" }
func (x *SubmitBookingRequest) ProtoMessage()  {}
func (x *SubmitBookingRequest) GetBookingId() string {
	if x == nil {
		return ""
	}
	return x.BookingId
}

// SubmitBookingResponse carries the updated booking summary.
type SubmitBookingResponse struct {
	Booking *BookingSummary
}

func (x *SubmitBookingResponse) Reset()         {}
func (x *SubmitBookingResponse) String() string { return "" }
func (x *SubmitBookingResponse) ProtoMessage()  {}
func (x *SubmitBookingResponse) GetBooking() *BookingSummary {
	if x == nil {
		return nil
	}
	return x.Booking
}

// BookingSummary is a lightweight booking projection returned by SubmitBooking.
type BookingSummary struct {
	Id                 string
	Status             string
	Channel            string
	PackageId          string
	DepartureId        string
	RoomType           string
	LeadFullName       string
	LeadWhatsapp       string
	LeadDomicile       string
	ListAmount         int64
	ListCurrency       string
	SettlementCurrency string
}

func (x *BookingSummary) Reset()         {}
func (x *BookingSummary) String() string { return "" }
func (x *BookingSummary) ProtoMessage()  {}
func (x *BookingSummary) GetId() string {
	if x == nil {
		return ""
	}
	return x.Id
}
func (x *BookingSummary) GetStatus() string {
	if x == nil {
		return ""
	}
	return x.Status
}
func (x *BookingSummary) GetChannel() string {
	if x == nil {
		return ""
	}
	return x.Channel
}
func (x *BookingSummary) GetPackageId() string {
	if x == nil {
		return ""
	}
	return x.PackageId
}
func (x *BookingSummary) GetDepartureId() string {
	if x == nil {
		return ""
	}
	return x.DepartureId
}
func (x *BookingSummary) GetRoomType() string {
	if x == nil {
		return ""
	}
	return x.RoomType
}
func (x *BookingSummary) GetLeadFullName() string {
	if x == nil {
		return ""
	}
	return x.LeadFullName
}
func (x *BookingSummary) GetLeadWhatsapp() string {
	if x == nil {
		return ""
	}
	return x.LeadWhatsapp
}
func (x *BookingSummary) GetLeadDomicile() string {
	if x == nil {
		return ""
	}
	return x.LeadDomicile
}
func (x *BookingSummary) GetListAmount() int64 {
	if x == nil {
		return 0
	}
	return x.ListAmount
}
func (x *BookingSummary) GetListCurrency() string {
	if x == nil {
		return ""
	}
	return x.ListCurrency
}
func (x *BookingSummary) GetSettlementCurrency() string {
	if x == nil {
		return ""
	}
	return x.SettlementCurrency
}

// ---------------------------------------------------------------------------
// Error helpers (unused — kept to avoid import cycle if needed later)
// ---------------------------------------------------------------------------

var _ = codes.OK
var _ = status.New
