// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetDbTxDiagnostic(ctx context.Context, id int64) (Diagnostic, error)
	InsertDbTxDiagnostic(ctx context.Context, arg InsertDbTxDiagnosticParams) (Diagnostic, error)
	ReadyCheck(ctx context.Context) (int32, error)

	// Fulfillment task queries (S3-E-02 / BL-LOG-001)
	GetFulfillmentTaskByBookingID(ctx context.Context, bookingID string) (FulfillmentTaskRow, error)
	GetFulfillmentTaskByID(ctx context.Context, id string) (FulfillmentTaskRow, error)
	InsertFulfillmentTask(ctx context.Context, arg InsertFulfillmentTaskParams) (FulfillmentTaskRow, error)
	// ListFulfillmentTasks returns a paginated, filtered list of fulfillment tasks (ISSUE-018).
	ListFulfillmentTasks(ctx context.Context, arg ListFulfillmentTasksParams) ([]FulfillmentTaskRow, error)
	CountFulfillmentTasks(ctx context.Context, arg CountFulfillmentTasksParams) (int64, error)

	// Shipment queries (BL-LOG-002 / migration 000019)
	InsertShipment(ctx context.Context, arg InsertShipmentParams) (ShipmentRow, error)
	GetShipmentByTaskID(ctx context.Context, taskID string) (ShipmentRow, error)
	UpdateFulfillmentTaskStatus(ctx context.Context, arg UpdateFulfillmentTaskStatusParams) error

	// Pickup token queries (BL-LOG-003 / migration 000019)
	InsertPickupToken(ctx context.Context, arg InsertPickupTokenParams) (PickupTokenRow, error)
	GetPickupTokenByToken(ctx context.Context, token string) (PickupTokenRow, error)
	GetActivePickupTokenByTaskID(ctx context.Context, taskID string) (PickupTokenRow, error)
	MarkPickupTokenUsed(ctx context.Context, id string) (PickupTokenRow, error)

	// Purchase request + kit assembly queries (BL-LOG-010..012)
	InsertPurchaseRequest(ctx context.Context, arg InsertPurchaseRequestParams) (PurchaseRequestRow, error)
	GetPurchaseRequestByID(ctx context.Context, id string) (PurchaseRequestRow, error)
	UpdatePurchaseRequestDecision(ctx context.Context, arg UpdatePurchaseRequestDecisionParams) error
	InsertKitAssemblyIdempotent(ctx context.Context, arg InsertKitAssemblyParams) (KitAssemblyRow, bool, error)
	InsertKitAssemblyItem(ctx context.Context, arg InsertKitAssemblyItemParams) error
	UpdateKitAssemblyStatus(ctx context.Context, newStatus, id string) error
}

var _ Querier = (*Queries)(nil)
