// ops.sql.go — hand-written sqlc query implementations for ops schema.
// These would normally be generated by sqlc from ops.sql.
// Written by hand because sqlc binary is not available in the sandbox.

package sqlc

import (
	"context"
)

// ---------------------------------------------------------------------------
// Room allocation queries
// ---------------------------------------------------------------------------

const upsertRoomAllocation = `-- name: UpsertRoomAllocation :one
INSERT INTO ops.room_allocations (departure_id, status)
VALUES ($1, 'draft')
ON CONFLICT (departure_id) DO UPDATE
  SET updated_at = now()
WHERE ops.room_allocations.status = 'draft'
RETURNING id, departure_id, status, committed_at, created_at, updated_at
`

// UpsertRoomAllocation inserts a new draft allocation or returns the existing
// draft for the departure. Returns error if status is not 'draft'.
func (q *Queries) UpsertRoomAllocation(ctx context.Context, departureID string) (RoomAllocation, error) {
	row := q.db.QueryRow(ctx, upsertRoomAllocation, departureID)
	var i RoomAllocation
	err := row.Scan(
		&i.ID,
		&i.DepartureID,
		&i.Status,
		&i.CommittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomAllocationByDepartureID = `-- name: GetRoomAllocationByDepartureID :one
SELECT id, departure_id, status, committed_at, created_at, updated_at
FROM ops.room_allocations
WHERE departure_id = $1
`

func (q *Queries) GetRoomAllocationByDepartureID(ctx context.Context, departureID string) (RoomAllocation, error) {
	row := q.db.QueryRow(ctx, getRoomAllocationByDepartureID, departureID)
	var i RoomAllocation
	err := row.Scan(
		&i.ID,
		&i.DepartureID,
		&i.Status,
		&i.CommittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRoomAllocation = `-- name: InsertRoomAllocation :one
INSERT INTO ops.room_allocations (departure_id, status)
VALUES ($1, 'draft')
RETURNING id, departure_id, status, committed_at, created_at, updated_at
`

func (q *Queries) InsertRoomAllocation(ctx context.Context, departureID string) (RoomAllocation, error) {
	row := q.db.QueryRow(ctx, insertRoomAllocation, departureID)
	var i RoomAllocation
	err := row.Scan(
		&i.ID,
		&i.DepartureID,
		&i.Status,
		&i.CommittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoomAssignmentsByAllocationID = `-- name: DeleteRoomAssignmentsByAllocationID :exec
DELETE FROM ops.room_assignments WHERE allocation_id = $1
`

func (q *Queries) DeleteRoomAssignmentsByAllocationID(ctx context.Context, allocationID string) error {
	_, err := q.db.Exec(ctx, deleteRoomAssignmentsByAllocationID, allocationID)
	return err
}

// InsertRoomAssignmentParams holds parameters for InsertRoomAssignment.
type InsertRoomAssignmentParams struct {
	AllocationID string
	RoomNumber   string
	JamaahID     string
}

const insertRoomAssignment = `-- name: InsertRoomAssignment :one
INSERT INTO ops.room_assignments (allocation_id, room_number, jamaah_id)
VALUES ($1, $2, $3)
RETURNING id, allocation_id, room_number, jamaah_id, created_at
`

func (q *Queries) InsertRoomAssignment(ctx context.Context, arg InsertRoomAssignmentParams) (RoomAssignment, error) {
	row := q.db.QueryRow(ctx, insertRoomAssignment, arg.AllocationID, arg.RoomNumber, arg.JamaahID)
	var i RoomAssignment
	err := row.Scan(
		&i.ID,
		&i.AllocationID,
		&i.RoomNumber,
		&i.JamaahID,
		&i.CreatedAt,
	)
	return i, err
}

const listRoomAssignmentsByAllocationID = `-- name: ListRoomAssignmentsByAllocationID :many
SELECT id, allocation_id, room_number, jamaah_id, created_at
FROM ops.room_assignments
WHERE allocation_id = $1
ORDER BY room_number, jamaah_id
`

func (q *Queries) ListRoomAssignmentsByAllocationID(ctx context.Context, allocationID string) ([]RoomAssignment, error) {
	rows, err := q.db.Query(ctx, listRoomAssignmentsByAllocationID, allocationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []RoomAssignment
	for rows.Next() {
		var i RoomAssignment
		if err := rows.Scan(
			&i.ID,
			&i.AllocationID,
			&i.RoomNumber,
			&i.JamaahID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

// ---------------------------------------------------------------------------
// ID card issuance queries
// ---------------------------------------------------------------------------

// UpsertIDCardIssuanceParams holds parameters for UpsertIDCardIssuance.
type UpsertIDCardIssuanceParams struct {
	JamaahID    string
	DepartureID string
	CardType    string
	Token       string
}

const upsertIDCardIssuance = `-- name: UpsertIDCardIssuance :one
INSERT INTO ops.id_card_issuances (jamaah_id, departure_id, card_type, token)
VALUES ($1, $2, $3, $4)
ON CONFLICT (jamaah_id, departure_id, card_type) DO UPDATE
  SET token = EXCLUDED.token,
      issued_at = now()
RETURNING id, jamaah_id, departure_id, card_type, token, issued_at
`

func (q *Queries) UpsertIDCardIssuance(ctx context.Context, arg UpsertIDCardIssuanceParams) (IDCardIssuance, error) {
	row := q.db.QueryRow(ctx, upsertIDCardIssuance, arg.JamaahID, arg.DepartureID, arg.CardType, arg.Token)
	var i IDCardIssuance
	err := row.Scan(
		&i.ID,
		&i.JamaahID,
		&i.DepartureID,
		&i.CardType,
		&i.Token,
		&i.IssuedAt,
	)
	return i, err
}

const getIDCardIssuanceByToken = `-- name: GetIDCardIssuanceByToken :one
SELECT id, jamaah_id, departure_id, card_type, token, issued_at
FROM ops.id_card_issuances
WHERE token = $1
`

func (q *Queries) GetIDCardIssuanceByToken(ctx context.Context, token string) (IDCardIssuance, error) {
	row := q.db.QueryRow(ctx, getIDCardIssuanceByToken, token)
	var i IDCardIssuance
	err := row.Scan(
		&i.ID,
		&i.JamaahID,
		&i.DepartureID,
		&i.CardType,
		&i.Token,
		&i.IssuedAt,
	)
	return i, err
}
