// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system.sql

package sqlc

import (
	"context"
)

const readyCheck = `-- name: ReadyCheck :one
SELECT 1 AS ok
`

func (q *Queries) ReadyCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, readyCheck)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
