// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: catalog.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_Healthz_FullMethodName             = "/pb.CatalogService/Healthz"
	CatalogService_ListPackages_FullMethodName        = "/pb.CatalogService/ListPackages"
	CatalogService_GetPackage_FullMethodName          = "/pb.CatalogService/GetPackage"
	CatalogService_GetPackageDeparture_FullMethodName = "/pb.CatalogService/GetPackageDeparture"
	CatalogService_DiagnosticsDbTx_FullMethodName     = "/pb.CatalogService/DiagnosticsDbTx"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CatalogService — the catalog's only transport surface (packages + master
// data). Per ADR 0009 this service is gRPC-only; the public REST surface
// lives on gateway-svc (services/gateway-svc/api/rest_oapi/openapi.yaml
// § Catalog) which proxies to these RPCs.
//
// ListPackages / GetPackage / GetPackageDeparture landed in BL-GTW-002
// (S1-E-10). Dates are ISO YYYY-MM-DD strings (matching the service
// layer); enums stay as strings per the adapter pattern (cross-service
// type churn avoided; gateway's oapi-generated enum validation is the
// authoritative gate). DiagnosticsDbTx landed in BL-REFACTOR-001 (S1-E-11)
// when the legacy REST /system/diagnostics/db-tx was retired.
type CatalogServiceClient interface {
	// Healthz — pilot placeholder. Retained for reflection-based probing
	// that predates the standard grpc.health.v1.Health protocol added in
	// BL-MON-001; the standard protocol (empty + named service) is the
	// real health surface used by docker-compose and grpc_health_probe.
	Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzResponse, error)
	// ListPackages — public paginated list of active packages. Mirrors
	// GET /v1/packages on the current REST surface.
	ListPackages(ctx context.Context, in *ListPackagesRequest, opts ...grpc.CallOption) (*ListPackagesResponse, error)
	// GetPackage — public active-package detail. Returns NOT_FOUND for
	// draft/archived/unknown ids (no existence oracle). Mirrors
	// GET /v1/packages/{id}.
	GetPackage(ctx context.Context, in *GetPackageRequest, opts ...grpc.CallOption) (*GetPackageResponse, error)
	// GetPackageDeparture — public departure detail with live seat math.
	// Returns NOT_FOUND for departed/completed/cancelled/unknown.
	// Mirrors GET /v1/package-departures/{id}.
	GetPackageDeparture(ctx context.Context, in *GetPackageDepartureRequest, opts ...grpc.CallOption) (*GetPackageDepartureResponse, error)
	// DiagnosticsDbTx — state-mutating WithTx reference path. Inserts one
	// row into public.diagnostics, reads it back inside the same
	// transaction, echoes the message. Dev verification only (invoked via
	// grpcurl); per ADR 0009 there is no gateway REST route for this —
	// iam-svc's /v1/iam/system/diagnostics/db-tx already proves the
	// cross-service trace story (S0-J-05).
	DiagnosticsDbTx(ctx context.Context, in *DiagnosticsDbTxRequest, opts ...grpc.CallOption) (*DiagnosticsDbTxResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, CatalogService_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListPackages(ctx context.Context, in *ListPackagesRequest, opts ...grpc.CallOption) (*ListPackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPackagesResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetPackage(ctx context.Context, in *GetPackageRequest, opts ...grpc.CallOption) (*GetPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPackageResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetPackageDeparture(ctx context.Context, in *GetPackageDepartureRequest, opts ...grpc.CallOption) (*GetPackageDepartureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPackageDepartureResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetPackageDeparture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DiagnosticsDbTx(ctx context.Context, in *DiagnosticsDbTxRequest, opts ...grpc.CallOption) (*DiagnosticsDbTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosticsDbTxResponse)
	err := c.cc.Invoke(ctx, CatalogService_DiagnosticsDbTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
//
// CatalogService — the catalog's only transport surface (packages + master
// data). Per ADR 0009 this service is gRPC-only; the public REST surface
// lives on gateway-svc (services/gateway-svc/api/rest_oapi/openapi.yaml
// § Catalog) which proxies to these RPCs.
//
// ListPackages / GetPackage / GetPackageDeparture landed in BL-GTW-002
// (S1-E-10). Dates are ISO YYYY-MM-DD strings (matching the service
// layer); enums stay as strings per the adapter pattern (cross-service
// type churn avoided; gateway's oapi-generated enum validation is the
// authoritative gate). DiagnosticsDbTx landed in BL-REFACTOR-001 (S1-E-11)
// when the legacy REST /system/diagnostics/db-tx was retired.
type CatalogServiceServer interface {
	// Healthz — pilot placeholder. Retained for reflection-based probing
	// that predates the standard grpc.health.v1.Health protocol added in
	// BL-MON-001; the standard protocol (empty + named service) is the
	// real health surface used by docker-compose and grpc_health_probe.
	Healthz(context.Context, *HealthzRequest) (*HealthzResponse, error)
	// ListPackages — public paginated list of active packages. Mirrors
	// GET /v1/packages on the current REST surface.
	ListPackages(context.Context, *ListPackagesRequest) (*ListPackagesResponse, error)
	// GetPackage — public active-package detail. Returns NOT_FOUND for
	// draft/archived/unknown ids (no existence oracle). Mirrors
	// GET /v1/packages/{id}.
	GetPackage(context.Context, *GetPackageRequest) (*GetPackageResponse, error)
	// GetPackageDeparture — public departure detail with live seat math.
	// Returns NOT_FOUND for departed/completed/cancelled/unknown.
	// Mirrors GET /v1/package-departures/{id}.
	GetPackageDeparture(context.Context, *GetPackageDepartureRequest) (*GetPackageDepartureResponse, error)
	// DiagnosticsDbTx — state-mutating WithTx reference path. Inserts one
	// row into public.diagnostics, reads it back inside the same
	// transaction, echoes the message. Dev verification only (invoked via
	// grpcurl); per ADR 0009 there is no gateway REST route for this —
	// iam-svc's /v1/iam/system/diagnostics/db-tx already proves the
	// cross-service trace story (S0-J-05).
	DiagnosticsDbTx(context.Context, *DiagnosticsDbTxRequest) (*DiagnosticsDbTxResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) Healthz(context.Context, *HealthzRequest) (*HealthzResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedCatalogServiceServer) ListPackages(context.Context, *ListPackagesRequest) (*ListPackagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPackages not implemented")
}
func (UnimplementedCatalogServiceServer) GetPackage(context.Context, *GetPackageRequest) (*GetPackageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPackage not implemented")
}
func (UnimplementedCatalogServiceServer) GetPackageDeparture(context.Context, *GetPackageDepartureRequest) (*GetPackageDepartureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPackageDeparture not implemented")
}
func (UnimplementedCatalogServiceServer) DiagnosticsDbTx(context.Context, *DiagnosticsDbTxRequest) (*DiagnosticsDbTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiagnosticsDbTx not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call pancis, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthzRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).Healthz(ctx, req.(*HealthzRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListPackages(ctx, req.(*ListPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetPackage(ctx, req.(*GetPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetPackageDeparture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPackageDepartureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetPackageDeparture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetPackageDeparture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetPackageDeparture(ctx, req.(*GetPackageDepartureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DiagnosticsDbTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnosticsDbTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DiagnosticsDbTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DiagnosticsDbTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DiagnosticsDbTx(ctx, req.(*DiagnosticsDbTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _CatalogService_Healthz_Handler,
		},
		{
			MethodName: "ListPackages",
			Handler:    _CatalogService_ListPackages_Handler,
		},
		{
			MethodName: "GetPackage",
			Handler:    _CatalogService_GetPackage_Handler,
		},
		{
			MethodName: "GetPackageDeparture",
			Handler:    _CatalogService_GetPackageDeparture_Handler,
		},
		{
			MethodName: "DiagnosticsDbTx",
			Handler:    _CatalogService_DiagnosticsDbTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog.proto",
}
