// vendor_readiness_messages.go — hand-written proto message types for
// vendor readiness RPCs (BL-OPS-020).
//
// Would normally be generated by protoc into catalog.pb.go.
// Delete when protoc is available and run `make genpb`.

package pb

// ---------------------------------------------------------------------------
// UpdateVendorReadiness RPC
// ---------------------------------------------------------------------------

// UpdateVendorReadinessRequest is sent by the gateway to update one readiness
// kind for a departure. UserId is the acting staff subject (from bearer token).
type UpdateVendorReadinessRequest struct {
	UserId        string `json:"user_id"`
	DepartureId   string `json:"departure_id"`
	Kind          string `json:"kind"`           // ticket | hotel | visa
	State         string `json:"state"`          // not_started | in_progress | done
	Notes         string `json:"notes"`
	AttachmentUrl string `json:"attachment_url"`
}

func (x *UpdateVendorReadinessRequest) GetUserId() string {
	if x == nil {
		return ""
	}
	return x.UserId
}
func (x *UpdateVendorReadinessRequest) GetDepartureId() string {
	if x == nil {
		return ""
	}
	return x.DepartureId
}
func (x *UpdateVendorReadinessRequest) GetKind() string {
	if x == nil {
		return ""
	}
	return x.Kind
}
func (x *UpdateVendorReadinessRequest) GetState() string {
	if x == nil {
		return ""
	}
	return x.State
}
func (x *UpdateVendorReadinessRequest) GetNotes() string {
	if x == nil {
		return ""
	}
	return x.Notes
}
func (x *UpdateVendorReadinessRequest) GetAttachmentUrl() string {
	if x == nil {
		return ""
	}
	return x.AttachmentUrl
}

// UpdateVendorReadinessResponse returns the full readiness after the update.
type UpdateVendorReadinessResponse struct {
	Readiness *VendorReadiness `json:"readiness"`
}

func (x *UpdateVendorReadinessResponse) GetReadiness() *VendorReadiness {
	if x == nil {
		return nil
	}
	return x.Readiness
}

// ---------------------------------------------------------------------------
// GetDepartureReadiness RPC
// ---------------------------------------------------------------------------

// GetDepartureReadinessRequest fetches the current readiness for a departure.
// UserId is the acting staff subject (from bearer token).
type GetDepartureReadinessRequest struct {
	UserId      string `json:"user_id"`
	DepartureId string `json:"departure_id"`
}

func (x *GetDepartureReadinessRequest) GetUserId() string {
	if x == nil {
		return ""
	}
	return x.UserId
}
func (x *GetDepartureReadinessRequest) GetDepartureId() string {
	if x == nil {
		return ""
	}
	return x.DepartureId
}

// GetDepartureReadinessResponse carries the full readiness summary.
type GetDepartureReadinessResponse struct {
	Readiness *VendorReadiness `json:"readiness"`
}

func (x *GetDepartureReadinessResponse) GetReadiness() *VendorReadiness {
	if x == nil {
		return nil
	}
	return x.Readiness
}
