// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: crm.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrmService_Healthz_FullMethodName = "/pb.CrmService/Healthz"
)

// CrmServiceClient is the client API for CrmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CrmService — internal gRPC surface for Identity, Access, Audit.
//
// Pilot scaffold ships a single placeholder RPC (Healthz) so the service can
// come up and be callable over gRPC end-to-end. Real RPCs land in F1.7:
//   - ValidateToken
//   - CheckPermission
//   - GetUser
//   - RecordAudit
type CrmServiceClient interface {
	// Healthz returns ok=true if the service process is alive.
	// Placeholder for the pilot; real health checks go through gRPC health protocol.
	Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzResponse, error)
}

type crmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrmServiceClient(cc grpc.ClientConnInterface) CrmServiceClient {
	return &crmServiceClient{cc}
}

func (c *crmServiceClient) Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, CrmService_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrmServiceServer is the server API for CrmService service.
// All implementations must embed UnimplementedCrmServiceServer
// for forward compatibility.
//
// CrmService — internal gRPC surface for Identity, Access, Audit.
//
// Pilot scaffold ships a single placeholder RPC (Healthz) so the service can
// come up and be callable over gRPC end-to-end. Real RPCs land in F1.7:
//   - ValidateToken
//   - CheckPermission
//   - GetUser
//   - RecordAudit
type CrmServiceServer interface {
	// Healthz returns ok=true if the service process is alive.
	// Placeholder for the pilot; real health checks go through gRPC health protocol.
	Healthz(context.Context, *HealthzRequest) (*HealthzResponse, error)
	mustEmbedUnimplementedCrmServiceServer()
}

// UnimplementedCrmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrmServiceServer struct{}

func (UnimplementedCrmServiceServer) Healthz(context.Context, *HealthzRequest) (*HealthzResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedCrmServiceServer) mustEmbedUnimplementedCrmServiceServer() {}
func (UnimplementedCrmServiceServer) testEmbeddedByValue()                    {}

// UnsafeCrmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrmServiceServer will
// result in compilation errors.
type UnsafeCrmServiceServer interface {
	mustEmbedUnimplementedCrmServiceServer()
}

func RegisterCrmServiceServer(s grpc.ServiceRegistrar, srv CrmServiceServer) {
	// If the following call pancis, it indicates UnimplementedCrmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrmService_ServiceDesc, srv)
}

func _CrmService_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthzRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrmServiceServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrmService_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrmServiceServer).Healthz(ctx, req.(*HealthzRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrmService_ServiceDesc is the grpc.ServiceDesc for CrmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CrmService",
	HandlerType: (*CrmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _CrmService_Healthz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crm.proto",
}
