import { redirect } from '@sveltejs/kit';
import type { Cookies, RequestEvent } from '@sveltejs/kit';

// $types is generated by svelte-kit sync; fall back to RequestEvent when not yet generated
type LoadEvent = { cookies: Cookies; fetch: RequestEvent['fetch']; url: URL };

// Server-side env vars — VITE_* not available here, but fall back for local dev parity
const MOCK = process.env.MOCK_FINANCE === 'true' || process.env.VITE_MOCK_FINANCE === 'true';
const baseUrl =
  process.env.GATEWAY_URL ?? process.env.VITE_GATEWAY_URL ?? 'http://localhost:4000';

// ---- Types ----

export interface AccountSummary {
  account_code: string;
  debit_total: number;
  credit_total: number;
  net: number; // debit - credit
}

export interface JournalLine {
  id: string;
  entry_id: string;
  account_code: string;
  debit: number;
  credit: number;
}

export interface JournalEntry {
  id: string;
  idempotency_key: string;
  source_type: string;
  source_id: string;
  posted_at: string; // ISO 8601 RFC3339
  description: string;
  lines: JournalLine[];
}

export interface PageData {
  summary: AccountSummary[];
  journals: JournalEntry[];
  next_cursor: string | null;
  error: string | null;
}

// ---- Mock data ----

const MOCK_SUMMARY: AccountSummary[] = [
  {
    account_code: '1001',
    debit_total: 250_000_000,
    credit_total: 75_000_000,
    net: 175_000_000
  },
  {
    account_code: '2001',
    debit_total: 0,
    credit_total: 120_000_000,
    net: -120_000_000
  },
  {
    account_code: '4001',
    debit_total: 0,
    credit_total: 200_000_000,
    net: -200_000_000
  }
];

const MOCK_JOURNALS: JournalEntry[] = [
  {
    id: 'jrn_001',
    idempotency_key: 'booking-BK2024-001-payment',
    source_type: 'payment',
    source_id: 'BK2024-001',
    posted_at: '2024-03-15T08:30:00Z',
    description: 'Pembayaran DP Booking BK2024-001',
    lines: [
      { id: 'l_001', entry_id: 'jrn_001', account_code: '1001', debit: 10_000_000, credit: 0 },
      { id: 'l_002', entry_id: 'jrn_001', account_code: '2001', debit: 0, credit: 10_000_000 }
    ]
  },
  {
    id: 'jrn_002',
    idempotency_key: 'booking-BK2024-002-payment',
    source_type: 'payment',
    source_id: 'BK2024-002',
    posted_at: '2024-03-16T10:15:00Z',
    description: 'Pembayaran Lunas Booking BK2024-002',
    lines: [
      { id: 'l_003', entry_id: 'jrn_002', account_code: '1001', debit: 25_000_000, credit: 0 },
      { id: 'l_004', entry_id: 'jrn_002', account_code: '2001', debit: 0, credit: 15_000_000 },
      { id: 'l_005', entry_id: 'jrn_002', account_code: '4001', debit: 0, credit: 10_000_000 }
    ]
  },
  {
    id: 'jrn_003',
    idempotency_key: 'departure-DEP2024-01-settlement',
    source_type: 'departure',
    source_id: 'DEP2024-01',
    posted_at: '2024-03-20T14:00:00Z',
    description: 'Settlement Keberangkatan DEP2024-01',
    lines: [
      { id: 'l_006', entry_id: 'jrn_003', account_code: '2001', debit: 50_000_000, credit: 0 },
      { id: 'l_007', entry_id: 'jrn_003', account_code: '4001', debit: 0, credit: 50_000_000 }
    ]
  }
];

// ---- Load function ----

export const load = async ({ cookies, fetch, url }: LoadEvent): Promise<PageData> => {
  const accessToken = cookies.get('umrohos_access_token');
  if (!accessToken) {
    throw redirect(303, '/console/login');
  }

  if (MOCK) {
    return {
      summary: MOCK_SUMMARY,
      journals: MOCK_JOURNALS,
      next_cursor: null,
      error: null
    };
  }

  // Read optional filter/pagination query params from the current URL
  const from = url.searchParams.get('from') ?? '';
  const to = url.searchParams.get('to') ?? '';
  const cursor = url.searchParams.get('cursor') ?? '';
  const limitParam = url.searchParams.get('limit') ?? '50';

  // Build journals query string
  const journalParams = new URLSearchParams();
  journalParams.set('limit', limitParam);
  if (from) journalParams.set('from', from);
  if (to) journalParams.set('to', to);
  if (cursor) journalParams.set('cursor', cursor);

  try {
    const [summaryRes, journalsRes] = await Promise.all([
      fetch(`${baseUrl}/v1/finance/summary`, {
        headers: { Authorization: `Bearer ${accessToken}` }
      }),
      fetch(`${baseUrl}/v1/finance/journals?${journalParams.toString()}`, {
        headers: { Authorization: `Bearer ${accessToken}` }
      })
    ]);

    // Gateway returns { data: AccountBalanceData[] } for summary
    const summaryBody: { data: AccountSummary[] } = summaryRes.ok
      ? ((await summaryRes.json()) as { data: AccountSummary[] })
      : { data: [] };

    // Gateway returns { data: JournalEntryData[], next_cursor: string } for journals
    const journalsBody: { data: JournalEntry[]; next_cursor: string | null } = journalsRes.ok
      ? ((await journalsRes.json()) as { data: JournalEntry[]; next_cursor: string | null })
      : { data: [], next_cursor: null };

    const error =
      !summaryRes.ok
        ? `Gagal memuat ringkasan akun (${summaryRes.status})`
        : !journalsRes.ok
          ? `Gagal memuat riwayat jurnal (${journalsRes.status})`
          : null;

    return {
      summary: Array.isArray(summaryBody.data) ? summaryBody.data : [],
      journals: journalsBody.data ?? [],
      next_cursor: journalsBody.next_cursor ?? null,
      error
    };
  } catch {
    return {
      summary: [],
      journals: [],
      next_cursor: null,
      error: 'Tidak dapat terhubung ke gateway.'
    };
  }
};
