// logistics_messages.go — hand-written proto message types for the
// OnBookingPaid RPC added in S3-E-02.
//
// NOTE: These types would normally be generated by protoc from logistics.proto.
// They are written by hand because protoc is not available in the sandbox.
// Run `make genpb` to regenerate cleanly from logistics.proto once protoc is
// available in the build environment.
//
// OnBookingPaid is called by booking-svc after a booking transitions to
// paid_in_full, triggering kit dispatch queue creation in logistics-svc.

package pb

// OnBookingPaidRequest carries the booking context needed to create a
// fulfillment task.  JamaahIds is required (min 1) per §S3-J-02 contract.
type OnBookingPaidRequest struct {
	BookingId   string
	DepartureId string
	JamaahIds   []string // at least 1 element; ULIDs of jamaah on this booking
}

func (x *OnBookingPaidRequest) GetBookingId() string {
	if x == nil {
		return ""
	}
	return x.BookingId
}

func (x *OnBookingPaidRequest) GetDepartureId() string {
	if x == nil {
		return ""
	}
	return x.DepartureId
}

func (x *OnBookingPaidRequest) GetJamaahIds() []string {
	if x == nil {
		return nil
	}
	return x.JamaahIds
}

// OnBookingPaidResponse returns the fulfillment task that was created (or the
// existing task if one already existed for this booking).
type OnBookingPaidResponse struct {
	TaskId string
	Status string
}

func (x *OnBookingPaidResponse) GetTaskId() string {
	if x == nil {
		return ""
	}
	return x.TaskId
}

func (x *OnBookingPaidResponse) GetStatus() string {
	if x == nil {
		return ""
	}
	return x.Status
}
