// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetDbTxDiagnostic(ctx context.Context, id int64) (Diagnostic, error)
	InsertDbTxDiagnostic(ctx context.Context, arg InsertDbTxDiagnosticParams) (Diagnostic, error)
	ReadyCheck(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
