// Package rest_oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package rest_oapi

import (
	"context"
	"fmt"
	"net/url"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// DbTxDiagnosticResponse defines model for DbTxDiagnosticResponse.
type DbTxDiagnosticResponse struct {
	Data struct {
		// DiagnosticId ID of the inserted diagnostic row.
		DiagnosticId int64 `json:"diagnostic_id"`

		// Message Echo of the message received from the client.
		Message string `json:"message"`
	} `json:"data"`
}

// LiveResponse defines model for LiveResponse.
type LiveResponse struct {
	Data struct {
		Ok bool `json:"ok"`
	} `json:"data"`
}

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	Data struct {
		Ok bool `json:"ok"`
	} `json:"data"`
}

// DbTxDiagnosticParams defines parameters for DbTxDiagnostic.
type DbTxDiagnosticParams struct {
	// Message Message to store and echo back.
	Message *string `form:"message,omitempty" json:"message,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// DB transaction diagnostic
	// (GET /system/diagnostics/db-tx)
	DbTxDiagnostic(c *fiber.Ctx, params DbTxDiagnosticParams) error
	// Liveness probe
	// (GET /system/live)
	Liveness(c *fiber.Ctx) error
	// Readiness probe
	// (GET /system/ready)
	Readiness(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// DbTxDiagnostic operation middleware
func (siw *ServerInterfaceWrapper) DbTxDiagnostic(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DbTxDiagnosticParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "message" -------------

	err = runtime.BindQueryParameter("form", true, false, "message", query, &params.Message)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter message: %w", err).Error())
	}

	return siw.Handler.DbTxDiagnostic(c, params)
}

// Liveness operation middleware
func (siw *ServerInterfaceWrapper) Liveness(c *fiber.Ctx) error {

	return siw.Handler.Liveness(c)
}

// Readiness operation middleware
func (siw *ServerInterfaceWrapper) Readiness(c *fiber.Ctx) error {

	return siw.Handler.Readiness(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/system/diagnostics/db-tx", wrapper.DbTxDiagnostic)

	router.Get(options.BaseURL+"/system/live", wrapper.Liveness)

	router.Get(options.BaseURL+"/system/ready", wrapper.Readiness)

}

type DbTxDiagnosticRequestObject struct {
	Params DbTxDiagnosticParams
}

type DbTxDiagnosticResponseObject interface {
	VisitDbTxDiagnosticResponse(ctx *fiber.Ctx) error
}

type DbTxDiagnostic200JSONResponse DbTxDiagnosticResponse

func (response DbTxDiagnostic200JSONResponse) VisitDbTxDiagnosticResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type LivenessRequestObject struct {
}

type LivenessResponseObject interface {
	VisitLivenessResponse(ctx *fiber.Ctx) error
}

type Liveness200JSONResponse LiveResponse

func (response Liveness200JSONResponse) VisitLivenessResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ReadinessRequestObject struct {
}

type ReadinessResponseObject interface {
	VisitReadinessResponse(ctx *fiber.Ctx) error
}

type Readiness200JSONResponse ReadyResponse

func (response Readiness200JSONResponse) VisitReadinessResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// DB transaction diagnostic
	// (GET /system/diagnostics/db-tx)
	DbTxDiagnostic(ctx context.Context, request DbTxDiagnosticRequestObject) (DbTxDiagnosticResponseObject, error)
	// Liveness probe
	// (GET /system/live)
	Liveness(ctx context.Context, request LivenessRequestObject) (LivenessResponseObject, error)
	// Readiness probe
	// (GET /system/ready)
	Readiness(ctx context.Context, request ReadinessRequestObject) (ReadinessResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// DbTxDiagnostic operation middleware
func (sh *strictHandler) DbTxDiagnostic(ctx *fiber.Ctx, params DbTxDiagnosticParams) error {
	var request DbTxDiagnosticRequestObject

	request.Params = params

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DbTxDiagnostic(ctx.UserContext(), request.(DbTxDiagnosticRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DbTxDiagnostic")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(DbTxDiagnosticResponseObject); ok {
		if err := validResponse.VisitDbTxDiagnosticResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Liveness operation middleware
func (sh *strictHandler) Liveness(ctx *fiber.Ctx) error {
	var request LivenessRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Liveness(ctx.UserContext(), request.(LivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Liveness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(LivenessResponseObject); ok {
		if err := validResponse.VisitLivenessResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Readiness operation middleware
func (sh *strictHandler) Readiness(ctx *fiber.Ctx) error {
	var request ReadinessRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Readiness(ctx.UserContext(), request.(ReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Readiness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ReadinessResponseObject); ok {
		if err := validResponse.VisitReadinessResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
