// payment_models.go — hand-written sqlc model structs for payment-svc S2-E-02.
//
// NOTE: These structs would normally be generated by `sqlc generate` into models.go.
// They are written by hand here because sqlc is not available in the sandbox.
// Run `make generate` (or `sqlc generate`) from the postgres_store directory to
// regenerate — then delete this file and merge into the generated models.go.
//
// Follows the same conventions as the auto-generated models.go: pgtype for
// nullable/timestamp columns, json tags matching column names.

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// ---------------------------------------------------------------------------
// Invoice
// ---------------------------------------------------------------------------

type Invoice struct {
	ID                    pgtype.UUID        `json:"id"`
	BookingID             pgtype.UUID        `json:"booking_id"`
	AmountTotal           pgtype.Numeric     `json:"amount_total"`
	RoundingAdjustmentIdr pgtype.Numeric     `json:"rounding_adjustment_idr"`
	Currency              string             `json:"currency"`
	FxSnapshot            []byte             `json:"fx_snapshot"`
	Status                string             `json:"status"`
	PaidAmount            pgtype.Numeric     `json:"paid_amount"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// ---------------------------------------------------------------------------
// VirtualAccount
// ---------------------------------------------------------------------------

type VirtualAccount struct {
	ID             pgtype.UUID        `json:"id"`
	InvoiceID      pgtype.UUID        `json:"invoice_id"`
	Gateway        string             `json:"gateway"`
	GatewayVaID    string             `json:"gateway_va_id"`
	AccountNumber  string             `json:"account_number"`
	BankCode       string             `json:"bank_code"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// ---------------------------------------------------------------------------
// PaymentEvent
// ---------------------------------------------------------------------------

type PaymentEvent struct {
	ID             pgtype.UUID        `json:"id"`
	InvoiceID      pgtype.UUID        `json:"invoice_id"`
	Gateway        string             `json:"gateway"`
	GatewayTxnID   pgtype.Text        `json:"gateway_txn_id"`
	Kind           string             `json:"kind"`
	Amount         pgtype.Numeric     `json:"amount"`
	RawPayload     []byte             `json:"raw_payload"`
	ApprovalStatus pgtype.Text        `json:"approval_status"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// ---------------------------------------------------------------------------
// Refund
// ---------------------------------------------------------------------------

type Refund struct {
	ID               pgtype.UUID        `json:"id"`
	InvoiceID        pgtype.UUID        `json:"invoice_id"`
	BookingID        pgtype.UUID        `json:"booking_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	ReasonCode       pgtype.Text        `json:"reason_code"`
	Status           string             `json:"status"`
	GatewayRefundID  pgtype.Text        `json:"gateway_refund_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
