// payment.sql.go — hand-written sqlc query implementations for payment-svc S2-E-02.
//
// NOTE: These functions would normally be generated by `sqlc generate` from
// payment.sql. They are written by hand because sqlc is not available in the
// sandbox. Run `make generate` to regenerate, then delete this file.
//
// Each function follows the exact same pattern as the auto-generated system.sql.go:
// embed the SQL constant, call QueryRow/Query, scan fields in SELECT column order.

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ===========================================================================
// invoices
// ===========================================================================

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO payment.invoices (
    booking_id,
    amount_total,
    rounding_adjustment_idr,
    currency,
    fx_snapshot,
    status,
    paid_amount
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, booking_id, amount_total, rounding_adjustment_idr, currency, fx_snapshot, status, paid_amount, created_at, updated_at`

type CreateInvoiceParams struct {
	BookingID             pgtype.UUID    `json:"booking_id"`
	AmountTotal           pgtype.Numeric `json:"amount_total"`
	RoundingAdjustmentIdr pgtype.Numeric `json:"rounding_adjustment_idr"`
	Currency              string         `json:"currency"`
	FxSnapshot            []byte         `json:"fx_snapshot"`
	Status                string         `json:"status"`
	PaidAmount            pgtype.Numeric `json:"paid_amount"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.BookingID,
		arg.AmountTotal,
		arg.RoundingAdjustmentIdr,
		arg.Currency,
		arg.FxSnapshot,
		arg.Status,
		arg.PaidAmount,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.AmountTotal,
		&i.RoundingAdjustmentIdr,
		&i.Currency,
		&i.FxSnapshot,
		&i.Status,
		&i.PaidAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, booking_id, amount_total, rounding_adjustment_idr, currency, fx_snapshot, status, paid_amount, created_at, updated_at
FROM payment.invoices
WHERE id = $1`

func (q *Queries) GetInvoiceByID(ctx context.Context, id pgtype.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.AmountTotal,
		&i.RoundingAdjustmentIdr,
		&i.Currency,
		&i.FxSnapshot,
		&i.Status,
		&i.PaidAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByBookingID = `-- name: GetInvoiceByBookingID :one
SELECT id, booking_id, amount_total, rounding_adjustment_idr, currency, fx_snapshot, status, paid_amount, created_at, updated_at
FROM payment.invoices
WHERE booking_id = $1
ORDER BY created_at DESC
LIMIT 1`

func (q *Queries) GetInvoiceByBookingID(ctx context.Context, bookingID pgtype.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByBookingID, bookingID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.AmountTotal,
		&i.RoundingAdjustmentIdr,
		&i.Currency,
		&i.FxSnapshot,
		&i.Status,
		&i.PaidAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvoicePaidAmount = `-- name: UpdateInvoicePaidAmount :one
UPDATE payment.invoices
SET
    paid_amount = $2,
    status      = $3,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, booking_id, amount_total, rounding_adjustment_idr, currency, fx_snapshot, status, paid_amount, created_at, updated_at`

type UpdateInvoicePaidAmountParams struct {
	ID         pgtype.UUID    `json:"id"`
	PaidAmount pgtype.Numeric `json:"paid_amount"`
	Status     string         `json:"status"`
}

func (q *Queries) UpdateInvoicePaidAmount(ctx context.Context, arg UpdateInvoicePaidAmountParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoicePaidAmount, arg.ID, arg.PaidAmount, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.AmountTotal,
		&i.RoundingAdjustmentIdr,
		&i.Currency,
		&i.FxSnapshot,
		&i.Status,
		&i.PaidAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE payment.invoices
SET
    status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, booking_id, amount_total, rounding_adjustment_idr, currency, fx_snapshot, status, paid_amount, created_at, updated_at`

type UpdateInvoiceStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.ID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.AmountTotal,
		&i.RoundingAdjustmentIdr,
		&i.Currency,
		&i.FxSnapshot,
		&i.Status,
		&i.PaidAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnpaidInvoicesWithActiveVA = `-- name: ListUnpaidInvoicesWithActiveVA :many
SELECT DISTINCT ON (i.id)
    i.id, i.booking_id, i.amount_total, i.rounding_adjustment_idr, i.currency,
    i.fx_snapshot, i.status, i.paid_amount, i.created_at, i.updated_at
FROM payment.invoices i
JOIN payment.virtual_accounts va ON va.invoice_id = i.id
WHERE i.status IN ('unpaid', 'partially_paid')
  AND va.status = 'active'
  AND va.expires_at > NOW()
ORDER BY i.id, i.created_at ASC`

func (q *Queries) ListUnpaidInvoicesWithActiveVA(ctx context.Context) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listUnpaidInvoicesWithActiveVA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.AmountTotal,
			&i.RoundingAdjustmentIdr,
			&i.Currency,
			&i.FxSnapshot,
			&i.Status,
			&i.PaidAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

// ===========================================================================
// virtual_accounts
// ===========================================================================

const createVirtualAccount = `-- name: CreateVirtualAccount :one
INSERT INTO payment.virtual_accounts (
    invoice_id,
    gateway,
    gateway_va_id,
    account_number,
    bank_code,
    expires_at,
    status,
    idempotency_key
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, invoice_id, gateway, gateway_va_id, account_number, bank_code, expires_at, status, idempotency_key, created_at`

type CreateVirtualAccountParams struct {
	InvoiceID      pgtype.UUID        `json:"invoice_id"`
	Gateway        string             `json:"gateway"`
	GatewayVaID    string             `json:"gateway_va_id"`
	AccountNumber  string             `json:"account_number"`
	BankCode       string             `json:"bank_code"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	Status         string             `json:"status"`
	IdempotencyKey string             `json:"idempotency_key"`
}

func (q *Queries) CreateVirtualAccount(ctx context.Context, arg CreateVirtualAccountParams) (VirtualAccount, error) {
	row := q.db.QueryRow(ctx, createVirtualAccount,
		arg.InvoiceID,
		arg.Gateway,
		arg.GatewayVaID,
		arg.AccountNumber,
		arg.BankCode,
		arg.ExpiresAt,
		arg.Status,
		arg.IdempotencyKey,
	)
	var va VirtualAccount
	err := row.Scan(
		&va.ID,
		&va.InvoiceID,
		&va.Gateway,
		&va.GatewayVaID,
		&va.AccountNumber,
		&va.BankCode,
		&va.ExpiresAt,
		&va.Status,
		&va.IdempotencyKey,
		&va.CreatedAt,
	)
	return va, err
}

const getVAByInvoiceID = `-- name: GetVAByInvoiceID :one
SELECT id, invoice_id, gateway, gateway_va_id, account_number, bank_code, expires_at, status, idempotency_key, created_at
FROM payment.virtual_accounts
WHERE invoice_id = $1
ORDER BY created_at DESC
LIMIT 1`

func (q *Queries) GetVAByInvoiceID(ctx context.Context, invoiceID pgtype.UUID) (VirtualAccount, error) {
	row := q.db.QueryRow(ctx, getVAByInvoiceID, invoiceID)
	var va VirtualAccount
	err := row.Scan(
		&va.ID,
		&va.InvoiceID,
		&va.Gateway,
		&va.GatewayVaID,
		&va.AccountNumber,
		&va.BankCode,
		&va.ExpiresAt,
		&va.Status,
		&va.IdempotencyKey,
		&va.CreatedAt,
	)
	return va, err
}

const getVAByIdempotencyKey = `-- name: GetVAByIdempotencyKey :one
SELECT id, invoice_id, gateway, gateway_va_id, account_number, bank_code, expires_at, status, idempotency_key, created_at
FROM payment.virtual_accounts
WHERE idempotency_key = $1`

func (q *Queries) GetVAByIdempotencyKey(ctx context.Context, idempotencyKey string) (VirtualAccount, error) {
	row := q.db.QueryRow(ctx, getVAByIdempotencyKey, idempotencyKey)
	var va VirtualAccount
	err := row.Scan(
		&va.ID,
		&va.InvoiceID,
		&va.Gateway,
		&va.GatewayVaID,
		&va.AccountNumber,
		&va.BankCode,
		&va.ExpiresAt,
		&va.Status,
		&va.IdempotencyKey,
		&va.CreatedAt,
	)
	return va, err
}

const updateVAStatus = `-- name: UpdateVAStatus :one
UPDATE payment.virtual_accounts
SET status = $2
WHERE id = $1
RETURNING id, invoice_id, gateway, gateway_va_id, account_number, bank_code, expires_at, status, idempotency_key, created_at`

type UpdateVAStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateVAStatus(ctx context.Context, arg UpdateVAStatusParams) (VirtualAccount, error) {
	row := q.db.QueryRow(ctx, updateVAStatus, arg.ID, arg.Status)
	var va VirtualAccount
	err := row.Scan(
		&va.ID,
		&va.InvoiceID,
		&va.Gateway,
		&va.GatewayVaID,
		&va.AccountNumber,
		&va.BankCode,
		&va.ExpiresAt,
		&va.Status,
		&va.IdempotencyKey,
		&va.CreatedAt,
	)
	return va, err
}

const listActiveVAsByInvoiceID = `-- name: ListActiveVAsByInvoiceID :many
SELECT id, invoice_id, gateway, gateway_va_id, account_number, bank_code, expires_at, status, idempotency_key, created_at
FROM payment.virtual_accounts
WHERE invoice_id = $1
  AND status = 'active'`

func (q *Queries) ListActiveVAsByInvoiceID(ctx context.Context, invoiceID pgtype.UUID) ([]VirtualAccount, error) {
	rows, err := q.db.Query(ctx, listActiveVAsByInvoiceID, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VirtualAccount
	for rows.Next() {
		var va VirtualAccount
		if err := rows.Scan(
			&va.ID,
			&va.InvoiceID,
			&va.Gateway,
			&va.GatewayVaID,
			&va.AccountNumber,
			&va.BankCode,
			&va.ExpiresAt,
			&va.Status,
			&va.IdempotencyKey,
			&va.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, va)
	}
	return items, rows.Err()
}

// ===========================================================================
// payment_events
// ===========================================================================

const createPaymentEvent = `-- name: CreatePaymentEvent :one
INSERT INTO payment.payment_events (
    invoice_id,
    gateway,
    gateway_txn_id,
    kind,
    amount,
    raw_payload,
    approval_status,
    received_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, invoice_id, gateway, gateway_txn_id, kind, amount, raw_payload, approval_status, received_at, created_at`

type CreatePaymentEventParams struct {
	InvoiceID      pgtype.UUID        `json:"invoice_id"`
	Gateway        string             `json:"gateway"`
	GatewayTxnID   pgtype.Text        `json:"gateway_txn_id"`
	Kind           string             `json:"kind"`
	Amount         pgtype.Numeric     `json:"amount"`
	RawPayload     []byte             `json:"raw_payload"`
	ApprovalStatus pgtype.Text        `json:"approval_status"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) CreatePaymentEvent(ctx context.Context, arg CreatePaymentEventParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, createPaymentEvent,
		arg.InvoiceID,
		arg.Gateway,
		arg.GatewayTxnID,
		arg.Kind,
		arg.Amount,
		arg.RawPayload,
		arg.ApprovalStatus,
		arg.ReceivedAt,
	)
	var pe PaymentEvent
	err := row.Scan(
		&pe.ID,
		&pe.InvoiceID,
		&pe.Gateway,
		&pe.GatewayTxnID,
		&pe.Kind,
		&pe.Amount,
		&pe.RawPayload,
		&pe.ApprovalStatus,
		&pe.ReceivedAt,
		&pe.CreatedAt,
	)
	return pe, err
}

const getPaymentEventByGatewayTxnID = `-- name: GetPaymentEventByGatewayTxnID :one
SELECT id, invoice_id, gateway, gateway_txn_id, kind, amount, raw_payload, approval_status, received_at, created_at
FROM payment.payment_events
WHERE gateway = $1
  AND gateway_txn_id = $2`

type GetPaymentEventByGatewayTxnIDParams struct {
	Gateway      string `json:"gateway"`
	GatewayTxnID string `json:"gateway_txn_id"`
}

func (q *Queries) GetPaymentEventByGatewayTxnID(ctx context.Context, arg GetPaymentEventByGatewayTxnIDParams) (PaymentEvent, error) {
	row := q.db.QueryRow(ctx, getPaymentEventByGatewayTxnID, arg.Gateway, arg.GatewayTxnID)
	var pe PaymentEvent
	err := row.Scan(
		&pe.ID,
		&pe.InvoiceID,
		&pe.Gateway,
		&pe.GatewayTxnID,
		&pe.Kind,
		&pe.Amount,
		&pe.RawPayload,
		&pe.ApprovalStatus,
		&pe.ReceivedAt,
		&pe.CreatedAt,
	)
	return pe, err
}

const listPaymentEventsByInvoiceID = `-- name: ListPaymentEventsByInvoiceID :many
SELECT id, invoice_id, gateway, gateway_txn_id, kind, amount, raw_payload, approval_status, received_at, created_at
FROM payment.payment_events
WHERE invoice_id = $1
ORDER BY received_at ASC`

func (q *Queries) ListPaymentEventsByInvoiceID(ctx context.Context, invoiceID pgtype.UUID) ([]PaymentEvent, error) {
	rows, err := q.db.Query(ctx, listPaymentEventsByInvoiceID, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentEvent
	for rows.Next() {
		var pe PaymentEvent
		if err := rows.Scan(
			&pe.ID,
			&pe.InvoiceID,
			&pe.Gateway,
			&pe.GatewayTxnID,
			&pe.Kind,
			&pe.Amount,
			&pe.RawPayload,
			&pe.ApprovalStatus,
			&pe.ReceivedAt,
			&pe.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, pe)
	}
	return items, rows.Err()
}

// ===========================================================================
// refunds
// ===========================================================================

const createRefund = `-- name: CreateRefund :one
INSERT INTO payment.refunds (
    invoice_id,
    booking_id,
    amount,
    reason_code,
    status,
    gateway_refund_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, invoice_id, booking_id, amount, reason_code, status, gateway_refund_id, created_at, updated_at`

type CreateRefundParams struct {
	InvoiceID       pgtype.UUID    `json:"invoice_id"`
	BookingID       pgtype.UUID    `json:"booking_id"`
	Amount          pgtype.Numeric `json:"amount"`
	ReasonCode      pgtype.Text    `json:"reason_code"`
	Status          string         `json:"status"`
	GatewayRefundID pgtype.Text    `json:"gateway_refund_id"`
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error) {
	row := q.db.QueryRow(ctx, createRefund,
		arg.InvoiceID,
		arg.BookingID,
		arg.Amount,
		arg.ReasonCode,
		arg.Status,
		arg.GatewayRefundID,
	)
	var r Refund
	err := row.Scan(
		&r.ID,
		&r.InvoiceID,
		&r.BookingID,
		&r.Amount,
		&r.ReasonCode,
		&r.Status,
		&r.GatewayRefundID,
		&r.CreatedAt,
		&r.UpdatedAt,
	)
	return r, err
}

const updateRefundStatus = `-- name: UpdateRefundStatus :one
UPDATE payment.refunds
SET
    status            = $2,
    gateway_refund_id = COALESCE($3, gateway_refund_id),
    updated_at        = NOW()
WHERE id = $1
RETURNING id, invoice_id, booking_id, amount, reason_code, status, gateway_refund_id, created_at, updated_at`

type UpdateRefundStatusParams struct {
	ID              pgtype.UUID `json:"id"`
	Status          string      `json:"status"`
	GatewayRefundID pgtype.Text `json:"gateway_refund_id"`
}

func (q *Queries) UpdateRefundStatus(ctx context.Context, arg UpdateRefundStatusParams) (Refund, error) {
	row := q.db.QueryRow(ctx, updateRefundStatus, arg.ID, arg.Status, arg.GatewayRefundID)
	var r Refund
	err := row.Scan(
		&r.ID,
		&r.InvoiceID,
		&r.BookingID,
		&r.Amount,
		&r.ReasonCode,
		&r.Status,
		&r.GatewayRefundID,
		&r.CreatedAt,
		&r.UpdatedAt,
	)
	return r, err
}

const getRefundByID = `-- name: GetRefundByID :one
SELECT id, invoice_id, booking_id, amount, reason_code, status, gateway_refund_id, created_at, updated_at
FROM payment.refunds
WHERE id = $1`

func (q *Queries) GetRefundByID(ctx context.Context, id pgtype.UUID) (Refund, error) {
	row := q.db.QueryRow(ctx, getRefundByID, id)
	var r Refund
	err := row.Scan(
		&r.ID,
		&r.InvoiceID,
		&r.BookingID,
		&r.Amount,
		&r.ReasonCode,
		&r.Status,
		&r.GatewayRefundID,
		&r.CreatedAt,
		&r.UpdatedAt,
	)
	return r, err
}
