// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
//
// NOTE: payment_* methods are hand-written (S2-E-02) and will be folded into
// generated output once sqlc can be run against the 000012 migration schema.

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// system
	GetDbTxDiagnostic(ctx context.Context, id int64) (Diagnostic, error)
	InsertDbTxDiagnostic(ctx context.Context, arg InsertDbTxDiagnosticParams) (Diagnostic, error)
	ReadyCheck(ctx context.Context) (int32, error)

	// invoices
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	GetInvoiceByID(ctx context.Context, id pgtype.UUID) (Invoice, error)
	GetInvoiceByBookingID(ctx context.Context, bookingID pgtype.UUID) (Invoice, error)
	UpdateInvoicePaidAmount(ctx context.Context, arg UpdateInvoicePaidAmountParams) (Invoice, error)
	UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error)
	ListUnpaidInvoicesWithActiveVA(ctx context.Context) ([]Invoice, error)

	// virtual_accounts
	CreateVirtualAccount(ctx context.Context, arg CreateVirtualAccountParams) (VirtualAccount, error)
	GetVAByInvoiceID(ctx context.Context, invoiceID pgtype.UUID) (VirtualAccount, error)
	GetVAByIdempotencyKey(ctx context.Context, idempotencyKey string) (VirtualAccount, error)
	UpdateVAStatus(ctx context.Context, arg UpdateVAStatusParams) (VirtualAccount, error)
	ListActiveVAsByInvoiceID(ctx context.Context, invoiceID pgtype.UUID) ([]VirtualAccount, error)

	// payment_events
	CreatePaymentEvent(ctx context.Context, arg CreatePaymentEventParams) (PaymentEvent, error)
	GetPaymentEventByGatewayTxnID(ctx context.Context, arg GetPaymentEventByGatewayTxnIDParams) (PaymentEvent, error)
	ListPaymentEventsByInvoiceID(ctx context.Context, invoiceID pgtype.UUID) ([]PaymentEvent, error)

	// refunds
	CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error)
	UpdateRefundStatus(ctx context.Context, arg UpdateRefundStatusParams) (Refund, error)
	GetRefundByID(ctx context.Context, id pgtype.UUID) (Refund, error)
}

var _ Querier = (*Queries)(nil)
