// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: catalog.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Money is the display-only currency triple from § Catalog. Settlement
// currency is always "IDR" in MVP per Q001.
type Money struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ListAmount         int64                  `protobuf:"varint,1,opt,name=list_amount,json=listAmount,proto3" json:"list_amount,omitempty"`
	ListCurrency       string                 `protobuf:"bytes,2,opt,name=list_currency,json=listCurrency,proto3" json:"list_currency,omitempty"`                   // "IDR" | "USD"
	SettlementCurrency string                 `protobuf:"bytes,3,opt,name=settlement_currency,json=settlementCurrency,proto3" json:"settlement_currency,omitempty"` // "IDR"
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetListAmount() int64 {
	if x != nil {
		return x.ListAmount
	}
	return 0
}

func (x *Money) GetListCurrency() string {
	if x != nil {
		return x.ListCurrency
	}
	return ""
}

func (x *Money) GetSettlementCurrency() string {
	if x != nil {
		return x.SettlementCurrency
	}
	return ""
}

type HotelRef struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City             string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	StarRating       int32                  `protobuf:"varint,4,opt,name=star_rating,json=starRating,proto3" json:"star_rating,omitempty"`
	WalkingDistanceM int32                  `protobuf:"varint,5,opt,name=walking_distance_m,json=walkingDistanceM,proto3" json:"walking_distance_m,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HotelRef) Reset() {
	*x = HotelRef{}
	mi := &file_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotelRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotelRef) ProtoMessage() {}

func (x *HotelRef) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotelRef.ProtoReflect.Descriptor instead.
func (*HotelRef) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *HotelRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HotelRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HotelRef) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *HotelRef) GetStarRating() int32 {
	if x != nil {
		return x.StarRating
	}
	return 0
}

func (x *HotelRef) GetWalkingDistanceM() int32 {
	if x != nil {
		return x.WalkingDistanceM
	}
	return 0
}

type AirlineRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OperatorKind  string                 `protobuf:"bytes,4,opt,name=operator_kind,json=operatorKind,proto3" json:"operator_kind,omitempty"` // "airline" | "rail" | "bus"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AirlineRef) Reset() {
	*x = AirlineRef{}
	mi := &file_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirlineRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirlineRef) ProtoMessage() {}

func (x *AirlineRef) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirlineRef.ProtoReflect.Descriptor instead.
func (*AirlineRef) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *AirlineRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AirlineRef) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AirlineRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AirlineRef) GetOperatorKind() string {
	if x != nil {
		return x.OperatorKind
	}
	return ""
}

type MuthawwifRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PortraitUrl   string                 `protobuf:"bytes,3,opt,name=portrait_url,json=portraitUrl,proto3" json:"portrait_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuthawwifRef) Reset() {
	*x = MuthawwifRef{}
	mi := &file_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuthawwifRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuthawwifRef) ProtoMessage() {}

func (x *MuthawwifRef) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuthawwifRef.ProtoReflect.Descriptor instead.
func (*MuthawwifRef) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *MuthawwifRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MuthawwifRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MuthawwifRef) GetPortraitUrl() string {
	if x != nil {
		return x.PortraitUrl
	}
	return ""
}

type AddonRef struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ListAmount         int64                  `protobuf:"varint,3,opt,name=list_amount,json=listAmount,proto3" json:"list_amount,omitempty"`
	ListCurrency       string                 `protobuf:"bytes,4,opt,name=list_currency,json=listCurrency,proto3" json:"list_currency,omitempty"`
	SettlementCurrency string                 `protobuf:"bytes,5,opt,name=settlement_currency,json=settlementCurrency,proto3" json:"settlement_currency,omitempty"` // "IDR"
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AddonRef) Reset() {
	*x = AddonRef{}
	mi := &file_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddonRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddonRef) ProtoMessage() {}

func (x *AddonRef) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddonRef.ProtoReflect.Descriptor instead.
func (*AddonRef) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *AddonRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddonRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddonRef) GetListAmount() int64 {
	if x != nil {
		return x.ListAmount
	}
	return 0
}

func (x *AddonRef) GetListCurrency() string {
	if x != nil {
		return x.ListCurrency
	}
	return ""
}

func (x *AddonRef) GetSettlementCurrency() string {
	if x != nil {
		return x.SettlementCurrency
	}
	return ""
}

type ItineraryDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           int32                  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PhotoUrl      string                 `protobuf:"bytes,4,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"` // optional; empty = absent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItineraryDay) Reset() {
	*x = ItineraryDay{}
	mi := &file_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItineraryDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItineraryDay) ProtoMessage() {}

func (x *ItineraryDay) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItineraryDay.ProtoReflect.Descriptor instead.
func (*ItineraryDay) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *ItineraryDay) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *ItineraryDay) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ItineraryDay) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItineraryDay) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

type Itinerary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Days          []*ItineraryDay        `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,3,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Itinerary) Reset() {
	*x = Itinerary{}
	mi := &file_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Itinerary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Itinerary) ProtoMessage() {}

func (x *Itinerary) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Itinerary.ProtoReflect.Descriptor instead.
func (*Itinerary) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *Itinerary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Itinerary) GetDays() []*ItineraryDay {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *Itinerary) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

type ListPackagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All filters optional. Empty string / 0 = no filter.
	Kind          string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // one of the package_kind enum values
	AirlineCode   string `protobuf:"bytes,2,opt,name=airline_code,json=airlineCode,proto3" json:"airline_code,omitempty"`
	HotelId       string `protobuf:"bytes,3,opt,name=hotel_id,json=hotelId,proto3" json:"hotel_id,omitempty"`
	DepartureFrom string `protobuf:"bytes,4,opt,name=departure_from,json=departureFrom,proto3" json:"departure_from,omitempty"` // ISO YYYY-MM-DD
	DepartureTo   string `protobuf:"bytes,5,opt,name=departure_to,json=departureTo,proto3" json:"departure_to,omitempty"`       // ISO YYYY-MM-DD
	Cursor        string `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`                                    // opaque base64
	Limit         int32  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`                                     // 1..100; 0 = default 20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesRequest) Reset() {
	*x = ListPackagesRequest{}
	mi := &file_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesRequest) ProtoMessage() {}

func (x *ListPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesRequest.ProtoReflect.Descriptor instead.
func (*ListPackagesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *ListPackagesRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ListPackagesRequest) GetAirlineCode() string {
	if x != nil {
		return x.AirlineCode
	}
	return ""
}

func (x *ListPackagesRequest) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *ListPackagesRequest) GetDepartureFrom() string {
	if x != nil {
		return x.DepartureFrom
	}
	return ""
}

func (x *ListPackagesRequest) GetDepartureTo() string {
	if x != nil {
		return x.DepartureTo
	}
	return ""
}

func (x *ListPackagesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListPackagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// NextDeparture is the earliest open/closed departure attached to each
// list-row package. Present in ListPackages responses only; may be
// omitted if no upcoming departure exists.
type NextDeparture struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DepartureDate  string                 `protobuf:"bytes,2,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"` // ISO YYYY-MM-DD
	ReturnDate     string                 `protobuf:"bytes,3,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	RemainingSeats int32                  `protobuf:"varint,4,opt,name=remaining_seats,json=remainingSeats,proto3" json:"remaining_seats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NextDeparture) Reset() {
	*x = NextDeparture{}
	mi := &file_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextDeparture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextDeparture) ProtoMessage() {}

func (x *NextDeparture) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextDeparture.ProtoReflect.Descriptor instead.
func (*NextDeparture) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *NextDeparture) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NextDeparture) GetDepartureDate() string {
	if x != nil {
		return x.DepartureDate
	}
	return ""
}

func (x *NextDeparture) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

func (x *NextDeparture) GetRemainingSeats() int32 {
	if x != nil {
		return x.RemainingSeats
	}
	return 0
}

type PackageListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CoverPhotoUrl string                 `protobuf:"bytes,5,opt,name=cover_photo_url,json=coverPhotoUrl,proto3" json:"cover_photo_url,omitempty"`
	StartingPrice *Money                 `protobuf:"bytes,6,opt,name=starting_price,json=startingPrice,proto3" json:"starting_price,omitempty"`
	NextDeparture *NextDeparture         `protobuf:"bytes,7,opt,name=next_departure,json=nextDeparture,proto3" json:"next_departure,omitempty"` // optional; nil = absent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageListItem) Reset() {
	*x = PackageListItem{}
	mi := &file_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageListItem) ProtoMessage() {}

func (x *PackageListItem) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageListItem.ProtoReflect.Descriptor instead.
func (*PackageListItem) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *PackageListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PackageListItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PackageListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageListItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PackageListItem) GetCoverPhotoUrl() string {
	if x != nil {
		return x.CoverPhotoUrl
	}
	return ""
}

func (x *PackageListItem) GetStartingPrice() *Money {
	if x != nil {
		return x.StartingPrice
	}
	return nil
}

func (x *PackageListItem) GetNextDeparture() *NextDeparture {
	if x != nil {
		return x.NextDeparture
	}
	return nil
}

type PageMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextCursor    string                 `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // empty when has_more=false
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageMeta) Reset() {
	*x = PageMeta{}
	mi := &file_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageMeta) ProtoMessage() {}

func (x *PageMeta) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageMeta.ProtoReflect.Descriptor instead.
func (*PageMeta) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *PageMeta) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *PageMeta) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ListPackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*PackageListItem     `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	Page          *PageMeta              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesResponse) Reset() {
	*x = ListPackagesResponse{}
	mi := &file_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesResponse) ProtoMessage() {}

func (x *ListPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesResponse.ProtoReflect.Descriptor instead.
func (*ListPackagesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *ListPackagesResponse) GetPackages() []*PackageListItem {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *ListPackagesResponse) GetPage() *PageMeta {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageRequest) Reset() {
	*x = GetPackageRequest{}
	mi := &file_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageRequest) ProtoMessage() {}

func (x *GetPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageRequest.ProtoReflect.Descriptor instead.
func (*GetPackageRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *GetPackageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DepartureSummary is the compact shape embedded in PackageDetail.departures.
type DepartureSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DepartureDate  string                 `protobuf:"bytes,2,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"` // ISO YYYY-MM-DD
	ReturnDate     string                 `protobuf:"bytes,3,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	RemainingSeats int32                  `protobuf:"varint,4,opt,name=remaining_seats,json=remainingSeats,proto3" json:"remaining_seats,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "open" | "closed"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DepartureSummary) Reset() {
	*x = DepartureSummary{}
	mi := &file_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartureSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartureSummary) ProtoMessage() {}

func (x *DepartureSummary) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartureSummary.ProtoReflect.Descriptor instead.
func (*DepartureSummary) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *DepartureSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DepartureSummary) GetDepartureDate() string {
	if x != nil {
		return x.DepartureDate
	}
	return ""
}

func (x *DepartureSummary) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

func (x *DepartureSummary) GetRemainingSeats() int32 {
	if x != nil {
		return x.RemainingSeats
	}
	return 0
}

func (x *DepartureSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PackageDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Highlights    []string               `protobuf:"bytes,5,rep,name=highlights,proto3" json:"highlights,omitempty"`
	CoverPhotoUrl string                 `protobuf:"bytes,6,opt,name=cover_photo_url,json=coverPhotoUrl,proto3" json:"cover_photo_url,omitempty"`
	Itinerary     *Itinerary             `protobuf:"bytes,7,opt,name=itinerary,proto3" json:"itinerary,omitempty"` // optional; nil = absent
	Hotels        []*HotelRef            `protobuf:"bytes,8,rep,name=hotels,proto3" json:"hotels,omitempty"`
	Airline       *AirlineRef            `protobuf:"bytes,9,opt,name=airline,proto3" json:"airline,omitempty"`      // optional; nil = absent
	Muthawwif     *MuthawwifRef          `protobuf:"bytes,10,opt,name=muthawwif,proto3" json:"muthawwif,omitempty"` // optional; nil = absent
	AddOns        []*AddonRef            `protobuf:"bytes,11,rep,name=add_ons,json=addOns,proto3" json:"add_ons,omitempty"`
	Departures    []*DepartureSummary    `protobuf:"bytes,12,rep,name=departures,proto3" json:"departures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageDetail) Reset() {
	*x = PackageDetail{}
	mi := &file_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageDetail) ProtoMessage() {}

func (x *PackageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageDetail.ProtoReflect.Descriptor instead.
func (*PackageDetail) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *PackageDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PackageDetail) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PackageDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PackageDetail) GetHighlights() []string {
	if x != nil {
		return x.Highlights
	}
	return nil
}

func (x *PackageDetail) GetCoverPhotoUrl() string {
	if x != nil {
		return x.CoverPhotoUrl
	}
	return ""
}

func (x *PackageDetail) GetItinerary() *Itinerary {
	if x != nil {
		return x.Itinerary
	}
	return nil
}

func (x *PackageDetail) GetHotels() []*HotelRef {
	if x != nil {
		return x.Hotels
	}
	return nil
}

func (x *PackageDetail) GetAirline() *AirlineRef {
	if x != nil {
		return x.Airline
	}
	return nil
}

func (x *PackageDetail) GetMuthawwif() *MuthawwifRef {
	if x != nil {
		return x.Muthawwif
	}
	return nil
}

func (x *PackageDetail) GetAddOns() []*AddonRef {
	if x != nil {
		return x.AddOns
	}
	return nil
}

func (x *PackageDetail) GetDepartures() []*DepartureSummary {
	if x != nil {
		return x.Departures
	}
	return nil
}

type GetPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       *PackageDetail         `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageResponse) Reset() {
	*x = GetPackageResponse{}
	mi := &file_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageResponse) ProtoMessage() {}

func (x *GetPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageResponse.ProtoReflect.Descriptor instead.
func (*GetPackageResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *GetPackageResponse) GetPackage() *PackageDetail {
	if x != nil {
		return x.Package
	}
	return nil
}

type GetPackageDepartureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageDepartureRequest) Reset() {
	*x = GetPackageDepartureRequest{}
	mi := &file_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageDepartureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageDepartureRequest) ProtoMessage() {}

func (x *GetPackageDepartureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageDepartureRequest.ProtoReflect.Descriptor instead.
func (*GetPackageDepartureRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *GetPackageDepartureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PackagePricing struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RoomType           string                 `protobuf:"bytes,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"` // "double" | "triple" | "quad"
	ListAmount         int64                  `protobuf:"varint,2,opt,name=list_amount,json=listAmount,proto3" json:"list_amount,omitempty"`
	ListCurrency       string                 `protobuf:"bytes,3,opt,name=list_currency,json=listCurrency,proto3" json:"list_currency,omitempty"`
	SettlementCurrency string                 `protobuf:"bytes,4,opt,name=settlement_currency,json=settlementCurrency,proto3" json:"settlement_currency,omitempty"` // "IDR"
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PackagePricing) Reset() {
	*x = PackagePricing{}
	mi := &file_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackagePricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagePricing) ProtoMessage() {}

func (x *PackagePricing) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagePricing.ProtoReflect.Descriptor instead.
func (*PackagePricing) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *PackagePricing) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *PackagePricing) GetListAmount() int64 {
	if x != nil {
		return x.ListAmount
	}
	return 0
}

func (x *PackagePricing) GetListCurrency() string {
	if x != nil {
		return x.ListCurrency
	}
	return ""
}

func (x *PackagePricing) GetSettlementCurrency() string {
	if x != nil {
		return x.SettlementCurrency
	}
	return ""
}

type VendorReadiness struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticket        string                 `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"` // "not_started" | "in_progress" | "ready" | "blocked"
	Hotel         string                 `protobuf:"bytes,2,opt,name=hotel,proto3" json:"hotel,omitempty"`
	Visa          string                 `protobuf:"bytes,3,opt,name=visa,proto3" json:"visa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorReadiness) Reset() {
	*x = VendorReadiness{}
	mi := &file_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorReadiness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorReadiness) ProtoMessage() {}

func (x *VendorReadiness) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorReadiness.ProtoReflect.Descriptor instead.
func (*VendorReadiness) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *VendorReadiness) GetTicket() string {
	if x != nil {
		return x.Ticket
	}
	return ""
}

func (x *VendorReadiness) GetHotel() string {
	if x != nil {
		return x.Hotel
	}
	return ""
}

func (x *VendorReadiness) GetVisa() string {
	if x != nil {
		return x.Visa
	}
	return ""
}

type DepartureDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PackageId       string                 `protobuf:"bytes,2,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	DepartureDate   string                 `protobuf:"bytes,3,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"` // ISO YYYY-MM-DD
	ReturnDate      string                 `protobuf:"bytes,4,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	TotalSeats      int32                  `protobuf:"varint,5,opt,name=total_seats,json=totalSeats,proto3" json:"total_seats,omitempty"`
	RemainingSeats  int32                  `protobuf:"varint,6,opt,name=remaining_seats,json=remainingSeats,proto3" json:"remaining_seats,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "open" | "closed"
	Pricing         []*PackagePricing      `protobuf:"bytes,8,rep,name=pricing,proto3" json:"pricing,omitempty"`
	VendorReadiness *VendorReadiness       `protobuf:"bytes,9,opt,name=vendor_readiness,json=vendorReadiness,proto3" json:"vendor_readiness,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DepartureDetail) Reset() {
	*x = DepartureDetail{}
	mi := &file_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartureDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartureDetail) ProtoMessage() {}

func (x *DepartureDetail) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartureDetail.ProtoReflect.Descriptor instead.
func (*DepartureDetail) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *DepartureDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DepartureDetail) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *DepartureDetail) GetDepartureDate() string {
	if x != nil {
		return x.DepartureDate
	}
	return ""
}

func (x *DepartureDetail) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

func (x *DepartureDetail) GetTotalSeats() int32 {
	if x != nil {
		return x.TotalSeats
	}
	return 0
}

func (x *DepartureDetail) GetRemainingSeats() int32 {
	if x != nil {
		return x.RemainingSeats
	}
	return 0
}

func (x *DepartureDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DepartureDetail) GetPricing() []*PackagePricing {
	if x != nil {
		return x.Pricing
	}
	return nil
}

func (x *DepartureDetail) GetVendorReadiness() *VendorReadiness {
	if x != nil {
		return x.VendorReadiness
	}
	return nil
}

type GetPackageDepartureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Departure     *DepartureDetail       `protobuf:"bytes,1,opt,name=departure,proto3" json:"departure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageDepartureResponse) Reset() {
	*x = GetPackageDepartureResponse{}
	mi := &file_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageDepartureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageDepartureResponse) ProtoMessage() {}

func (x *GetPackageDepartureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageDepartureResponse.ProtoReflect.Descriptor instead.
func (*GetPackageDepartureResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{20}
}

func (x *GetPackageDepartureResponse) GetDeparture() *DepartureDetail {
	if x != nil {
		return x.Departure
	}
	return nil
}

var File_catalog_proto protoreflect.FileDescriptor

const file_catalog_proto_rawDesc = "" +
	"\n" +
	"\rcatalog.proto\x12\x02pb\"~\n" +
	"\x05Money\x12\x1f\n" +
	"\vlist_amount\x18\x01 \x01(\x03R\n" +
	"listAmount\x12#\n" +
	"\rlist_currency\x18\x02 \x01(\tR\flistCurrency\x12/\n" +
	"\x13settlement_currency\x18\x03 \x01(\tR\x12settlementCurrency\"\x91\x01\n" +
	"\bHotelRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x1f\n" +
	"\vstar_rating\x18\x04 \x01(\x05R\n" +
	"starRating\x12,\n" +
	"\x12walking_distance_m\x18\x05 \x01(\x05R\x10walkingDistanceM\"i\n" +
	"\n" +
	"AirlineRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\roperator_kind\x18\x04 \x01(\tR\foperatorKind\"U\n" +
	"\fMuthawwifRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fportrait_url\x18\x03 \x01(\tR\vportraitUrl\"\xa5\x01\n" +
	"\bAddonRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vlist_amount\x18\x03 \x01(\x03R\n" +
	"listAmount\x12#\n" +
	"\rlist_currency\x18\x04 \x01(\tR\flistCurrency\x12/\n" +
	"\x13settlement_currency\x18\x05 \x01(\tR\x12settlementCurrency\"u\n" +
	"\fItineraryDay\x12\x10\n" +
	"\x03day\x18\x01 \x01(\x05R\x03day\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tphoto_url\x18\x04 \x01(\tR\bphotoUrl\"`\n" +
	"\tItinerary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x04days\x18\x02 \x03(\v2\x10.pb.ItineraryDayR\x04days\x12\x1d\n" +
	"\n" +
	"public_url\x18\x03 \x01(\tR\tpublicUrl\"\xdf\x01\n" +
	"\x13ListPackagesRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12!\n" +
	"\fairline_code\x18\x02 \x01(\tR\vairlineCode\x12\x19\n" +
	"\bhotel_id\x18\x03 \x01(\tR\ahotelId\x12%\n" +
	"\x0edeparture_from\x18\x04 \x01(\tR\rdepartureFrom\x12!\n" +
	"\fdeparture_to\x18\x05 \x01(\tR\vdepartureTo\x12\x16\n" +
	"\x06cursor\x18\x06 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\"\x90\x01\n" +
	"\rNextDeparture\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0edeparture_date\x18\x02 \x01(\tR\rdepartureDate\x12\x1f\n" +
	"\vreturn_date\x18\x03 \x01(\tR\n" +
	"returnDate\x12'\n" +
	"\x0fremaining_seats\x18\x04 \x01(\x05R\x0eremainingSeats\"\xff\x01\n" +
	"\x0fPackageListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12&\n" +
	"\x0fcover_photo_url\x18\x05 \x01(\tR\rcoverPhotoUrl\x120\n" +
	"\x0estarting_price\x18\x06 \x01(\v2\t.pb.MoneyR\rstartingPrice\x128\n" +
	"\x0enext_departure\x18\a \x01(\v2\x11.pb.NextDepartureR\rnextDeparture\"F\n" +
	"\bPageMeta\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"i\n" +
	"\x14ListPackagesResponse\x12/\n" +
	"\bpackages\x18\x01 \x03(\v2\x13.pb.PackageListItemR\bpackages\x12 \n" +
	"\x04page\x18\x02 \x01(\v2\f.pb.PageMetaR\x04page\"#\n" +
	"\x11GetPackageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xab\x01\n" +
	"\x10DepartureSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0edeparture_date\x18\x02 \x01(\tR\rdepartureDate\x12\x1f\n" +
	"\vreturn_date\x18\x03 \x01(\tR\n" +
	"returnDate\x12'\n" +
	"\x0fremaining_seats\x18\x04 \x01(\x05R\x0eremainingSeats\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xbb\x03\n" +
	"\rPackageDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"highlights\x18\x05 \x03(\tR\n" +
	"highlights\x12&\n" +
	"\x0fcover_photo_url\x18\x06 \x01(\tR\rcoverPhotoUrl\x12+\n" +
	"\titinerary\x18\a \x01(\v2\r.pb.ItineraryR\titinerary\x12$\n" +
	"\x06hotels\x18\b \x03(\v2\f.pb.HotelRefR\x06hotels\x12(\n" +
	"\aairline\x18\t \x01(\v2\x0e.pb.AirlineRefR\aairline\x12.\n" +
	"\tmuthawwif\x18\n" +
	" \x01(\v2\x10.pb.MuthawwifRefR\tmuthawwif\x12%\n" +
	"\aadd_ons\x18\v \x03(\v2\f.pb.AddonRefR\x06addOns\x124\n" +
	"\n" +
	"departures\x18\f \x03(\v2\x14.pb.DepartureSummaryR\n" +
	"departures\"A\n" +
	"\x12GetPackageResponse\x12+\n" +
	"\apackage\x18\x01 \x01(\v2\x11.pb.PackageDetailR\apackage\",\n" +
	"\x1aGetPackageDepartureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa4\x01\n" +
	"\x0ePackagePricing\x12\x1b\n" +
	"\troom_type\x18\x01 \x01(\tR\broomType\x12\x1f\n" +
	"\vlist_amount\x18\x02 \x01(\x03R\n" +
	"listAmount\x12#\n" +
	"\rlist_currency\x18\x03 \x01(\tR\flistCurrency\x12/\n" +
	"\x13settlement_currency\x18\x04 \x01(\tR\x12settlementCurrency\"S\n" +
	"\x0fVendorReadiness\x12\x16\n" +
	"\x06ticket\x18\x01 \x01(\tR\x06ticket\x12\x14\n" +
	"\x05hotel\x18\x02 \x01(\tR\x05hotel\x12\x12\n" +
	"\x04visa\x18\x03 \x01(\tR\x04visa\"\xd8\x02\n" +
	"\x0fDepartureDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"package_id\x18\x02 \x01(\tR\tpackageId\x12%\n" +
	"\x0edeparture_date\x18\x03 \x01(\tR\rdepartureDate\x12\x1f\n" +
	"\vreturn_date\x18\x04 \x01(\tR\n" +
	"returnDate\x12\x1f\n" +
	"\vtotal_seats\x18\x05 \x01(\x05R\n" +
	"totalSeats\x12'\n" +
	"\x0fremaining_seats\x18\x06 \x01(\x05R\x0eremainingSeats\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12,\n" +
	"\apricing\x18\b \x03(\v2\x12.pb.PackagePricingR\apricing\x12>\n" +
	"\x10vendor_readiness\x18\t \x01(\v2\x13.pb.VendorReadinessR\x0fvendorReadiness\"P\n" +
	"\x1bGetPackageDepartureResponse\x121\n" +
	"\tdeparture\x18\x01 \x01(\v2\x13.pb.DepartureDetailR\tdeparture2\xee\x01\n" +
	"\x0eCatalogService\x12C\n" +
	"\fListPackages\x12\x17.pb.ListPackagesRequest\x1a\x18.pb.ListPackagesResponse\"\x00\x12=\n" +
	"\n" +
	"GetPackage\x12\x15.pb.GetPackageRequest\x1a\x16.pb.GetPackageResponse\"\x00\x12X\n" +
	"\x13GetPackageDeparture\x12\x1e.pb.GetPackageDepartureRequest\x1a\x1f.pb.GetPackageDepartureResponse\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_catalog_proto_rawDescOnce sync.Once
	file_catalog_proto_rawDescData []byte
)

func file_catalog_proto_rawDescGZIP() []byte {
	file_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)))
	})
	return file_catalog_proto_rawDescData
}

var file_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_catalog_proto_goTypes = []any{
	(*Money)(nil),                       // 0: pb.Money
	(*HotelRef)(nil),                    // 1: pb.HotelRef
	(*AirlineRef)(nil),                  // 2: pb.AirlineRef
	(*MuthawwifRef)(nil),                // 3: pb.MuthawwifRef
	(*AddonRef)(nil),                    // 4: pb.AddonRef
	(*ItineraryDay)(nil),                // 5: pb.ItineraryDay
	(*Itinerary)(nil),                   // 6: pb.Itinerary
	(*ListPackagesRequest)(nil),         // 7: pb.ListPackagesRequest
	(*NextDeparture)(nil),               // 8: pb.NextDeparture
	(*PackageListItem)(nil),             // 9: pb.PackageListItem
	(*PageMeta)(nil),                    // 10: pb.PageMeta
	(*ListPackagesResponse)(nil),        // 11: pb.ListPackagesResponse
	(*GetPackageRequest)(nil),           // 12: pb.GetPackageRequest
	(*DepartureSummary)(nil),            // 13: pb.DepartureSummary
	(*PackageDetail)(nil),               // 14: pb.PackageDetail
	(*GetPackageResponse)(nil),          // 15: pb.GetPackageResponse
	(*GetPackageDepartureRequest)(nil),  // 16: pb.GetPackageDepartureRequest
	(*PackagePricing)(nil),              // 17: pb.PackagePricing
	(*VendorReadiness)(nil),             // 18: pb.VendorReadiness
	(*DepartureDetail)(nil),             // 19: pb.DepartureDetail
	(*GetPackageDepartureResponse)(nil), // 20: pb.GetPackageDepartureResponse
}
var file_catalog_proto_depIdxs = []int32{
	5,  // 0: pb.Itinerary.days:type_name -> pb.ItineraryDay
	0,  // 1: pb.PackageListItem.starting_price:type_name -> pb.Money
	8,  // 2: pb.PackageListItem.next_departure:type_name -> pb.NextDeparture
	9,  // 3: pb.ListPackagesResponse.packages:type_name -> pb.PackageListItem
	10, // 4: pb.ListPackagesResponse.page:type_name -> pb.PageMeta
	6,  // 5: pb.PackageDetail.itinerary:type_name -> pb.Itinerary
	1,  // 6: pb.PackageDetail.hotels:type_name -> pb.HotelRef
	2,  // 7: pb.PackageDetail.airline:type_name -> pb.AirlineRef
	3,  // 8: pb.PackageDetail.muthawwif:type_name -> pb.MuthawwifRef
	4,  // 9: pb.PackageDetail.add_ons:type_name -> pb.AddonRef
	13, // 10: pb.PackageDetail.departures:type_name -> pb.DepartureSummary
	14, // 11: pb.GetPackageResponse.package:type_name -> pb.PackageDetail
	17, // 12: pb.DepartureDetail.pricing:type_name -> pb.PackagePricing
	18, // 13: pb.DepartureDetail.vendor_readiness:type_name -> pb.VendorReadiness
	19, // 14: pb.GetPackageDepartureResponse.departure:type_name -> pb.DepartureDetail
	7,  // 15: pb.CatalogService.ListPackages:input_type -> pb.ListPackagesRequest
	12, // 16: pb.CatalogService.GetPackage:input_type -> pb.GetPackageRequest
	16, // 17: pb.CatalogService.GetPackageDeparture:input_type -> pb.GetPackageDepartureRequest
	11, // 18: pb.CatalogService.ListPackages:output_type -> pb.ListPackagesResponse
	15, // 19: pb.CatalogService.GetPackage:output_type -> pb.GetPackageResponse
	20, // 20: pb.CatalogService.GetPackageDeparture:output_type -> pb.GetPackageDepartureResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_catalog_proto_init() }
func file_catalog_proto_init() {
	if File_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto = out.File
	file_catalog_proto_goTypes = nil
	file_catalog_proto_depIdxs = nil
}
