// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditLogByID = `-- name: GetAuditLogByID :one
SELECT id, user_id, branch_id, resource, resource_id, action,
       old_value, new_value, ip, created_at
FROM iam.audit_logs
WHERE id = $1
`

func (q *Queries) GetAuditLogByID(ctx context.Context, id pgtype.UUID) (IamAuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLogByID, id)
	var i IamAuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BranchID,
		&i.Resource,
		&i.ResourceID,
		&i.Action,
		&i.OldValue,
		&i.NewValue,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO iam.audit_logs (
    user_id, branch_id, resource, resource_id, action,
    old_value, new_value, ip
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, branch_id, resource, resource_id, action,
          old_value, new_value, ip, created_at
`

type InsertAuditLogParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	BranchID   pgtype.UUID `json:"branch_id"`
	Resource   string      `json:"resource"`
	ResourceID string      `json:"resource_id"`
	Action     string      `json:"action"`
	OldValue   []byte      `json:"old_value"`
	NewValue   []byte      `json:"new_value"`
	Ip         *netip.Addr `json:"ip"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (IamAuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.UserID,
		arg.BranchID,
		arg.Resource,
		arg.ResourceID,
		arg.Action,
		arg.OldValue,
		arg.NewValue,
		arg.Ip,
	)
	var i IamAuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BranchID,
		&i.Resource,
		&i.ResourceID,
		&i.Action,
		&i.OldValue,
		&i.NewValue,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentAuditLogsByResource = `-- name: ListRecentAuditLogsByResource :many
SELECT id, user_id, branch_id, resource, resource_id, action,
       old_value, new_value, ip, created_at
FROM iam.audit_logs
WHERE resource = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentAuditLogsByResourceParams struct {
	Resource string `json:"resource"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) ListRecentAuditLogsByResource(ctx context.Context, arg ListRecentAuditLogsByResourceParams) ([]IamAuditLog, error) {
	rows, err := q.db.Query(ctx, listRecentAuditLogsByResource, arg.Resource, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IamAuditLog{}
	for rows.Next() {
		var i IamAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BranchID,
			&i.Resource,
			&i.ResourceID,
			&i.Action,
			&i.OldValue,
			&i.NewValue,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAuditLogsByUser = `-- name: ListRecentAuditLogsByUser :many
SELECT id, user_id, branch_id, resource, resource_id, action,
       old_value, new_value, ip, created_at
FROM iam.audit_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentAuditLogsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListRecentAuditLogsByUser(ctx context.Context, arg ListRecentAuditLogsByUserParams) ([]IamAuditLog, error) {
	rows, err := q.db.Query(ctx, listRecentAuditLogsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IamAuditLog{}
	for rows.Next() {
		var i IamAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BranchID,
			&i.Resource,
			&i.ResourceID,
			&i.Action,
			&i.OldValue,
			&i.NewValue,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
