// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Admin user management (S1-E-06)
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error)
	AdminGetUser(ctx context.Context, id pgtype.UUID) (AdminGetUserRow, error)
	AdminUpdateUserNameStatus(ctx context.Context, arg AdminUpdateUserNameStatusParams) (AdminUpdateUserNameStatusRow, error)
	RevokeAllSessionsForUserAdmin(ctx context.Context, userID pgtype.UUID) error

	// Admin role management (S1-E-06)
	AdminListRoles(ctx context.Context, arg AdminListRolesParams) ([]AdminRoleRow, error)
	AdminGetRoleWithPermissions(ctx context.Context, id pgtype.UUID) (AdminRoleRow, error)
	CountUserRolesForRole(ctx context.Context, roleID pgtype.UUID) (int64, error)

	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CreateBranch(ctx context.Context, arg CreateBranchParams) (IamBranch, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (IamPermission, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (IamRole, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (IamSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (IamUser, error)
	DeleteBranch(ctx context.Context, id pgtype.UUID) error
	DeletePermission(ctx context.Context, id pgtype.UUID) error
	DeleteRole(ctx context.Context, id pgtype.UUID) error
	GetAuditLogByID(ctx context.Context, id pgtype.UUID) (IamAuditLog, error)
	GetBranchByCode(ctx context.Context, code string) (IamBranch, error)
	GetBranchByID(ctx context.Context, id pgtype.UUID) (IamBranch, error)
	GetDbTxDiagnostic(ctx context.Context, id int64) (Diagnostic, error)
	GetPermissionByID(ctx context.Context, id pgtype.UUID) (IamPermission, error)
	GetPermissionByTuple(ctx context.Context, arg GetPermissionByTupleParams) (IamPermission, error)
	GetRoleByID(ctx context.Context, id pgtype.UUID) (IamRole, error)
	GetRoleByName(ctx context.Context, name string) (IamRole, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (IamSession, error)
	GetSessionByRefreshHash(ctx context.Context, refreshTokenHash string) (IamSession, error)
	GetUserByEmail(ctx context.Context, email string) (IamUser, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (IamUser, error)
	GrantPermissionToRole(ctx context.Context, arg GrantPermissionToRoleParams) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (IamAuditLog, error)
	InsertDbTxDiagnostic(ctx context.Context, arg InsertDbTxDiagnosticParams) (Diagnostic, error)
	ListActiveSessionsForUser(ctx context.Context, userID pgtype.UUID) ([]IamSession, error)
	ListBranches(ctx context.Context) ([]IamBranch, error)
	ListPermissionIDsForRole(ctx context.Context, roleID pgtype.UUID) ([]pgtype.UUID, error)
	ListPermissions(ctx context.Context) ([]IamPermission, error)
	ListPermissionsByResource(ctx context.Context, resource string) ([]IamPermission, error)
	ListRecentAuditLogsByResource(ctx context.Context, arg ListRecentAuditLogsByResourceParams) ([]IamAuditLog, error)
	ListRecentAuditLogsByUser(ctx context.Context, arg ListRecentAuditLogsByUserParams) ([]IamAuditLog, error)
	ListRoleIDsForPermission(ctx context.Context, permissionID pgtype.UUID) ([]pgtype.UUID, error)
	ListRoleIDsForUser(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error)
	// ListRoleNamesForUser returns the role names currently assigned to the user.
	// Backs iam.v1.IamService/ValidateToken so downstream services receive role
	// strings alongside identity claims (BL-IAM-002).
	//
	ListRoleNamesForUser(ctx context.Context, userID pgtype.UUID) ([]string, error)
	ListRoles(ctx context.Context) ([]IamRole, error)
	ListUserIDsForRole(ctx context.Context, roleID pgtype.UUID) ([]pgtype.UUID, error)
	ListUsersByBranch(ctx context.Context, branchID pgtype.UUID) ([]IamUser, error)
	ReadyCheck(ctx context.Context) (int32, error)
	RevokeAllPermissionsForRole(ctx context.Context, roleID pgtype.UUID) error
	RevokeAllRolesForUser(ctx context.Context, userID pgtype.UUID) error
	RevokeAllSessionsForUser(ctx context.Context, userID pgtype.UUID) error
	RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error
	RevokeRoleFromUser(ctx context.Context, arg RevokeRoleFromUserParams) error
	RevokeSession(ctx context.Context, id pgtype.UUID) error
	SoftDeleteUser(ctx context.Context, id pgtype.UUID) error
	UpdateBranch(ctx context.Context, arg UpdateBranchParams) (IamBranch, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (IamRole, error)
	UpdateUserLastLoginAt(ctx context.Context, id pgtype.UUID) error
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (IamUser, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpdateUserTOTP(ctx context.Context, arg UpdateUserTOTPParams) error
	// UserHasPermission resolves whether the given user currently holds the
	// (resource, action, scope) permission via any of their assigned roles.
	// Backs iam.v1.IamService/CheckPermission (BL-IAM-002); the hot path must
	// stay a single index-backed join.
	//
	UserHasPermission(ctx context.Context, arg UserHasPermissionParams) (bool, error)

	// IAM Phase 6 admin tables (BL-IAM-007/010/011/014/016)
	UpsertDataScope(ctx context.Context, arg UpsertDataScopeParams) (IamDataScope, error)
	InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (IamAPIKey, error)
	GetAPIKeyByID(ctx context.Context, id string) (IamAPIKey, error)
	RevokeAPIKeyByID(ctx context.Context, id string, revokedAt time.Time) error
	GetAllGlobalConfig(ctx context.Context) ([]IamGlobalConfig, error)
	GetGlobalConfigByKeys(ctx context.Context, keys []string) ([]IamGlobalConfig, error)
	UpsertGlobalConfig(ctx context.Context, arg UpsertGlobalConfigParams) (IamGlobalConfig, error)
	SearchActivityLog(ctx context.Context, arg SearchActivityLogParams) ([]IamAuditLog, error)
}

var _ Querier = (*Queries)(nil)
