// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_permissions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const grantPermissionToRole = `-- name: GrantPermissionToRole :exec
INSERT INTO iam.role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT (role_id, permission_id) DO NOTHING
`

type GrantPermissionToRoleParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) GrantPermissionToRole(ctx context.Context, arg GrantPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, grantPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const listPermissionIDsForRole = `-- name: ListPermissionIDsForRole :many
SELECT permission_id
FROM iam.role_permissions
WHERE role_id = $1
`

func (q *Queries) ListPermissionIDsForRole(ctx context.Context, roleID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listPermissionIDsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var permission_id pgtype.UUID
		if err := rows.Scan(&permission_id); err != nil {
			return nil, err
		}
		items = append(items, permission_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleIDsForPermission = `-- name: ListRoleIDsForPermission :many
SELECT role_id
FROM iam.role_permissions
WHERE permission_id = $1
`

func (q *Queries) ListRoleIDsForPermission(ctx context.Context, permissionID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRoleIDsForPermission, permissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var role_id pgtype.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllPermissionsForRole = `-- name: RevokeAllPermissionsForRole :exec
DELETE FROM iam.role_permissions
WHERE role_id = $1
`

func (q *Queries) RevokeAllPermissionsForRole(ctx context.Context, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllPermissionsForRole, roleID)
	return err
}

const revokePermissionFromRole = `-- name: RevokePermissionFromRole :exec
DELETE FROM iam.role_permissions
WHERE role_id = $1 AND permission_id = $2
`

type RevokePermissionFromRoleParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, revokePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}
