// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO iam.users (email, password_hash, name, branch_id, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, name, branch_id, status,
          totp_secret, totp_verified_at, last_login_at,
          created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string        `json:"email"`
	PasswordHash string        `json:"password_hash"`
	Name         string        `json:"name"`
	BranchID     pgtype.UUID   `json:"branch_id"`
	Status       IamUserStatus `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (IamUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.BranchID,
		arg.Status,
	)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.BranchID,
		&i.Status,
		&i.TotpSecret,
		&i.TotpVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, branch_id, status,
       totp_secret, totp_verified_at, last_login_at,
       created_at, updated_at, deleted_at
FROM iam.users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (IamUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.BranchID,
		&i.Status,
		&i.TotpSecret,
		&i.TotpVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, branch_id, status,
       totp_secret, totp_verified_at, last_login_at,
       created_at, updated_at, deleted_at
FROM iam.users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (IamUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.BranchID,
		&i.Status,
		&i.TotpSecret,
		&i.TotpVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsersByBranch = `-- name: ListUsersByBranch :many
SELECT id, email, password_hash, name, branch_id, status,
       totp_secret, totp_verified_at, last_login_at,
       created_at, updated_at, deleted_at
FROM iam.users
WHERE branch_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListUsersByBranch(ctx context.Context, branchID pgtype.UUID) ([]IamUser, error) {
	rows, err := q.db.Query(ctx, listUsersByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IamUser{}
	for rows.Next() {
		var i IamUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.BranchID,
			&i.Status,
			&i.TotpSecret,
			&i.TotpVerifiedAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE iam.users
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserLastLoginAt = `-- name: UpdateUserLastLoginAt :exec
UPDATE iam.users
SET last_login_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UpdateUserLastLoginAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLoginAt, id)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE iam.users
SET password_hash = $2,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE iam.users
SET name = $2,
    branch_id = $3,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, name, branch_id, status,
          totp_secret, totp_verified_at, last_login_at,
          created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	BranchID pgtype.UUID `json:"branch_id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (IamUser, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Name, arg.BranchID)
	var i IamUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.BranchID,
		&i.Status,
		&i.TotpSecret,
		&i.TotpVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE iam.users
SET status = $2,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserStatusParams struct {
	ID     pgtype.UUID   `json:"id"`
	Status IamUserStatus `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}

const updateUserTOTP = `-- name: UpdateUserTOTP :exec
UPDATE iam.users
SET totp_secret = $2,
    totp_verified_at = $3,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserTOTPParams struct {
	ID             pgtype.UUID        `json:"id"`
	TotpSecret     pgtype.Text        `json:"totp_secret"`
	TotpVerifiedAt pgtype.Timestamptz `json:"totp_verified_at"`
}

func (q *Queries) UpdateUserTOTP(ctx context.Context, arg UpdateUserTOTPParams) error {
	_, err := q.db.Exec(ctx, updateUserTOTP, arg.ID, arg.TotpSecret, arg.TotpVerifiedAt)
	return err
}
