// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO iam.user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const listRoleIDsForUser = `-- name: ListRoleIDsForUser :many
SELECT role_id
FROM iam.user_roles
WHERE user_id = $1
`

func (q *Queries) ListRoleIDsForUser(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRoleIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var role_id pgtype.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleNamesForUser = `-- name: ListRoleNamesForUser :many
SELECT r.name
FROM iam.user_roles ur
JOIN iam.roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.name
`

// ListRoleNamesForUser returns the role names currently assigned to the user.
// Backs iam.v1.IamService/ValidateToken so downstream services receive role
// strings alongside identity claims (BL-IAM-002).
func (q *Queries) ListRoleNamesForUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleNamesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDsForRole = `-- name: ListUserIDsForRole :many
SELECT user_id
FROM iam.user_roles
WHERE role_id = $1
`

func (q *Queries) ListUserIDsForRole(ctx context.Context, roleID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUserIDsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllRolesForUser = `-- name: RevokeAllRolesForUser :exec
DELETE FROM iam.user_roles
WHERE user_id = $1
`

func (q *Queries) RevokeAllRolesForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRolesForUser, userID)
	return err
}

const revokeRoleFromUser = `-- name: RevokeRoleFromUser :exec
DELETE FROM iam.user_roles
WHERE user_id = $1 AND role_id = $2
`

type RevokeRoleFromUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) RevokeRoleFromUser(ctx context.Context, arg RevokeRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, revokeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}
